{% extends "layouts/template.phtml" %}
{% block breadcrumbs %}
<h1 class="page_title">Halaman tidak ditemukan</h1>
{% endblock %}
{% block content %}
<h1 class="not_found page_margin_top_section">404</h1>
<h1 class="page_margin_top_section">Error 404</h1>
<p style="font-size: 14px; padding: 0;" class="page_margin_top">Maaf halaman yang Anda cari tidak ditemukan.<br />
Jika Anda menuju halaman ini melalui penanda browser Anda, mohon untuk mengkinikan data penanda Anda</p>
<a title="Kembali ke Halaman Utama" href="{{ url() }}" class="more blue medium page_margin_top_section">Kembali ke Halaman Utama</a>
{% endblock %}
