{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Tanya Jawab &#8211; Pemrosesan &#038; Penyimpanan</h2>
						<p>Untuk membantu Anda membuat keputusan yang tepat,  kami sudah mengumpulkan beberapa pertanyaan yang sering diajukan kepada kami.</p>

<ul class="accordion page_margin_top">
	<li><div id="accordion-faq4-1"><h3>Bagaimana darah tali pusat disimpan? </h3></div><div class="clearfix">
		<p>Setelah terkumpul, darah tali pusat dikirim ke laboratorium. Kemudian akan diproses oleh staf laboratorium yang terlatih dan secara sistematis dibekukan secara bertahap - minus satu derajat pada satu saat hingga mencapai suhu optimal -180 derajat Celcius, yang kemudian akan disimpan dalam tangki berisi nitrogen cair.</p>
	</div></li>
	
	<li><div id="accordion-faq4-2"><h3>Bagaimana cara penyimpanan darah tali pusat?</h3></div><div class="clearfix">
		<p>Setelah pengambilan, darah tali pusat dikirim ke lab kami. Di sana darah akan diproses oleh lab specialist kami dan dibekukan secara sistematis, ketika darah mencapai suhu -180C, darah akan dipindahkan ke tangki nitrogen cair kami.</p>
	</div></li>
	
	<li><div id="accordion-faq4-3"><h3>Mengapa unit Darah Tali Pusat disimpan dalam 2 kantung, di dua lokasi terpisah?</h3></div><div class="clearfix">
		<p>StemCord adalah satu-satunya bank darah tali pusat di Singapura yang menyimpan darah tali pusat di beberapa unit. Dengan perkembangan yang menjanjikan dalam penggunaan sel punca untuk Terapi Regeneratif, menyimpan sel induk di beberapa unit menyediakan kapasitas untuk beberapa kali penggunaan jika diperlukan. Kami juga mengambil langkah ekstra untuk menyimpan unit darah tali pusat di dua lokasi terpisah sebagai tambahan keamanan dan ketenangan pikiran Anda.</p>
		<h3 style="font-weight:bold;color:#234396;font-size:18px;line-height:120%;margin-top:10px;">Menyimpan darah tali pusat secara terpisah tidak akan mengurangi dosis sel</h3>
		<p>Memiliki darah tali pusat bayi Anda disimpan secara terpisah tidak akan mengurangi dosis sel dan kompromi hasil perawatan di masa depan. Hal ini karena Anda menyimpan di bank darah tali pusat swasta, semua unit darah tali pusat milik anak Anda adalah untuk penggunaan bagi keluarga Anda sendiri. Ini merupakan perbedaan penting dari bank darah tali pusat hibrida <sup>1</sup>, yang juga ada.</p>
		<div style="background-color:#f9bf00;padding:20px;font-style:italic;font-size:90%;line-height:150%;border-radius:5px;">
					<sup>1</sup>1Bank darah tali pusat Hibrida membagi satuan darah tali Anda menjadi dua penyimpanan yang terpisah, yaitu untuk penggunaan pribadi dan umum (public). Mengingat bahwa dosis sel merupakan prediktor penting dari kesuksesan hasil transplantasi , membagi unit darah tali pusat menjadi 2-4 seperti itu mungkin menempatkan potensi dan aplikasi penerima  pada kerugian, oleh karena itu, tidak mungkin, kecuali ekspansi sel punca sukses dan  praktis dilakukan dalam pengaturan ini.<br><br>
				(Rubinstein, P. (2009) Cord blood banking for clinical transplantation. Bone Marrow Transplantation. 44. pp. 635-642)
				</div>
	</div></li>
	
	<li><div id="accordion-faq4-4"><h3>Di mana sel punca ini disimpan?</h3></div><div class="clearfix">
		<p>StemCord menyimpan sample darah tali pusat ini di 2 laboratoriumnya yang dilengkapi dengan teknologi terkini dan tercanggih di Singapura. StemCord adalah satu-satunya bank darah tali pusat yang melakukan pemisahan sample di 2 lokasi. Lab kami dilengkapi dengan generator cadangan, dan system monitoring terkomputerisasi yang membatasi orang yang bisa masuk ke dalam fasilitas penyimpanan kami hanya kepada staf yang berwenang. Lab ini juga dilengkapi dengan system komunikasi yang terhubung kepada teknisi kami sembari memonitor laboratorium dan fasilitas penyimpanan. Keduanya dimonitor 24 jam sehari, 365 hari per tahun, untuk memastikan keamanan sel punca keluarga Anda.</p>
	</div></li>
	
	<li><div id="accordion-faq4-5"><h3>Bagaimana StemCord melindungi sel punca dari kemungkinan kontaminasi dan tertukarnya sample yang satu dengan yang lain? </h3></div><div class="clearfix">
		<p>Setiap darah tali pusat yang kami terima akan ditangani oleh satu lab spesialis sampai ke tahapan tertentu. Ketika Anda mendaftar dengan StemCord, Anda akan mendapat nomor registrasi, yang nomer registrasi ini akan selalu ada di sample dan  dokumen Anda. Kami juga menggunakan sistem penyimpanan dengan 2 kali pembungkusan, untuk mengeliminasi kemungkinan adanya kontaminasi silang selama penyimpanan. Sampai saat ini sistem ini adalah metode penyimpanan yang paling aman.</p>
	</div></li>
	
	<li><div id="accordion-faq4-6"><h3>Berapa lama darah tali pusat ini dapat disimpan?</h3></div><div class="clearfix">
		<p>Karena darah tali pusat disimpan dalam temperatur yang sangat rendah dalam nitrogen cair, maka darah ini dapat disimpan selamanya. Literatur yang pernah diterbitkan telah menunjukkan bahwa sel punca yang disimpan selama 15 tahun tetap dapat mempertahankan viabilitasnya dan mampu berproliferasi, sehingga dapat digunakan untuk transplantasi.</p>
	</div></li>
	
	<li><div id="accordion-faq4-7"><h3>Apakah Saya akan menerima konfirmasi bahwa darah tali pusat bayi Saya dapat disimpan? </h3></div><div class="clearfix">
		<p>Setelah menerima akte kelahiran bayi Anda, maka Stemcord akan mengeluarkan  sertifikat Stemcord dan akan dikirimkan ke alamat Anda.</p>
	</div></li>
	
	<li><div id="accordion-faq4-8"><h3>Panduan apa yang Anda gunakan dalam penyimpanan ini?</h3></div><div class="clearfix">
		<p>Sejak awal didirikan, StemCord sudah mengikuti berbagai langkah pengendalian mutu untuk mempertahankan viabilitas sel punca yang kami simpan. Langkah-langkah ini disesuaikan dengan aturan dan panduan dari standar AABB dan telah disertifikasi oleh Departemen Kesehatan Singapura. Sebagai tambahan, kami sudah mendapatkan akreditasi <a href="{{ url('perbedaan-stemcord/fact-netcord-accreditation') }}" target="_blank">FACT -  NetCord International  Standards</a> untuk pengambilan, pemrosesan, pengujian, penyimpanan, penyeleksian dan pelepasan darah tali pusat, yang membuat kami menjadi bank darah tali pusat pertama di Asia Tenggara untuk mencapai standar Internasional  yang paling bergengsi untuk perbankan darah tali pusat. </p>
	</div></li>
</ul>

<div style="margin-top:120px">&nbsp;</div>
<div class="disclaimer">
<p><sup>2</sup>Current medical literature proves that stem cells can maintain viability for 23 years. Sources:</p>
<p>Broxmeyer HE, et al. Hematopoietic stem/progenitor cells, generation of induced pluripotent stem cells, and isolation of endothelial progenitors from 21 – 23.5-year cryopreserved cord blood.<br>
Blood. 2011. 117(18): 4773-4777. doi:10.1182/blood-2011-01-330514 <a href="http://bloodjournal.hematologylibrary.org/content/117/18/4773.full.pdf" target="_blank">http://bloodjournal.hematologylibrary.org/content/117/18/4773.full.pdf</a></p>
<p>Linden JV, Preti RA, Dracker R. New York state guidelines for cord blood banking.Journal of Hematotherapy. 1997;6:535-41.
Scaradavou, Stevens, Dobrila, Sung, Ruinstein. “Age” of the cord blood (CB) unit: Impact of long-term cryopreservation and storage on transplant outcomes.<br>
Abstract presented at: 49th Annual Meeting of the American Society of Hematology; 2008.</p>
</div>
{% endblock %}