{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Tanya Jawab &#8211; Pengeluaran Darah Tali Pusat</h2>
						<p>Untuk membantu anda membuat keputusan yang tepat,  kami sudah mengumpulkan beberapa pertanyaan yang sering diajukan kepada kami.</p>

<ul class="accordion page_margin_top">
	<li><div id="accordion-faq5-1"><h3>Jika keluarga saya memerlukan darah tersebut, bagaimana saya mengambilnya kembali?</h3></div><div class="clearfix">
		<p>Jika diperlukan, hubungi hotline StemCord di {{ phoneFullTag }} dan kami akan mengeluarkan dan mengirimkan sel punca bayi anda ke rumah sakit yang dituju.</p>
	</div></li>
	
	<li><div id="accordion-faq5-2"><h3>Siapakah pemilik sel punca ini jika si anak sudah dewasa?</h3></div><div class="clearfix">
		<p>StemCord mengakui bahwa ibu adalah pemilik dari sel punca ini sampai si anak mencapai usia 21 tahun. 
Setelah itu, sang ibu berhak memindahkan hak kepemilikannya dan pembayaran biaya pemeliharaannya kepada si anak. </p>
	</div></li>
</ul>
{% endblock %}