{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Tanya Jawab &#8211; Penyimpanan Darah Tali Pusat</h2>
						<p>Untuk membantu Anda membuat keputusan yang tepat,  kami  berinisiatif mengumpulkan beberapa pertanyaan yang sering diajukan kepada kami.</p>

<ul class="accordion page_margin_top">
	<li><div id="accordion-faq2-1"><h3>Apakah Bank Darah Tali Pusat?</h3></div><div class="clearfix">
		<p>Bank darah tali pusat adalah keseluruhan proses pengambilan dan penyimpanan darah yang diambil dari tali pusat dan ari-ari bayi sesaat setelah bayi dilahirkan.</p>
	</div></li>
	
	<li><div id="accordion-faq2-2"><h3>Kapan pertama kali transplantasi darah tali pusat dilakukan?</h3></div><div class="clearfix">
		<p>Transplantasi darah tali pusat yang pertama kali berhasil dilakukan adalah pada tahun 1988 pada seorang anak laki-laki berusia 5 tahun, dengan Anemia Fanconi, yang memiliki usia harapan hidup yang rendah. Donornya adalah adik perempuannya yang baru saja lahir. Lebih dari 17 tahun kemudian, anak laki-laki ini masih hidup dan sembuh dari penyakitnya tersebut.</p>
	</div></li>
	
	<li><div id="accordion-faq2-3"><h3>Seberapa barukah penyimpanan darah tali pusat ini?</h3></div><div class="clearfix">
		<p>Bank darah tali pusat yang pertama didirikan pada tahun 1992. StemCord adalah pelopor penyimpanan darah tali pusat di singapura, didirikan tahun 2002. Saat ini sudah lebih dari 30.000 keluarga telah mengambil keputusan untuk menyimpan darah tali pusat anak mereka di StemCord.</p>
	</div></li>
	
	<li><div id="accordion-faq2-4"><h3>Siapa saja yang perlu menyimpan?</h3></div><div class="clearfix">
		<p>Semua orang tua sebaiknya menyimpan darah tali pusat bayinya kecuali Anda yang telah mendapat peringatan sebelumnya oleh dokter kandungan dikarenakan kondisi kehamilan Anda yang begitu riskan dan tidak memungkinkan untuk proses pengambilan. Penyimpaan darah tali pusat sabagi asuransi biologis ini kami anjurkan untuk para calon orang tua seperti berikut ini:</p>
<h4>Keluarga dengan riwayat kelainan darah dan kanker</h4>
<p>Bank darah tali pusat memberikan potensi untuk transplantasi sel punca sebagai tambahan pilihan pengobatan.</p>
<h4>Keluarga kecil, keluarga dengan anak tunggal, kehamilan yang sulit  atau terlambat atau pasangan kurang subur</h4>
<p>Dalam situasi ini, si anak mungkin saja menjadi anak tunggal, sehingga ada kemungkinan ia tidak mendapatkan donor yang cocok bila diperlukan.</p>
<h4>Perkawinan campur (dari etnis yang berbeda)</h4>
<p>Ini akan sulit bagi pasangan untuk mendapatkan donor yang cocok dikarenakan konstitusi genetik yang sangat berbeda</p>
<h4>Kelahiran anak pertama</h4>
<p>Sangat disarankan untuk menyimpan darah tali pusat dari anak pertama, karena kita tidak pernah tahu apakah akan ada kehamilan yang berikutnya. Sehingga bila anak tersebut menjadi anak tunggal, jika suatu hari nanti darah tali pusat diperlukan, ia tidak perlu bergantung pada sel punca keluarga yang lain.</p>
	</div></li>
	
	<li><div id="accordion-faq2-5"><h3>Mengapa para keluarga-keluarga memilih untuk mengumpulkan dan menyimpan darah tali pusat bayi mereka?</h3></div><div class="clearfix">
		<p>Semakin banyak keluarga yang memilih untuk mengumpulkan, memproses, dan menyimpan darah tali pusat bayi mereka, karena suatu cara yang aman, tidak sakit dan mudah untuk mendapatkan sel punca. Sel punca ini memiliki potensi untuk mengobati berbagai macam penyakit, termasuk kanker, dan kelainan darah seperti anemia, talaseia, dan leukemia.</p>
<p>Menyimpan darah tali pusat adalah kesempatan satu kali seumur hidup, hanya dapat dilakukan pada saat persalinan. Darah tali pusat mengandung sel punca yang muda dan sehat, dan memiliki presentase kecocokan yang tinggi saat digunakan untuk transplantasi. Transplantasi darah tali pusat lebih disukai karena presentase komplikasi yang lebih rendah dibandingkan transplantasi sumsum tulang. Ketika disimpan dalam bank darah tali pusat swasta, darah tali pusat dapat digunakan sewaktu-waktu dibutuhkan, menghemat waktu untuk mencari donor yang cocok.</p>
<p>Garansi 100% kecocokan untuk bayi tersebut. Secara potensial dapat meningkatkan kemungkinan kecocokan untuk saudara kandung dan orang tua.</p>
<p>Calon orang tua menyimpan darah tali pusat untuk keluarga mereka, sel punca tidak hanya menyediakan perlindungan bagi kesehatan lebih dari itu sebagai pilihan pengobatan di masa mendatang. Beberapa keluarga mempunyai faktor risiko yang jelas, tetapi sering orang tua menyimpan untuk keamanan karena mengetahui manfaat dari sel punca suatu saat dibutuhkan untuk anak mereka atau anggota keluarga lainnya.</p>
<p>Studi klinis terakhir menunjukkan bahwa sel punca darah tali pusat memiliki keunikan yang dapat digunakan untuk berbagai macam pengembangan teknologi. Dokter-dokter sangat antusias mengenai potensi darah tali pusat dalam bidang terapi genetic dan memperbaiki sel. Ketika Anda menyimpan darah tali pusat bayi Anda, Anda memberikan kemungkinan pemeliharaan suatu garis kehidupan yang amat berharga yang suatu saat dapat memberikan pilihan pengobatan yang tiada habisnya di masa mendatang.</p>
	</div></li>
	
	<li><div id="accordion-faq2-6"><h3>Apakah Saya harus menyimpan darah tali pusat semua anak Saya?</h3></div><div class="clearfix">
		<p>Darah tali pusat dari setiap anak memiliki keunikan. Menyimpan darah tali pusat dari setiap anak akan memastikan kecocokan genetik bagi setiap anak. Disamping itu akan meningkatkan kemungkinan tambahan Anda memiliki cadangan darah tali pusat bagi anggota keluarga lainnya. Bagi kembar identik, disarankan untuk menyimpan darah tali pusat kedua bayi untuk mendapatkan sel punca dalam jumlah sebanyak-banyaknya. Hal ini diakibatkan pada pengambilan darah saat persalinan kembar biasanya volume yang didapat lebih sedikit, sehingga dengan mengambil darah dari kedua bayi kembar identik ini akan meningkatkan kecukupan jumlah sel punca untuk keperluan transplantasi.</p>
	</div></li>
	
	<li><div id="accordion-faq2-7"><h3>Apakah darah tali pusat bayi Saya bisa digunakan untuk saudara kandungya? </h3></div><div class="clearfix">
		<p>Ya. Darah tali pusat bayi Anda potensial dapat digunakan untuk anggota keluarga yang lain, terutama saudara kandungnya. Kkarena  dalam transplantasi darah tali pusat kita masih dapat menggunakan sel punca ini meskipun ada (hingga) dua antigen yang tidak cocok.</p>
	</div></li>
	
	<li><div id="accordion-faq2-8"><h3>Apakah Saya harus pilih penyimpan darah tali pusat yang dekat dengan rumah Saya?</h3></div><div class="clearfix">
		<p>Keamanan dan kelangsungan hidup sel punca Anda adalah jauh lebih penting ketimbang jarak antara tempat tinggal Anda dan lokasi penyimpanan. Berikut adalah kriteria terpenting dalam memilih bank darah tali pusat adalah:</p>
<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">
Pengambilan darah tali pusat bayi Anda menghasilkan jumlah sel punca sebanyak mungkin, dan sel-selnya masih aktif dan hidup seAndainya nanti diperlukan untuk transplantasi. StemCord telah memberikan kontribusi dalam merawat pasien yang menderita kanker. Keberhasilan transplantasi sel punca yang telah disimpan dengan StemCord ini adalah bukti langkah – langkah pemrosesan dan metode penyimpanan StemCord yang ketat.
	</li>
	<li class="icon_small_arrow right_lightblue">
Laboratorium dan fasilitas penyimpanan StemCord berada di lokasi yang tidak memiliki sejarah terkena bencana alam seperti topan, gempa bumi dan tornado. Laboratorium StemCord terletak di lokasi yang aman di Science Park I dan II. SeAndainya diperlukan, sel punca Anda dapat dikirimkan ke sentral pengobatan di seluruh dunia.
	</li>
	<li class="icon_small_arrow right_lightblue">
Bank darah tali pusat yang stabil secara finansial dan akan tetap eksis di masa depan untuk menjamin sel punca bayi Anda akan selalu tersedia jika diperlukan. StemCord didirikan dengan tujuan  penyimpanan jangka panjang karena kami percaya penggunaan terbaik sel punca di  masa depan. StemCord adalah bank darah tali pusat satu-satunya di Singapura yang menguntungkan  dengan kekuatan finansial untuk mempertahankan kebutuhan jangka panjang penyimpanan darah tali pusat.
	</li>
</ul>
	</div></li>
	
	<li><div id="accordion-faq2-9"><h3>Dapatkah Saya menyimpan darah tali pusat di bank darah tali pusat umum?</h3></div><div class="clearfix">
		<p>Ketika Anda mendonasikan darah tali pusat bayi Anda ke bank darah tali pusat umum, maka darah ini dapat digunakan untuk kepentingan penelitian atau untuk orang lain. Penting sekali bagi para orang tua untuk memahami bahwa tidak semua sampel darah tali pusat yang didonasikan akan disimpan. Disiplin yang sama dilakukan bagi donasi darah pada umumnya, bahwa tidak semua darah layak untuk disimpan. Penolakan dari bank umum dapat berdasarkan dari riwayat kesehatan keluarga, riwayat medis ibu, volume pengumpulan, dan pemeriksaan sampel darah ibu.</p>
<p>Jika sel autolog tidak tersedia atau tidak dapat digunakan, maka pilihan berikutnya adalah sel punca dari keluarga (lebih diutamakan saudara kandung). Darah tali pusat dari orang yang sama sekali tidak memiliki hubungan darah memiliki resiko yang besar untuk terjadinya reaksi penolakan atau GVHD. Darah tali pusat yang memiliki hubungan darah akan mengurangi resiko pada sampel transplantasi yang mungkin mengandung masalah genetik yang dapat menyebabkan penyakit pada penerima donor, ini dikarenakan tidak ada informasi sebelumnya tentang sejarah genetik keluarga si pendonor.</p>
<p>Sel punca darah tali pusat, lebih muda dibandingkan sel punca dewasa maka dari itu memiliki kemungkinan kecocokan yang tinggi dalam garis keluarga dibandingkan sel punca dewasa dari sumsum tulang belakang. Bank darah umum dapat menyediakan kecukupan jumlah sampel akan tetapi tidak dapat menjamin kecocokan yang tinggi antara donor dan penerima. Sementara keluarga yang menyimpan darah tali pusat bayinya akan memiliki kesempatan tinggi untuk mendapatkan darah tali pusat yang cocok bagi anggota keluarganya.</p>
	</div></li>
</ul>
{% endblock %}