{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Tanya Jawab &#8211; Registrasi StemCord</h2>
						<p>Untuk membantu anda membuat keputusan yang tepat,  kami sudah mengumpulkan beberapa pertanyaan yang sering diajukan kepada kami.</p>

<ul class="accordion page_margin_top">
	<li><div id="accordion-faq7-1"><h3>Bagaimana saya mendaftar untuk menyimpan darah tali pusat saya dengan StemCord?</h3></div><div class="clearfix">
		<ol style="line-height:180%;">
			<li style="margin-bottom:10px;">Hubungi {{ phoneFullTag }} untuk registrasi. Staf kami siap untuk membantu anda.</li>
			<li style="margin-bottom:10px;">Registrasi ke StemCord (lebih baik sebelum minggu ke 28 kehamilan), dan anda akan menerima Collection Box Darah Tali Pusat</li>
			<li style="margin-bottom:10px;">Informasikan ke dokter anda</li>
			<li style="margin-bottom:10px;">Bawa Collection Box anda ke rumah sakit</li>
			<li style="margin-bottom:10px;">Hubungi Hotline 24 Jam kami di {{ phoneFullTag }} untuk menjemput darah tali pusat</li>
		</ol>
	</div></li>
	
	<li><div id="accordion-faq7-2"><h3>Berapa biaya yang diperlukan untuk penyimpanan darah tali pusat ini?</h3></div><div class="clearfix">
		<p>Klik <a href="/harga-pendaftaran/harga/">di sini</a> untuk informasi harga.</p>
	</div></li>
	
	<li><div id="accordion-faq7-3"><h3>Kapan sebaiknya saya memutuskan untuk bergabung dengan StemCord?</h3></div><div class="clearfix">
		<p>Kami menyarankan Anda untuk bergabung dengan StemCord sebelum usia kehamilan kurang dari 28 minggu dengan alasan usia kandungan sudah dewasa.</p>
	</div></li>
</ul>
{% endblock %}