{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Tanya Jawab &#8211; Sel Punca Darah Tali Pusat</h2>
						<p>Untuk membantu Anda membuat keputusan yang tepat,  kami  berinisiatif mengumpulkan beberapa pertanyaan yang sering diajukan kepada kami.</p>

<ul class="accordion page_margin_top">
	<li><div id="accordion-faq1-1"><h3>Mengapa darah tali pusat begitu penting?</h3></div><div class="clearfix">
		<p>Darah tali pusat juga dikenal sebagai darah plasenta. Darah tali pusat bayi Anda merupakan sumber yang kaya akan sel punca, yaitu sel yang belum matang, sel pluripoten yang dapat menghasilkan semua sel darah lainnya, termasuk trombosit dan sel darah merah dan sel darah putih. Darah tali pusat bisa digunakan untuk mengobati berbagai kelainan genetik yang dapat mempengaruhi darah dan sistem kekebalan tubuh, leukemia dan solid tumor tertentu dan beberapa kelainan bawaan.</p>
	</div></li>
	
	<li><div id="accordion-faq1-2"><h3>Mengapa sel punca darah sangat berguna dan berharga?</h3></div><div class="clearfix">
		<p>Darah sel punca, paling sering ditemukan di dalam sumsum tulang dan dalam sirkulasi darah tepi, yang adalah pabrik dari sistem peredaran darah kita. Sel-sel ini sangat penting bagi transplantasi sel punca (SCT = StemCell Transplant). SCT adalah pilihan pengobatan yang sangat penting bagi berbagai macam kelainan darah dan kanker. Tanpa darah sel punca, pasien tidak memiliki pilihan untuk melakukan transplantasi, dan kemungkinan tidak memiliki kesempatan untuk sembuh. Oleh karena itu, berbagai bank darah sel punca bermunculan di seluruh dunia untuk menyediakan donor sel punca bagi yang memerlukan. Berbagai bank sel punca ini hadir dalam bentuk sumsum tulang belakang dan bank darah tali pusat. </p>
	</div></li>
	
	<li><div id="accordion-faq1-3"><h3>Apa saja penyakit yang bisa disembuhkan dengan transplantasi sel punca?</h3></div><div class="clearfix">
		<p>A: Untuk saat ini, lebih dari <a href="/bank-darah-tali-pusat/daftar-penyakit-yang-dapat-ditangani/">70 penyakit*</a> dapat disembuhkan dengan transplantasi sel punca. Penelitian menggunakan sel punca masih terus dilakukan untuk terapi regenerasi di mana sel punca dapat membantu mendorong penyembuhan atau regenerasi sel untuk memperbaiki jaringan yang tercantum dalam daftar <a href="/bank-darah-tali-pusat/masa-depan-darah-tali-pusat/">Masa Depan Sel Punca</a>.</p>
	</div></li>
	
	<li><div id="accordion-faq1-4"><h3>Apa kelebihan menggunakan sel punca darah tali pusat jika dibandingkan dengan memakai sumsum tulang belakang?</h3></div><div class="clearfix">
		<h4>Proses pengambilan yang tidak sakit dan tidak beresiko</h4>
<p>Sel punca dari darah tali pusat lebih mudah untuk diambil. Proses pengambilan yang tidak beresiko bagi ibu dan si bayi. Pengambilan sel punca dari sumsum tulang memerlukan prosedur anestesi umum, yang tentu saja memiliki resiko. Pengambilan sel punca dari sumsum tulang juga menimbulkan rasa sakit berbeda dengan pengambilan dari darah tali pusat.</p>
<h4>Selalu tersedia</h4>
<p>Sel punca darah tali pusat yang disimpan dapat tersedia secara cepat jika dibutuhkan. Hal ini tentu sangat menguntungkan, karena dapat mengurangai waktu pencarian donor sel punca yang cocok dengan pasien. Dalam beberapa kondisi tertentu (mis: Anemia Aplastik), pasien tidak memiliki banyak waktu, namun dengan melakukan penyimpanan sel punca darah tali pusat pengobatan dapat segera dilaksanakan.</p>
<h4>Keuntungan Sel Punca Darah Tali Pusat</h4>
<p>Darah tali pusat lebih jarang terkontaminasi oleh virus dan bakteri. Beberapa penelitian menunjukkan bahwa darah tali pusat memiliki kemampuan lebih besar untuk menghasilkan sel darah baru ketimbang sel punca dari sumsum tulang belakang. Bila dihitung, jumlah sel punca dalam darah tali pusat adalah 10 kali lebih banyak daripada sumsum tulang belakang. Fakta ini menunjukkan bahwa untuk sebuah transplantasi hanya diperlukan darah tali pusat dalam jumlah yang lebih sedikit.</p>
<h4>Lebih mudah untuk mencari kecocokan</h4>
<p>Transplantasi sel punca jarang menghasilkan reaksi Graft Versus Host Disease (GVHD) oleh karena itu lebih tidak beresiko bagi resipient (penerima). Hal ini disebabkan sel punca darah tali pusat yang belum begitu matang dibandingkan sumsum tulang dan darah tepi, jadi  sel punca darah tali pusat dapat digunakan bahkan jika hanya setengahnya saja yang cocok. Karena resiko GVHD lebih rendah, transplantasi sel darah tali pusat ini dapat dicoba meskipun test HLA typingnya tidak 100% cocok. Dalam bank darah tali pusat swasta, sel punca yang disimpan hanya untuk kepentingan individu yang bersangkutan. Dengan penjelasan tersebut, maka sel punca ini dapat digunakan pula oleh anggota keluarga yang bersangkutan.</p>
	</div></li>
	
	<li><div id="accordion-faq1-5"><h3>Apa itu HLA-matching?</h3></div><div class="clearfix">
		<p>Dalam suatu transplantasi pada umumnya, Human Leukocyte Antigens (HLA) resipient (penerima) harus cocok dengan sel punca. Antigen-antigen ini berada di permukaan sel darah putih dan permukaan sel-sel lain dalam tubuh, dan yang bertanggung jawab atas terjadinya reaksi penolakan atau GVHD. Pencocokan mengacu pada protein yang disebut HLA yang muncul pada permukaan sel darah putih dan jaringan lain dalam tubuh.  Ke enam Komponen HLA atau lokus, menentukan kompatibilitas jaringan antara pasien dan donor. Meskipun kecocokan yang sempurna akan lebih baik, penelitian telah menunjukkan bahwa transplantasi darah tali pusat bisa sukses bahkan ketika hanya empat dari enam lokus cocok. Sel-sel kekebalan tubuh dalam darah tali pusat kurang matang dibandingkan dengan sumsum tulang belakang, oleh karena itu saudara kandung dari si empunya darah tali pusat akan dua kali lebih punya peluang untuk dapat menggunakan darah tali pusatnya, dibandingkan dengan sumsum tulang.</p>
	</div></li>
	
	<li><div id="accordion-faq1-6"><h3>Apa itu Graft vs Host Disease (GVHD)? </h3></div><div class="clearfix">
		<p>GVHD adalah salah satu efek samping yang paling umum dan paling mematikan dari transplantasi sel punca. GVHD adalah penyebab kematian yang paling banyak pada transplantasi sel punca. GVHD terjadi bila sel punca yang ditransplantasikan menganggap tubuh penerima sebagai benda asing dan menolaknya. Darah tali pusat memiliki tingkat insiden GVHD yang lebih jarang karena sel punca dari donor tidak harus 100% cocok dengan penerima.</p>
	</div></li>
	
	<li><div id="accordion-faq1-7"><h3>Apa keterbatasan pada sel punca darah tali pusat dalam mengobati penyakit?</h3></div><div class="clearfix">
		<p>Sel punca darah tali pusat (dan sel punca pada umumnya) saat ini digunakan terutama untuk mengobati kelainan darah dan kanker. Sementara penggunaannya di masa mendatang hanya dibatasi oleh imajinasi kita.</p>
	</div></li>
	
	<li><div id="accordion-faq1-8"><h3>Bagaimana masa depan transplantasi darah tali pusat?</h3></div><div class="clearfix">
		<p>Darah tali pusat sudah digunakan dalam ribuan transplantasi bagi anak-anak dan orang dewasa di seluruh dunia. Penelitian menunjukkan bahwa sel punca darah tali pusat dapat berdiferensiasi menjadi berbagai macam tipe sel tubuh. Kemampuan regenerasi sel punca telah dibawa ke garis depan dalam bidang reparasi sel. Sel punca telah disebut sebagai sumber biologis yang penting dan peneliti sedang melakukan lebih banyak lagi penelitian untuk mencari potensi sel punca darah tali pusat dalam aplikasinya untuk penyakit-penyakit seperti Alzheimer, diabetes, penyakit jantung dan liver, muscular dystrophy, Parkinson, cedera tulang punggung dan stroke. <br />
<div class="disclaimer">Penggunaan baru untuk stem sel darah tali pusat sedang dalam penelitian. Bank darah tali pusat tidak menjamin bahwa sel akan menyediakan obat dan dapat diaplikasikan untuk setiap situasi. Dokter akan menentukan pengobatan yang paling utama. Penggunaan sel punca dari darah tali pusat untuk metode pengobatan masih merupakan eksperimental. Silahkan bekonsultasi ke dokter Anda.</div></p>
	</div></li>
	
	<li><div id="accordion-faq1-9"><h3>Adakah isu etis yang berkaitan dengan transplantasi darah tali pusat?</h3></div><div class="clearfix">
		<p>Tidak seperti penggunaan sel punca dari embrio, tidak ada isu etis untuk darah tali pusat. Jika sel dari sumber ini tidak disimpan, maka darah tali pusat ini akan dibuang dan dengan demikian sel punca yang berharga ini akan hilang. Pengambilan dari sel unik ini hanya dapat dilakukan pada saat persalinan seorang anak.</p>
	</div></li>

</ul>									
{% endblock %}