{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Tanya Jawab &#8211; Tentang FACT-NetCord</h2>
						<p>Untuk membantu anda membuat keputusan yang tepat,  kami sudah mengumpulkan beberapa pertanyaan yang sering diajukan kepada kami.</p>

<ul class="accordion page_margin_top">
	<li><div id="accordion-faq8-1"><h3>Apa itu FACT-NetCord?</h3></div><div class="clearfix">
		<p>FACT (Foundation for the Accreditation of Cellular Therapy) menetapkan dan mempromosikan standar tertinggi untuk kualitas perawatan pasien dan kinerja laboratorium dengan keyakinan bahwa sebuah akreditasi yang sah  sebaiknya menilai dari kedua aspek . NetCord foundation adalah suatu jaringan Internasional non-profit bank darah tali pusat publik diciptakan untuk mempromosikan terbentuknya bank darah tali pusat dengan kualitas tinggi dan meningkatkan kualitas produk darah tali pusat melalui studi dan penelitian.</p>
<p>Menyadari dampak global perbankan darah tali pusat dan transplantasi, FACT bekerja sama dengan NetCord di tahun 2000 untuk mengembangkan standar Internasional untuk pengambilan, pengolahan, pengujian, perbankan, seleksi dan pelepasan darah tali pusat. Sampai saat ini, FACT-NetCord adalah organisasi akreditasi yang paling bergengsi khususnya untuk bank darah tali pusat.</p>
	</div></li>
	
	<li><div id="accordion-faq8-2"><h3>Siapa yang mengembangkan program akreditasi FACT-NetCord?</h3></div><div class="clearfix">
		<p>Inspeksi dan program  akreditasi FACT dikembangkan oleh Dr. Phyllis Warkentin, Direktur Medis FACT, direktur dan pejabat FACT, serta lembaga internasional untuk terapi sel (ISCT), Lembaga Amerika untuk transplantasi darah dan sumsum tulabf ( ASBMT) , dan regulasi standar. Edisi pertama FACT standar dipublikasikan pada tahun 2000.</p>
	</div></li>
	
	<li><div id="accordion-faq8-3"><h3>Apa yang membedakan akreditasi FACT-NetCord dengan yang lainnya?</h3></div><div class="clearfix">
		<p>FACT-NetCord adalah satu-satunya organisasi akreditasi yang menangani semua aspek kualitas terapi sel hematopoietic (pengumpulan, pengolahan, dan transplantasi). Sebuah akreditasi FACT-NetCord diberikan setelah sukses pendokumentasian / bukti sesuai dengan standar FACT-NetCord. Standar ini dikembangkan oleh tim ahli yang terkenal di dunia internasional di bidang terapi seluler. Mereka hanya melingkupi  seperangkat persyaratan internasional yang mencakup klinis maupun praktek laboratorium, dengan kepercayaan bahwa kualitas hanya bisa didapat jika masalah klinis dan laboratorium  secara efektif ditangani. FACT-NetCord adalah kualifikasi all-but-necessary untuk dapat diterima dan kompetitif di bidang terapi sel. </p>
	</div></li>
</ul>
{% endblock %}