{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Tanya Jawab &#8211; Tentang StemCord</h2>
						<p>Untuk membantu anda membuat keputusan yang tepat,  kami sudah mengumpulkan beberapa pertanyaan yang sering diajukan kepada kami.</p>

<ul class="accordion page_margin_top">
	<li><div id="accordion-faq6-1"><h3>Apakah laboratorium StemCord adalah milik StemCord sendiri?</h3></div><div class="clearfix">
		<p>Ya. StemCord mempunyai hak kepemilikan penuh atas kedua laboratorium kami di Science Park I dan II.</p>
	</div></li>
	
	<li><div id="accordion-faq6-2"><h3>Berapa banyak sample darah tali pusat yang sudah disimpan oleh StemCord?</h3></div><div class="clearfix">
		<p>Lebih dari 25.000 sampel darah yang telah dipercayakan kepada Sstemcord.</p>
	</div></li>
	
	<li><div id="accordion-faq6-3"><h3>Dokter / Rumah Sakit mana yang telah mengambil darah untuk StemCord?</h3></div><div class="clearfix">
		<p>StemCord telah mengumpulkan darah dari berbagai macam rumah sakit di seluruh Indonesia.</p>
	</div></li>
	
	<li><div id="accordion-faq6-4"><h3>Apakah ada sample StemCord yang telah digunakan dalam transplantasi?</h3></div><div class="clearfix">
		<p>Ya, ada.</p>
	</div></li>
	
	<li><div id="accordion-faq6-5"><h3>Bagaimana saya bisa tahu bahwa sel sel punca yang dibekukan ni akan bekerja ketika kita perlu untuk menggunakannya beberapa tahun kemudian?</h3></div><div class="clearfix">
		<p>Stemcord telah berkontribusi untuk perawatan pasien dengan kanker seperti Lymphomas, Myelomas, Leukeumia, Germ cell tumor, dan Sarcomas.  Sel punca diambil dari darah atau sumsum tulang pasien, diproses dan disimpan di Laboratorium Stemcord, dan kemudian digunakan dalam transplantasi sel punca konvensional.</p>
	</div></li>
	
	<li><div id="accordion-faq6-6"><h3>Apakah StemCord kuat secara financial?</h3></div><div class="clearfix">
		<p>StemCord tidak terlibat dalam penelitian dan pengembagan sel punca, karena keduanya sangat membutuhkan dana yang besar dan berpotensi melumpuhkan kemampuan financial perusahaan ini. StemCord sendiri percaya bahwa penggunaan terbaik dari sel punca ini adalah di masa depan, sehingga perusahaan ini harus tetap ada bagi para kliennya, untuk memastikan bahwa klien kami dapat menggunakan darah tali pusat yang sudah mereka simpan. StemCord sendiri adalah satu-satunya perusahaan bank darah tali pusat yang mendapatkan keuntungan, dan hal ini menjamin kelangsungan perusahaan ini sampai suatu saat nanti anda memerlukan sel punca yang anda percayakan kepada kami.</p>
	</div></li>
	
</ul>
{% endblock %}