{% extends "layouts/template.phtml" %}
{% block content %}
		<ul class="blog clearfix">
		
			 	
		<li id="post-1687" class="post-1687 stemcord-news type-stemcord-news status-publish hentry clearfix">

<div class="post_content page_margin_top clearfix">

			<div class="blglist-head clearfix">

					<div class="blglist-image"><img width="150" height="102" src="http://www.stemcord.com/wp-content/uploads/2013/09/stem-cell-therapy-wipes-out-HIV-150x102.jpg" class="attachment-thumbnail wp-post-image" alt="Stem-cell therapy wipes out HIV" /></div> <!-- blglist-image -->
				
		<div class="blglist-title">
		
	
	<h2 style="margin-bottom:10px;"><a href="#">Terapi Sel Punca menghapuskan HIV pada dua pasien</a></h2>
	<div class="author"> Reuters | Ben Hirschler | July 3, 2013 8:04 AM </div>
	
			</div><!-- blglist-title --></div><!-- blglist-head -->
		
	<div class="blglist-content">
		<p>LONDON (Reuters) – Dua orang penderita HIV telah off/ tidak memakan obat-obatan AIDS selama beberapa bulan setelah menerima transplantasi sel punca untuk kankernya yang nampaknya telah membersihkan virus dari tubuh mereka, para peneliti melaporkan pada hari Rabu.</p>
	</div>
	
		
			
</div><!--post_content-->

</li><!--post-->			
		 	
		<li id="post-1660" class="post-1660 stemcord-news type-stemcord-news status-publish hentry clearfix">

<div class="post_content page_margin_top clearfix">

			<div class="blglist-head clearfix">

					<div class="blglist-image"><img width="150" height="102" src="http://www.stemcord.com/wp-content/uploads/2013/08/Stem-Cells-Successfully-Treat-Cerebral-Palsy-150x102.jpg" class="attachment-thumbnail wp-post-image" alt="Stem Cells Successfully Treat Cerebral Palsy" /></div> <!-- blglist-image -->
				
		<div class="blglist-title">
		
	
	<h2 style="margin-bottom:10px;"><a href="#" rel="bookmark" title="Terapi Sel Punca Berhasil Mengobati Cerebral Palsy, Membangunkan dari Keadaan Vegetatif">Terapi Sel Punca Berhasil Mengobati Cerebral Palsy, Membangunkan dari Keadaan Vegetatif</a></h2>
	<div class="author"> By Anthony Rivas | Medical Daily | May 24, 2013 </div>
	
			</div><!-- blglist-title --></div><!-- blglist-head -->
		
	<div class="blglist-content">
		<p>Para dokter berhasil mengobati seorang anak laki berusia 2,5 tahun yang menderita serangan jantung berhenti (cardiac arrest) dan kerusakan otak, yang menyebabkan anak ini dalam keadaan vegetatif, dengan menggunakan darah tali pusatnya sendiri yang mengandung sel punca, <a href="http://aktuell.ruhr-uni-bochum.de/pm2013/pm00151.html.en" target="_blank">disampaikan siaran pers.</a>.</p>
	</div>
	
		
			
</div><!--post_content-->

</li><!--post-->			
		 	
		<li id="post-1662" class="post-1662 stemcord-news type-stemcord-news status-publish hentry clearfix">

<div class="post_content page_margin_top clearfix">

			<div class="blglist-head clearfix">

					<div class="blglist-image"><img width="150" height="102" src="http://www.stemcord.com/wp-content/uploads/2013/08/Stem-Cell-Scientists-Win-Nobel-Prize-150x102.jpg" class="attachment-thumbnail wp-post-image" alt="Stem Cell Scientists Win Nobel Prize" /></div> <!-- blglist-image -->
				
		<div class="blglist-title">
		
	
	<h2 style="margin-bottom:10px;"><a href="#" rel="bookmark" title="Ilmuwan Sel Punca Meraih Hadiah Nobel">Ilmuwan Sel Punca Meraih Hadiah Nobel</a></h2>
	<div class="author"> By GAUTAM NAIK | Wall Street Journal | Oct 8th 2012 </div>
	
			</div><!-- blglist-title --></div><!-- blglist-head -->
		
	<div class="blglist-content">
		<p>Dua peneliti sel punca telah memenangkan Hadiah Nobel tahun ini dalam Fisiologi atau Kedokteran atas terobosan mereka dalam pemrograman ulang sel, suatu teknik yang mengungkapkan kemajuan pesat di bidang biologi, mulai dari kloning hingga kemungkinan pengobatan penyakit menggunakan sel dari pasien sendiri.</p>
	</div>
	
		
			
</div><!--post_content-->

</li><!--post-->			
		 	
					
		
			</ul> <!-- blog -->
<p>Untuk artikel-artikel menarik lainnya, silahkan klik <a href="http://stemcord-indonesia.blogspot.com/">Blog Stemcord Indonesia</a>.</p>
{% endblock %}