{% extends "layouts/template.phtml" %}
{% block content %}

		<div id="post-1176" class="post-1176 page type-page status-publish hentry">
			
		<div class="tabs">
		<ul class="tabs_navigation clearfix">
		<li><a href="#Upcoming_Educational_Talks" title="Upcoming Educational Talks">Event Yang Akan Datang</a></li>
		<li><a href="#Past_Educational_Talks" title="Past Educational Talks">Event Yang Lalu</a></li></ul>
		
		<ul id="Upcoming_Educational_Talks" class="clearfix"><p class="page_margin_top" style="text-align:center;width:100%;">Belum ada event yang akan datang.<br>Silahkan datang kembali nanti.</p></ul>
		
		<!--Upcoming_Educational_Talks-->
		
		<ul id="Past_Educational_Talks" class="clearfix">
		<li class="news_and_event"><div class="news_and_event_content clearfix">
		<div class="column_left"><img width="300" height="157" src="http://www.stemcord.com/wp-content/uploads/2013/08/PB_Page_Banner-300x157.jpg" class="attachment-medium wp-post-image" alt="Pregnancy &amp; Beyond" /></div>
		<div class="column_right"><h2 class="box_header">Pregnancy & Beyond</h2>
		<div class="news_and_event_text">Don’t miss this chance to prepare well for your pregnancy
with advice from our specialists.  Register today for this much anticipated event!</div><a href="http://www.stemcord.com/stemcord-events/educational-talks/pregnancy-and-beyond/" title="Pregnancy & Beyond">Read More</a></div></div></li>
		<li class="news_and_event">
		<div class="news_and_event_content clearfix">
		<div class="column_left"><img width="300" height="190" src="http://www.stemcord.com/wp-content/uploads/2013/04/StemCord-Joy-of-Motherhood-300x190.jpg" class="attachment-medium wp-post-image" alt="StemCord Joy of Motherhood Event" /></div>
		<div class="column_right"><h2 class="box_header">Joy of Motherhood</h2>
		<div class="news_and_event_text">It was a full house at the Gleneagles Hospital lecture theatre on the 9th of March, Saturday, as expectant parents steadily filled up the seats and awaited the start of the day’s programme which consisted of talks and live demonstrations given by the resident doctor, chef, and medical specialists. With topics such as labour pains,
		</div><a href="http://www.stemcord.com/stemcord-events/educational-talks/joy-of-motherhood/" title="Joy of Motherhood">Read More</a></div></div></li></ul>
<!--Past_Educational_Talks-->

</div><!--tabs-->		</div><!--end post-->
{% endblock %}
