{% extends "layouts/template.phtml" %}
{% block content %}
		<ul class="blog clearfix">
		
			 	
		<li id="post-2012" class="post-2012 press-releases type-press-releases status-publish hentry clearfix">

<div class="post_content page_margin_top clearfix">

			<div class="blglist-head clearfix">

					<div class="blglist-image"><img width="150" height="90" src="http://www.stemcord.com/wp-content/uploads/2014/04/opening-of-stemcord-second-sales-office-150x90.jpg" class="attachment-thumbnail wp-post-image" alt="Opening of StemCord&#039;s Second Sales Office" /></div> <!-- blglist-image -->
				
		<div class="blglist-title">
		
	
	<h2 style="margin-bottom:10px;"><a href="#" rel="bookmark" title="StemCord Meningkatkan Kesadaran akan Bank Darah Tali Pusat dengan Pembukaan Kantor Penjualan di Mount Elizabeth Novena">StemCord Meningkatkan Kesadaran akan Bank Darah Tali Pusat dengan Pembukaan Kantor Penjualan di Mount Elizabeth Novena</a></h2>
	<div class="author">  </div>
	
			</div><!-- blglist-title --></div><!-- blglist-head -->
		
	<div class="blglist-content clearfix">
		<p>Singapura, 26 Maret 2014 - StemCord, Bank Darah Tali Pusat pertama di Asia Tenggara dan Singapura yang berhasil mendapatkan akreditasi FACT-NetCord, baru saja meresmikan kantor penjualan baru di <a href="/untuk-klien/kontak-kami/" title="Kontak Kami">Mount Elizabeth Novena</a>.
</p>
	</div>
	
		
			
	
</div><!--post_content-->

</li><!--post-->
{% endblock %}