{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Disclaimer</h2>
						<p>New uses for cord blood stem cells are being discovered rapidly. However, banking cord blood does not guarantee that the cells will provide a cure or be applicable to every situation. The treating physician will determine the ultimate use.</p>

<p>The newborn may be able to use his or her cord blood for some of the conditions on this website, but not all. In some cases, a matched sibling&#8217;s stem cells would be the first choice. There is no guarantee that the umbilical cord blood will be a match for a family member or will provide a cure. Autologous cord blood stem cells will not guarantee suitable treatment for all inherited genetic diseases. As with any transplant therapy, therapeutic success depends upon many factors beyond the stem cells themselves, including patient condition, type of disease, recipient-donor relationship and matching, and other factors.</p>

<p>The use of emerging cord blood stem cells for emerging treatments is experimental. Please consult your physician.</p>									
{% endblock %}