{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Privacy Policy</h2>
						<p>Your privacy is important to us. To better protect your privacy we provide this notice explaining our online information practices and the choices you can make about the way your information is collected and used. StemCord does not capture and store any personal information about individuals who access this website, except where the individual voluntarily chooses to give personal details via email, or by enquiring about any of our services. In these cases, the personal data provided to StemCord will be used exclusively for providing the information requested for. StemCord will not share personal data to outside organizations and/or individuals, except with your expressed consent. StemCord’s web applications only use cookies to assist in site navigation and session management so that visitors to our site remain anonymous.</p>

<h3 class="page_margin_top">Disclaimer</h3>

<p>StemCord and the hosts of this site accepts no responsibility for and exclude all liability in connection with browsing this site, use of information on this site and downloading any material from it including but not limited to any liability for errors, inaccuracies, omissions or misleading or defamatory statements. The information contained in this website may include opinions or views which, unless expressly stated otherwise, are not those of StemCord or any associated company or any person in relation to whom they would have vicarious liability or responsibility.</p>

<p>While StemCord makes every effort to maintain the accuracy of the information on this website, the company cannot accept responsibility for any loss or damage which may occur from use of information.</p>

<p>StemCord does not provide quality control of external links the inclusion of any company&#8217;s name within the pages should not be construed as a recommendation of that company&#8217;s products and/or services.</p>

<h3 class="page_margin_top">How to Contact Us</h3>

<p>Should you have any other questions or concerns about these policies, please call us at {{ phoneFullTag }} or send us an <a href="mailto:info@stemcord.co">email</a>.</p>									
{% endblock %}