{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Site Map</h2>
						<ul class="columns page_margin_top clearfix">
<li class="column_left">
<h3>Bank Darah Tali Pusat</h3>
<p>
<a  href="{{ url('bank-darah-tali-pusat/keuntungan-bank-darah-tali-pusat') }}">Keuntungan Bank Darah Tali Pusat</a><br />
<a  href="{{ url('bank-darah-tali-pusat/sel-punca-darah-tali-pusat') }}">Sel Punca Darah Tali Pusat</a><br />
<a  href="{{ url('bank-darah-tali-pusat/penyimpanan-darah-tali-pusat') }}">Penyimpanan Darah Tali Pusat</a><br />
<a  href="{{ url('bank-darah-tali-pusat/pengambilan-darah-tali-pusat') }}">Pengambilan Darah Tali Pusat</a><br />
<a  href="{{ url('bank-darah-tali-pusat/pemrosesan-penyimpanan-darah-tali-pusat') }}">Pemrosesan &#038; Penyimpanan Darah Tali Pusat</a><br />
<a  href="{{ url('bank-darah-tali-pusat/pengambilan-darah-tali-pusat') }}">Pengambilan Darah Tali Pusat</a><br />
<a  href="{{ url('bank-darah-tali-pusat/daftar-penyakit-yang-dapat-ditangani') }}">Daftar Penyakit yang Dapat Ditangani</a><br />
<a  href="{{ url('bank-darah-tali-pusat/masa-depan-darah-tali-pusat') }}">Masa Depan Darah Tali Pusat</a>
</p>
</li>
<li class="column_right">
<h3>Perbedaan StemCord</h3>
<p>
<a  href="{{ url('perbedaan-stemcord/mengapa-stemcord') }}">Mengapa StemCord?</a><br />
<a  href="{{ url('perbedaan-stemcord/keuntungan-stemcord') }}">Keuntungan StemCord</a><br />
<a  href="{{ url('perbedaan-stemcord/stemcord-bonus-cover') }}">StemCord Bonus Cover</a><br />
<a  href="{{ url('perbedaan-stemcord/fact-netcord-accreditation') }}">FACT-NetCord Accreditation</a><br />
<a  href="{{ url('perbedaan-stemcord/langkah-langkah-penyimpanan-dengan-stemcord') }}">Langkah-langkah Penyimpanan Dengan StemCord</a>
</p>
</li>
</ul>

<ul class="columns page_margin_top clearfix">
<li class="column_left">
<h3>Harga &amp; Pendaftaran</h3>
<p>
<a href="{{ url('harga-pendaftaran/harga') }}" title="Harga">Harga</a><br />
<a href="{{ url('harga-pendaftaran/bagaimana-caranya-mendaftar') }}" title="Bagaimana Caranya Mendaftar">Bagaimana Caranya Mendaftar</a><br />
<a href="{{ url('harga-pendaftaran/permintaan-information-kit') }}" title="Permintaan Information Kit">Permintaan Information Kit</a>
</p>
</li>
<li class="column_right">
<h3>Event &amp; Artikel</h3>
<p>
<a href="{{ url('event-artikel/event') }}" title="Event">Event</a><br />
<a href="{{ url('event-artikel/artikel') }}" title="Artikel">Artikel</a><br />
<a href="{{ url('event-artikel/siaran-pers') }}" title="Siaran Pers">Siaran Pers</a><br />
</p>
</li>
</ul>

<ul class="columns page_margin_top clearfix">
<li class="column_left">
<h3>Tentang Kami</h3>
<p>
<a href="{{ url('tentang-kami/tentang-stemcord') }}" title="Tentang StemCord">Tentang StemCord</a><br />
<a href="{{ url('tentang-kami/layanan-kami') }}" title="Layanan Kami">Layanan Kami</a><br />
<a href="{{ url('tentang-kami/pendiri') }}" title="Pendiri">Pendiri</a><br />
<a href="{{ url('tentang-kami/sejarah') }}" title="Sejarah">Sejarah</a><br />
<a href="{{ url('tentang-kami/akreditasi') }}" title="Akreditasi">Akreditasi</a><br />
<a href="{{ url('tentang-kami/fasilitas') }}" title="Fasilitas">Fasilitas</a><br />
<a href="{{ url('tentang-kami/video-kami') }}" title="Video Kami">Video Kami</a><br />
</p>
</li>
<li class="column_right">
<h3>Tanya Jawab</h3>
<p>
<a href="{{ url('tanya-jawab/sel-punca-darah-tali-pusat') }}" title="Sel Punca Darah Tali Pusat">Sel Punca Darah Tali Pusat</a><br />
<a href="{{ url('tanya-jawab/penyimpanan-darah-tali-pusat') }}" title="Penyimpanan Darah Tali Pusat">Penyimpanan Darah Tali Pusat</a><br />
<a href="{{ url('tanya-jawab/pengambilan-darah-tali-pusat') }}" title="Pengambilan Darah Tali Pusat">Pengambilan Darah Tali Pusat</a><br />
<a href="{{ url('tanya-jawab/pemrosesan-penyimpanan') }}" title="Pemrosesan &#038; Penyimpanan">Pemrosesan &#038; Penyimpanan</a><br />
<a href="{{ url('tanya-jawab/pengeluaran-darah-tali-pusat') }}" title="Pengeluaran Darah Tali Pusat">Pengeluaran Darah Tali Pusat</a><br />
<a href="{{ url('tanya-jawab/tentang-stemcord') }}" title="Tentang StemCord">Tentang StemCord</a><br />
<a href="{{ url('tanya-jawab/registrasi-stemcord') }}" title="Registrasi StemCord">Registrasi StemCord</a><br />
<a href="{{ url('tanya-jawab/tentang-fact-netcord') }}" title="Tentang FACT-NetCord">Tentang FACT-NetCord</a><br />
</p>
</li>
</ul>

<ul class="columns page_margin_top clearfix">
<li class="column_left">
<h3>Layanan Pelanggan</h3>
<p>
<a href="{{ url('layanan-pelanggan/friend-refer-friend') }}" title="Friend Refer Friend">Friend Refer Friend</a><br />
<a href="{{ url('layanan-pelanggan/penyerahan-dokumen') }}" title="Penyerahan Dokumen">Penyerahan Dokumen</a><br />
<a href="{{ url('layanan-pelanggan/perbaharui-informasi-anda') }}" title="Perbaharui Informasi Anda">Perbaharui Informasi Anda</a><br />
<a href="{{ url('layanan-pelanggan/download-form') }}" title="Download Form">Download Form</a><br />
<a href="{{ url('layanan-pelanggan/pilihan-pembayaran') }}" title="Pilihan Pembayaran">Pilihan Pembayaran</a><br />
<a href="{{ url('layanan-pelanggan/kotak-saran') }}" title="Kotak Saran">Kotak Saran</a><br />
</p>
</li>
<li class="column_right">
<h3>Untuk Klien</h3>
<p>
<a href="{{ url('untuk-klien/buat-enquiry') }}" title="Buat Enquiry">Buat Enquiry</a><br />
<a href="{{ url('untuk-klien/tanya-dokter') }}" title="Tanya Dokter">Tanya Dokter</a><br />
<a href="{{ url('untuk-klien/buat-janji') }}" title="Buat Janji">Buat Janji</a><br />
<a href="{{ url('untuk-klien/kontak-kami') }}" title="Kontak Kami">Kontak Kami</a><br />
</p>
</li>
</ul>

<ul class="columns page_margin_top clearfix">
<li class="column_left">
<h3>Blog</h3>
<p><a href="#" title="Blog">Blog</a></p>
</li>
<li class="column_right">
<h3>Footnotes</h3>
<p>
<a href="{{ url('footnotes/privacy-policy') }}">Privacy</a><br />
<a href="{{ url('footnotes/terms-and-conditions') }}">Terms &amp; Conditions</a><br />
<a href="{{ url('footnotes/disclaimer') }}">Disclaimer</a>
</p>
</li>
</ul>									
{% endblock %}