{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Download Formulir</h2>
<p>Anda akan menemukan formulir yang tersedia untuk di-download dengan mengklik langsung pada link di bawah ini.</p>

<h3 class="page_margin_top">Forms</h3>
<p>
<a href="http://www.stemcord.com/forms/SC_CreditCardAuthorisationForm.pdf" target="_blank" title="Form Otorisasi Pembayaran Kartu Kredit">Form Otorisasi Pembayaran Kartu Kredit</a> (96KB)<br />
<a href="http://www.stemcord.com/forms/StemCord_BillingInstructionAuthorizationLetter.pdf" target="_blank" title="Surat Kuasa Penagihan">Surat Kuasa Penagihan</a> (50KB)
</p>

<h3 class="page_margin_top">Penyerahan Formulir</h3>

<p>Formulir dapat diserahkan  melalui fax ke {{ phoneFullTag }} atau melalui pendaftaran online dengan mengklik <a href="{{ url('layanan-pelanggan/penyerahan-dokumen') }}" title="Penyerahan Dokumen">di sini</a>.<br />
Anda dapat mengirimkan: Form Re-Deklarasi  Sejarah Kesehatan Medis, Akte Kelahiran bayi, Surat Adverse Event atau dokumen lainnya.</p>					{% endblock %}