{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Teman Mereferensikan Teman</h2>
{% if isSubmit %}
						<ul>

	<li id="gallery-details-1" class="gallery_item_details clearfix"><div class="columns no_width"><div class="column_left"><div class="details_box">


<br />
<p>Kepada Yth <strong>{{ name }}</strong>, Info Teman Anda sudah diterima.</p>
<p>Terima kasih telah mengirimkan informasi ini. Staff kami akan mengontak Anda dengan segera. Apabila ada yang ingin ditanyakan lebih lanjut silahkan hubungi {{ phoneFullTag }} atau HP {{ mobileCall }}.</p>
<br />
<p>Terima kasih</p>
<br />
<p>Salam,<br />
StemCord</p>
		
	<ul class="controls page_margin_top"><li><a href="{{ url('layanan-pelanggan/friend-refer-friend') }}">Kembali ke halaman sebelumnya</a></li></ul></div></div></div></li>
	
</ul>
{% else %}
<div class="gallery-hide">

<p>Berbagi  informasi tentang Penyimpanan Darah Tali Pusat  dengan teman-teman Anda.</p>

<p>Cukup mengisi data Anda dan  teman Anda di bawah ini dan konsultan kami yang ramah akan menghubungi mereka untuk berbagi  informasi  tentang  manfaat yang banyak  dari penyimpanan darah tali pusat.</p>
<br />&nbsp;
<div class="wpcf7" id="wpcf7-f777-p775-o1">
<div class="screen-reader-response"></div>
<form action="{{ url('layanan-pelanggan/friend-refer-friend') }}" method="post" class="wpcf7-form wpcf7-acceptance-as-validation" novalidate="novalidate">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="777" />
<input type="hidden" name="_wpcf7_version" value="3.8.1" />
<input type="hidden" name="_wpcf7_locale" value="" />
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f777-p775-o1" />
<input type="hidden" name="_wpnonce" value="754b19c3e1" />
<input type="text" name="input-pot" value= "" />
</div>
<div class="contact_form">

<h3 class="box_header">Rincian  Pemberi Informasi (  Referrer )</h3>

<div class="clearfix">
<br>
<div class="note">Bagian  yang ditandai dengan * wajib diisi</div>
<fieldset class="left">

    <label>SCP Nomor</label><div class="block">
        <span class="wpcf7-form-control-wrap referal-mothers-scp"><input type="text" name="referal-mothers-scp" value="" size="8" maxlength="8" class="wpcf7-form-control wpcf7-text text_input" aria-invalid="false" /></span>
    </div>

    <label>Nama Ibu (sesuai kontrak/agreement) *</label><div class="block">
        <span class="wpcf7-form-control-wrap referal-mothers-name"><input type="text" name="referal-mothers-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" id="referal-mothers-name" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Nomor Identifikasi Ibu *</label><div class="block">
        <span class="wpcf7-form-control-wrap referal-mothers-IC"><input type="text" name="referal-mothers-ic" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>

<fieldset class="right">

    <label>Nomor Handphone Ibu *</label><div class="block">
        <span class="wpcf7-form-control-wrap referal-mothers-contact"><input type="text" name="referal-mothers-contact" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Alamat Email *</label><div class="block">
        <span class="wpcf7-form-control-wrap referal-mothers-email"><input type="email" name="referal-mothers-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>
</div>

<h3 class="box_header page_margin_top">Rincian Teman-teman</h3>

<div class="clearfix">

<fieldset class="left page_margin_top">

	<h4>Teman 1</h4>

	<label>Nama Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend1-name"><input type="text" name="referal-friend1-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
	</div>
	<label>Alamat Email Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend1-email"><input type="email" name="referal-friend1-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email text_input" aria-required="true" aria-invalid="false" /></span>
	</div>
	<label>Telepon Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend1-contact"><input type="text" name="referal-friend1-contact" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
	</div>
	<label>Rumah Sakit Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend1-hospital"><input type="text" name="referal-friend1-hospital" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
	</div>
	
</fieldset>

<fieldset class="right page_margin_top">

	<h4>Teman 2</h4>

	<label>Nama Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend2-name"><input type="text" name="referal-friend2-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-invalid="false" /></span>
	</div>
	<label>Alamat Email Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend2-email"><input type="email" name="referal-friend2-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email text_input" aria-invalid="false" /></span>
	</div>
	<label>Telepon Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend2-contact"><input type="text" name="referal-friend2-contact" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-invalid="false" /></span>
	</div>
	<label>Rumah Sakit Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend2-hospital"><input type="text" name="referal-friend2-hospital" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-invalid="false" /></span>
	</div>

</fieldset>

</div>

<div class="clearfix">

<fieldset class="left page_margin_top">

	<h4>Teman 3</h4>
	
	<label>Nama Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend3-name"><input type="text" name="referal-friend3-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-invalid="false" /></span>
	</div>
	<label>Alamat Email Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend3-email"><input type="email" name="referal-friend3-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email text_input" aria-invalid="false" /></span>
	</div>
	<label>Telepon Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend3-contact"><input type="text" name="referal-friend-3contact" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-invalid="false" /></span>
	</div>
	<label>Rumah Sakit Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend3-hospital"><input type="text" name="referal-friend3-hospital" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-invalid="false" /></span>
	</div>

</fieldset>

<fieldset class="right page_margin_top">

	<h4>Friend 4</h4>
	
	<label>Nama Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend4-name"><input type="text" name="referal-friend4-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-invalid="false" /></span>
	</div>
	<label>Alamat Email Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend4-email"><input type="email" name="referal-friend4-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email text_input" aria-invalid="false" /></span>
	</div>
	<label>Telepon Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend4-contact"><input type="text" name="referal-friend4-contact" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-invalid="false" /></span>
	</div>
	<label>Rumah Sakit Teman *</label><div class="block">
		<span class="wpcf7-form-control-wrap referal-friend4-hospital"><input type="text" name="referal-friend4-hospital" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-invalid="false" /></span>
	</div>

</fieldset>

</div>

<p class="submit-consent">Dengan mengirimkan formulir ini, saya menerima dan menyetujui untuk disertakan dalam StemCord milis, dan dihubungi oleh StemCord dan mitra untuk komunikasi lebih lanjut.<br>
Saya memilih untuk dihubungi dengan cara:
<span class="wpcf7-form-control-wrap contact-by"><span class="wpcf7-form-control wpcf7-checkbox wpcf7-validates-as-required"><span class="wpcf7-list-item first"><input type="checkbox" name="contact-by[]" value="Telepon" />&nbsp;<span class="wpcf7-list-item-label">Telepon</span></span><span class="wpcf7-list-item last"><input type="checkbox" name="contact-by[]" value="SMS" />&nbsp;<span class="wpcf7-list-item-label">SMS</span></span></span></span></p>

<p><input type="submit" value="Submit" class="wpcf7-form-control wpcf7-submit more blue" /></p>

</div><div class="wpcf7-response-output wpcf7-display-none"></div></form></div>

</div>
{% endif %}
{% endblock %}