{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Penyerahan Dokumen</h2>
<ul class="gallery_item_details_list clearfix">

	<li id="gallery-details-1" class="gallery_item_details clearfix"><div class="columns no_width"><div class="column_left"><div class="details_box">


<br />
<p>Your form was submitted successfully.</p>
<p>We will be sending you a confirmation email shortly. Please do not hesitate to contact us at {{ phoneFullTag }} should you require further assistance. </p>
<br />
<p>Thank you and have a pleasant day ahead.</p>
<br />
<p>Warmest Regards,<br />
StemCord Singapore</p>
		
	<ul class="controls page_margin_top"><li><a href="#gallery-details-close">Return to Previous Page</a></li></ul></div></div></div></li>
	
</ul>

<div class="gallery-hide">

<p>You may submit your documents here to complete the formalities required for the issuance of the StemCord Certificate.
<br /><br />
<strong>Documents that can be submitted include:</strong></p>
<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">Birth Certificate</li>
	<li class="icon_small_arrow right_lightblue">Re-Declaration of Medical Health History Form</li>
	<li class="icon_small_arrow right_lightblue">Adverse Event Letter</li>
	<li class="icon_small_arrow right_lightblue">Credit Card Payment Authorisation Form</li>
	<li class="icon_small_arrow right_lightblue">Billing Instruction Letter</li>
	<li class="icon_small_arrow right_lightblue">Deed Poll</li>
</ul>

<p>If you wish to submit your CDA Giro Application Form, kindly mail the completed form to: StemCord Pte Ltd, 89 Science Park Drive 1, The Rutherford #04-27/28, Singapore 118261</p>

<div class="wpcf7" id="wpcf7-f440-p441-o1">
<div class="screen-reader-response"></div>
<form action="/client-centre/submission-of-documents/#wpcf7-f440-p441-o1" method="post" class="wpcf7-form wpcf7-acceptance-as-validation" enctype="multipart/form-data" novalidate="novalidate">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="440" />
<input type="hidden" name="_wpcf7_version" value="3.8.1" />
<input type="hidden" name="_wpcf7_locale" value="" />
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f440-p441-o1" />
<input type="hidden" name="_wpnonce" value="43a9aa2700" />
</div>
<div class="contact_form">

<div class="clearfix">
<div class="note">fields marked with * are mandatory</div>
<fieldset class="left">

    <label>SCP Number</label><div class="block">
        <span class="wpcf7-form-control-wrap submit-mothers-scp"><input type="text" name="submit-mothers-scp" value="" size="8" maxlength="8" class="wpcf7-form-control wpcf7-text text_input" aria-invalid="false" /></span>
    </div>

    <label>Mother's Name (as per contract) *</label><div class="block">
        <span class="wpcf7-form-control-wrap submit-mothers-name"><input type="text" name="submit-mothers-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" id="submit-mothers-name" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Mother's Identification Number. *</label><div class="block">
        <span class="wpcf7-form-control-wrap submit-mothers-ID"><input type="text" name="submit-mothers-ID" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>

<fieldset class="right">

    <label>Mother's Contact No. (Mobile) *</label><div class="block">
        <span class="wpcf7-form-control-wrap submit-mothers-contact"><input type="text" name="submit-mothers-contact" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Mother's Email Address *</label><div class="block">
        <span class="wpcf7-form-control-wrap submit-mothers-email"><input type="email" name="submit-mothers-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>
</div>

<fieldset class="page_margin_top" style="clear:both;">
<p><span class="darkblue">For document upload, only file types JPEG and PDF of file size smaller than 2MB is allowed.</span></p>

    <label>Document *</label><div class="block">
        <span class="wpcf7-form-control-wrap submit-document"><input type="file" name="submit-document" value="1" size="40" class="wpcf7-form-control wpcf7-file wpcf7-validates-as-required" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>

<label>Remarks</label><div class="block">
	<span class="wpcf7-form-control-wrap submit-remarks"><textarea name="submit-remarks" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea text_input" aria-invalid="false"></textarea></span>
</div>

<p class="submit-consent">By submitting this form, I accept and agree to be included in StemCord’s mailing list, and to be contacted by StemCord and partners for future communications.<br>
I prefer to be contacted by:
<span class="wpcf7-form-control-wrap contact-by"><span class="wpcf7-form-control wpcf7-checkbox wpcf7-validates-as-required"><span class="wpcf7-list-item first"><input type="checkbox" name="contact-by[]" value="Telephone" />&nbsp;<span class="wpcf7-list-item-label">Telephone</span></span><span class="wpcf7-list-item last"><input type="checkbox" name="contact-by[]" value="SMS" />&nbsp;<span class="wpcf7-list-item-label">SMS</span></span></span></span></p>

<p><input type="submit" value="Submit" class="wpcf7-form-control wpcf7-submit more blue" /></p>

</div><div class="wpcf7-response-output wpcf7-display-none"></div></form></div>

</div>
{% endblock %}