{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Penyerahan Dokumen</h2>
{% if isSubmit %}
{% if error == '' %}
<ul>

	<li id="gallery-details-1" class="gallery_item_details clearfix"><div class="columns no_width"><div class="column_left"><div class="details_box">


<br />
<p>Kepada Yth <strong>{{ name }}</strong>, Dokumen Anda sudah kami terima.</p>
<p>Terima kasih telah mengirimkan dokumen ini. Staff kami akan mengontak Anda dengan segera. Apabila ada yang ingin ditanyakan lebih lanjut silahkan hubungi {{ phoneFullTag }} atau HP {{ mobileCall }}.</p>
<br />
<p>Terima kasih</p>
<br />
<p>Salam,<br />
StemCord</p>
		
	<ul class="controls page_margin_top"><li><a href="{{ url('layanan-pelanggan/penyerahan-dokumen')}}">Return to Previous Page</a></li></ul></div></div></div></li>
	
</ul>
{% else %}
Error: {{ error }}
<ul class="controls page_margin_top"><li><a href="{{ url('layanan-pelanggan/penyerahan-dokumen')}}">Return to Previous Page</a></li></ul>
{% endif %}
{% else %}
<div class="gallery-hide">

<p>Anda dapat mengirimkan dokumen Anda di sini untuk persyaratan dokumentasi yang diperlukan untuk penerbitan Sertifikat StemCord.
<br /><br />
<strong>Dokumen yang diperlukan antara lain:</strong></p>
<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">Akte Kelahiran</li>
	<li class="icon_small_arrow right_lightblue">Form Re-Deklarasi Sejarah Kesehatan Medis</li>
	<li class="icon_small_arrow right_lightblue">Surat Adverse Event</li>
	<li class="icon_small_arrow right_lightblue">Formulir Otorisasi Pembayaran Kartu Kredit</li>
	<li class="icon_small_arrow right_lightblue">Surat Penagihan</li>
	<li class="icon_small_arrow right_lightblue">Dokumen hukum untuk ganti nama</li>
</ul>

<div class="wpcf7" id="wpcf7-f440-p441-o1">
<div class="screen-reader-response"></div>
<form action="{{ url('layanan-pelanggan/penyerahan-dokumen') }}" method="post" class="wpcf7-form wpcf7-acceptance-as-validation" enctype="multipart/form-data" novalidate="novalidate">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="440" />
<input type="hidden" name="_wpcf7_version" value="3.8.1" />
<input type="hidden" name="_wpcf7_locale" value="" />
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f440-p441-o1" />
<input type="hidden" name="_wpnonce" value="43a9aa2700" />
<input type="text" name="input-pot" value= "" />
</div>
<div class="contact_form">

<div class="clearfix">
<div class="note">Bagian  yang ditandai dengan * wajib diisi</div>
<fieldset class="left">

    <label>Nomor SCP</label><div class="block">
        <span class="wpcf7-form-control-wrap submit-mothers-scp"><input type="text" name="submit-mothers-scp" value="" size="8" maxlength="8" class="wpcf7-form-control wpcf7-text text_input" aria-invalid="false" /></span>
    </div>

    <label>Nama Ibu (sesuai kontrak/agreement) *</label><div class="block">
        <span class="wpcf7-form-control-wrap submit-mothers-name"><input type="text" name="submit-mothers-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" id="submit-mothers-name" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Nomor KTP *</label><div class="block">
        <span class="wpcf7-form-control-wrap submit-mothers-ID"><input type="text" name="submit-mothers-ID" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>

<fieldset class="right">

    <label>Nomor Telepon ibu (Mobile) *</label><div class="block">
        <span class="wpcf7-form-control-wrap submit-mothers-contact"><input type="text" name="submit-mothers-contact" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Alamat Email Ibu *</label><div class="block">
        <span class="wpcf7-form-control-wrap submit-mothers-email"><input type="email" name="submit-mothers-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>
</div>

<fieldset class="page_margin_top" style="clear:both;">
<p><span class="darkblue">Untuk meng-upload dokumen, hanya mengajukan jenis JPEG dan PDF ukuran file yang lebih kecil dari 2MB diperbolehkan.</span></p>

    <label>Dokumen *</label><div class="block">
        <span class="wpcf7-form-control-wrap submit-document"><input type="file" name="submit-document" value="1" size="40" class="wpcf7-form-control wpcf7-file wpcf7-validates-as-required" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>

<label>Keterangan</label><div class="block">
	<span class="wpcf7-form-control-wrap submit-remarks"><textarea name="submit-remarks" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea text_input" aria-invalid="false"></textarea></span>
</div>

<p class="submit-consent">Dengan mengirimkan formulir ini, saya menerima dan menyetujui untuk disertakan dalam StemCord milis, dan dihubungi oleh StemCord dan mitra untuk komunikasi  lebih lanjut.<br>
Saya memilih untuk dihubungi dengan cara:
<span class="wpcf7-form-control-wrap contact-by"><span class="wpcf7-form-control wpcf7-checkbox wpcf7-validates-as-required"><span class="wpcf7-list-item first"><input type="checkbox" name="contact-by[]" value="Telepon" />&nbsp;<span class="wpcf7-list-item-label">Telepon</span></span><span class="wpcf7-list-item last"><input type="checkbox" name="contact-by[]" value="SMS" />&nbsp;<span class="wpcf7-list-item-label">SMS</span></span></span></span></p>

<p><input type="submit" value="Submit" class="wpcf7-form-control wpcf7-submit more blue" /></p>

</div><div class="wpcf7-response-output wpcf7-display-none"></div></form></div>

</div>
{% endif %}
{% endblock %}