{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Pilihan Pembayaran</h2>
<p>Anda dapat menentukan pilihan cara pembayaran yang nyaman  untuk layanan penyimpanan darah tali pusat StemCord.</p>

<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">
<span class="darkblue">Transfer Rupiah /SGD via BCA</span>
	</li>
	<li class="icon_small_arrow right_lightblue">
<span class="darkblue">Cicilan 3 atau 6 bulan 0% dengan kartu kredit BCA</span>
	</li>
	<li class="icon_small_arrow right_lightblue">
<span class="darkblue">Kartu kredit</span><br />
Cukup mengisi <a href="{{ url('layanan-pelanggan/download-form') }}">Formulir Otorisasi Kartu Kredit Anda</a> dan <a href="{{ url('layanan-pelanggan/penyerahan-dokumen') }}">mengirimkannya secara online</a>. Atau, Anda bisa fax formulir ke {{ phoneFullTag }} atau email ke {{ billingEmailFullTag }} untuk pembayaran
	</li>
</ul>									
{% endblock %}