{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Penyakit Diobati Saat Ini</h2>
<p>Saat ini, Transplantasi sel punca darah tali pusat merupakan alternatif terapi yang telah  terbukti dapat mengobati lebih dari 80 penyakit *. Ada dua jenis terapi.</p> 
<p>Untuk  terapi autologus, diperlukan sel punca milik  pasien sendiri.</p> 
<p>Untuk terapi Alogenik, pasien menerima sel punca dari donor lain yang cocok. Kemungkinan kecocokan  jauh lebih tinggi di antara saudara kandung dan anggota keluarga langsung.</p>
<p>Penyakit berikut * dapat diobati dengan sel punca  darah tali pusat, melalui:</p>

<ul class="columns page_margin_top clearfix">
	<li class="column_left">
		<h3 class="page_margin_top">Leukemia Akut </h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Acute Biphenotypic Leukemia</li>
			<li class="icon_small_arrow right_lightblue">Acute Lymphocytic Leukemia (ALL)</li>
			<li class="icon_small_arrow right_lightblue">Acute Myelogenous Leukemia (AML)</li>
			<li class="icon_small_arrow right_lightblue">Acute Undifferentiated Leukemia</li>
		</ul>
	</li>

	<li class="column_right">
	<h3 class="page_margin_top">Leukemia Kronis</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Chronic Lymphocytic Leukemia (CLL)</li>
			<li class="icon_small_arrow right_lightblue">Chronic Myelogenous Leukemia (CML)</li>
			<li class="icon_small_arrow right_lightblue">Juvenile Chronic Myelogenous Leukemia (JCML)</li>
			<li class="icon_small_arrow right_lightblue">Juvenile Myelomonocytic Leukemia (JMML)</li>
		</ul>
	</li>
</ul>

<ul class="columns page_margin_top clearfix">
	<li class="column_left">
		<h3 class="page_margin_top">Myelodysplastic Syndromes</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Amyloidosis</li>
			<li class="icon_small_arrow right_lightblue">Chronic Myelomonocytic Leukemia (CMML)</li>
			<li class="icon_small_arrow right_lightblue">Refractory Anemia (RA)</li>
			<li class="icon_small_arrow right_lightblue">Refractory Anemia with Excess Blasts (RAEB)</li>
			<li class="icon_small_arrow right_lightblue">Refractory Anemia with Excess Blasts in Transformation (RAEB-T)</li>
			<li class="icon_small_arrow right_lightblue">Refractory Anemia with Ringed Sideroblasts (RARS)</li>
		</ul>
	</li>

	<li class="column_right">
		<h3 class="page_margin_top">Stem Cell Disorders</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Aplastic Anemia (Severe)</li>
			<li class="icon_small_arrow right_lightblue">Congenital Cytopenia</li>
			<li class="icon_small_arrow right_lightblue">Dyskeratosis Congenita</li>
			<li class="icon_small_arrow right_lightblue">Fanconi Anemia</li>
			<li class="icon_small_arrow right_lightblue">Paroxysmal Nocturnal Hemoglobinuria (PNH)</li>
		</ul>
	</li>
</ul>

<ul class="columns page_margin_top clearfix">
	<li class="column_left">
		<h3 class="page_margin_top">Myeloproliferative Disorders</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Acute Myelofibrosis</li>
			<li class="icon_small_arrow right_lightblue">Agnogenic Myeloid Metaplasia (Myelofibrosis)</li>
			<li class="icon_small_arrow right_lightblue">Essential Thrombocythemia</li>
			<li class="icon_small_arrow right_lightblue">Polycythemia Vera</li>
		</ul>
	</li>

	<li class="column_right">
		<h3 class="page_margin_top">Lymphoproliferative Disorders</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Hodgkin&#8217;s Disease</li>
			<li class="icon_small_arrow right_lightblue">Non-Hodgkin&#8217;s Lymphoma</li>
			<li class="icon_small_arrow right_lightblue">Prolymphocytic Leukemia</li>
		</ul>
	</li>
</ul>

<ul class="columns page_margin_top clearfix">
	<li class="column_left">
		<h3 class="page_margin_top">Congenital (Inherited) Immune System Disorders</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Absence of T &#038; B Cells SCID</li>
			<li class="icon_small_arrow right_lightblue">Absence of T Cells, Normal B Cell SCID</li>
			<li class="icon_small_arrow right_lightblue">Ataxia-Telangiectasia</li>
			<li class="icon_small_arrow right_lightblue">Bare Lymphocyte Syndrome</li>
			<li class="icon_small_arrow right_lightblue">Common Variable Immunodeficiency</li>
			<li class="icon_small_arrow right_lightblue">DiGeorge Syndrome</li>
			<li class="icon_small_arrow right_lightblue">Kostmann Syndrome</li>
			<li class="icon_small_arrow right_lightblue">Leukocyte Adhesion Deficiency</li>
			<li class="icon_small_arrow right_lightblue">Omenn&#8217;s Syndrome</li>
			<li class="icon_small_arrow right_lightblue">Severe Combined Immunodeficiency (SCID)</li>
			<li class="icon_small_arrow right_lightblue">SCID with Adenosine Deaminase Deficiency</li>
			<li class="icon_small_arrow right_lightblue">Wiskott-Aldrich Syndrome</li>
			<li class="icon_small_arrow right_lightblue">X-Linked Lymphoproliferative Disorder</li>
		</ul>
	</li>

	<li class="column_right">
		<h3 class="page_margin_top">Liposomal Storage Diseases</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Adrenoleukodystrophy</li>
			<li class="icon_small_arrow right_lightblue">Gaucher&#8217;s Disease</li>
			<li class="icon_small_arrow right_lightblue">Hunter&#8217;s Syndrome (MPS-II)</li>
			<li class="icon_small_arrow right_lightblue">Hurler&#8217;s Syndrome (MPS-IH)</li>
			<li class="icon_small_arrow right_lightblue">Krabbe Disease</li>
			<li class="icon_small_arrow right_lightblue">Maroteaux-Lamy Syndrome (MPS-VI)</li>
			<li class="icon_small_arrow right_lightblue">Metachromatic Leukodystrophy</li>
			<li class="icon_small_arrow right_lightblue">Morquio Syndrome (MPS-IV)</li>
			<li class="icon_small_arrow right_lightblue">Mucolipidosis II (I-cell Disease)</li>
			<li class="icon_small_arrow right_lightblue">Mucopolysaccharidoses (MPS)</li>
			<li class="icon_small_arrow right_lightblue">Niemann-Pick Disease</li>
			<li class="icon_small_arrow right_lightblue">Sanfilippo Syndrome (MPS-III)</li>
			<li class="icon_small_arrow right_lightblue">Scheie Syndrome (MPS-IS)</li>
			<li class="icon_small_arrow right_lightblue">Sly Syndrome, Beta-Glucuronidase Deficiency (MPS-VII)</li>
			<li class="icon_small_arrow right_lightblue">Wolman Disease</li>
		</ul>
	</li>
</ul>

<ul class="columns page_margin_top clearfix">
	<li class="column_left">
		<h3 class="page_margin_top">Histiocytic Disorders</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Familial Erythrophagocytic Lymphohistiocytosis</li>
			<li class="icon_small_arrow right_lightblue">Hemophagocytosis</li>
			<li class="icon_small_arrow right_lightblue">Histiocytosis-X</li>
			<li class="icon_small_arrow right_lightblue">Langerhans&#8217; Cell Histiocytosis</li>
		</ul>
	</li>

	<li class="column_right">
		<h3 class="page_margin_top">Inherited Erythrocyte Abnormalities</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Beta Thalassemia Major</li>
			<li class="icon_small_arrow right_lightblue">Blackfan-Diamond Anemia</li>
			<li class="icon_small_arrow right_lightblue">Pure Red Cell Aplasia</li>
			<li class="icon_small_arrow right_lightblue">Sickle Cell Disease</li>
		</ul>
	</li>
</ul>

<ul class="columns page_margin_top clearfix">
	<li class="column_left">
		<h3 class="page_margin_top">Phagocyte Disorders</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Chediak-Higashi Syndrome</li>
			<li class="icon_small_arrow right_lightblue">Chronic Granulomatous Disease</li>
			<li class="icon_small_arrow right_lightblue">Neutrophil Actin Deficiency</li>
			<li class="icon_small_arrow right_lightblue">Reticular Dysgenesis</li>
		</ul>
	</li>

	<li class="column_right">
		<h3 class="page_margin_top">Other Inherited Disorders</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Cartilage-Hair Hypoplasia</li>
			<li class="icon_small_arrow right_lightblue">Ceroid Lipofuscinosis</li>
			<li class="icon_small_arrow right_lightblue">Congenital Erythropoietic Porphyria</li>
			<li class="icon_small_arrow right_lightblue">Glanzmann Thrombasthenia</li>
			<li class="icon_small_arrow right_lightblue">Lesch-Nyhan Syndrome</li>
			<li class="icon_small_arrow right_lightblue">Osteopetrosis</li>
			<li class="icon_small_arrow right_lightblue">Tay Sachs Disease</li>
		</ul>
	</li>
</ul>

<ul class="columns page_margin_top clearfix">
	<li class="column_left">
		<h3 class="page_margin_top">Inherited Platelet Abnormalities</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Amegakaryocytosis / Congenital Thrombocytopenia</li>
		</ul>
	</li>

	<li class="column_right">
		<h3 class="page_margin_top">Plasma Cell Disorders</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Multiple Myeloma</li>
			<li class="icon_small_arrow right_lightblue">Plasma Cell Leukemia</li>
			<li class="icon_small_arrow right_lightblue">Waldenstrom&#8217;s Macroglobulinemia</li>
		</ul>
	</li>
</ul>

<ul class="columns page_margin_top clearfix">
	<li class="column_left">
		<h3 class="page_margin_top">Other Malignancies</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Brain Tumors</li>
			<li class="icon_small_arrow right_lightblue">Breast Cancer</li>
			<li class="icon_small_arrow right_lightblue">Ewing Sarcoma</li>
			<li class="icon_small_arrow right_lightblue">Neuroblastoma</li>
			<li class="icon_small_arrow right_lightblue">Ovarian Cancer</li>
			<li class="icon_small_arrow right_lightblue">Renal Cell Carcinoma</li>
			<li class="icon_small_arrow right_lightblue">Small-Cell Lung Cancer</li>
			<li class="icon_small_arrow right_lightblue">Testicular Cancer</li>
		</ul>
	</li>

	<li class="column_right">
		<h3 class="page_margin_top">Autoimmune Diseases</h3>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">Evan Syndrome</li>
			<li class="icon_small_arrow right_lightblue">Multiple Sclerosis (Experimental)</li>
			<li class="icon_small_arrow right_lightblue">Rheumatoid Arthritis (Experimental)</li>
			<li class="icon_small_arrow right_lightblue">Systemic Lupus Erythematosus (Experimental)</li>
		</ul>
	</li>
</ul>

<div class="disclaimer"><b>Catatan:</b> Bank darah tali pusat tidak menjamin bahwa sel akan menyediakan obat dan dapat diaplikasikan untuk setiap situasi.  Dokter akan menentukan pengobatan yang paling utama. Tidak ada jaminan darah tali pusat akan cocok untuk anggota keluarga atau menyediakan pengobatan. Stem cell dari darah tali pusat untuk pemakaian sendiri tidak menjamin pengobatan yang cocok untuk semua penyakit genetik yang diwariskan.  Dengan setiap transplantasi terapi, keberhasilan terapi bergantung pada beberapa faktor di luar dari sel punca pasien sendiri termasuk kondisi pasien, jenis penyakit, hubungan penerima donor- donor dan kecocokannya, dan faktor-faktor lainnya. Penggunaan sel punca dari darah tali pusat untuk metode pengobatan masih merupakan eksperimental. Silahkan bekonsultasi ke dokter Anda.</div>									
{% endblock %}