{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Keuntungan Bank Darah Tali Pusat</h2>
						<p><img width="630" height="419" src="http://www.stemcord.com/wp-content/uploads/2013/03/banner-benefits-of-cord-blood-banking.jpg" class="attachment-post-thumbnail wp-post-image" alt="Benefits of cord blood banking" /></p>
						<p>Transplantasi darah tali pusat adalah jenis transplantasi sel punca dimana sumber sel punca berasal dari tali pusar. Ribuan nyawa di seluruh dunia telah diselamatkan dengan transplantasi darah tali pusat milik orang lain. Terapi ini dapat mengobati lebih dari <a href="{{ url('bank-darah-tali-pusat/daftar-penyakit-yang-dapat-ditangani') }}">70 penyakit*</a> termasuk gangguan sumsum tulang, kanker darah, kanker padat, beberapa jenis penyakit penyimpanan glikogen dan immunodeficiencies.</p>

<p>Sel Punca juga telah digunakan untuk mengobati kegagalan organ dalam bentuk <a href="{{ url('bank-darah-tali-pusat/masa-depan-darah-tali-pusat')}}" target="_blank">Terapi Regerenatif</a>. Ini adalah metode pengobatan yang sedang naik daun, dimana sel punca mempunyai potensi untuk membantu regenerasi organ yang telah rusak atau memperbaiki jaringan. Beberapa contoh penyakit yang dapat menggunakan sel punca untuk regenerasi organ mencakup cerebral palsy, cedera otak, juvenile diabetes, diabetes, penyakit jantung, cedera tulang belakang, dan stroke.</p>

<span class="darkblue heavy"><p>Raih keuntungan dari kesempatan sekali seumur hidup ini untuk menyelamatkan darah tali pusat bayi Anda alih alih membuangnya.</p></span>

<p>Your baby’s genetically unique stem cells offers many advantages if stem cells are ever needed for treatment by you, your child, siblings, or other family members as it is:</p>

<div class="dropcap"><div class="dropcap_label"><h3>1</h3></div>Tersedia dengan cepat untuk pengobatan dan pengobatan  sedini mungkin dapat meminimalisir perkembangan penyakit.</div><br />
<div class="dropcap"><div class="dropcap_label"><h3>2</h3></div>Lebih baik daripada menggunakan darah tali pusat dari donor yang tidak memiliki hubungan, karena lebih sedikit komplikasi dan hasil medis yang lebih baik.</div><br />
<div class="dropcap"><div class="dropcap_label"><h3>3</h3></div>Satu Satunya jenis darah tali pusat yang digunakan untuk eksperimen terapi regenerasi.</div>

<div class="disclaimer">
<b>Catatan:</b> Bank darah tali pusat tidak menjamin bahwa sel akan menyediakan obat dan dapat diaplikasikan untuk setiap situasi.  Dokter akan menentukan pengobatan yang paling utama. Tidak ada jaminan darah tali pusat akan cocok untuk anggota keluarga atau menyediakan pengobatan. Stem cell dari darah tali pusat untuk pemakaian sendiri tidak menjamin pengobatan yang cocok untuk semua penyakit genetik yang diwariskan.  Dengan setiap transplantasi terapi, keberhasilan terapi bergantung pada beberapa faktor di luar dari sel punca pasien sendiri termasuk kondisi pasien, jenis penyakit, hubungan penerima donor- donor dan kecocokannya, dan faktor-faktor lainnya. Penggunaan sel punca dari darah tali pusat untuk metode pengobatan masih merupakan eksperimental. Silahkan bekonsultasi ke dokter Anda.
</div>									
{% endblock %}