{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Masa Depan Darah Tali Pusat</h2>
						<p><img width="630" height="330" src="http://www.stemcord.com/wp-content/uploads/2013/04/future_stemcell.jpg" class="attachment-post-thumbnail wp-post-image" alt="future_stemcell" /></p>
						<p>Saat ini , darah tali pusat  sedang diteliti untuk terapi regenerasi di mana sel-sel induk dapat membantu mendorong penyembuhan atau regenerasi sel untuk memperbaiki jaringan.  Dengan kemampuannya untuk berubah mejadi jaringan tubuh yang berbeda pada terapi regenerasi, sel punca memiliki kemampuan yang amat menjanjikan pada pengobatan penyakit yang mengancam kehidupan. Penelitian masih terus dilakukan dan sel punca memberi harapan yang besar untuk dapat mengobati penyakit – penyakit seperti di bawah ini:</p>

<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">Penyakit Alzheimer&#8217;s</li>
	<li class="icon_small_arrow right_lightblue">Cidera Otak</li>
	<li class="icon_small_arrow right_lightblue">Cerebral Palsy</li>
	<li class="icon_small_arrow right_lightblue">Regenerasi Kornea</li>
	<li class="icon_small_arrow right_lightblue">Diabetes &#038; Juvenile Diabetes</li>
	<li class="icon_small_arrow right_lightblue">Penyakit Jantung</li>
	<li class="icon_small_arrow right_lightblue">Penyakit Liver</li>
	<li class="icon_small_arrow right_lightblue">Muscular Dystrophy</li>
	<li class="icon_small_arrow right_lightblue">Penyakit Parkinson&#8217;s</li>
	<li class="icon_small_arrow right_lightblue">Cidera Tulang</li>
	<li class="icon_small_arrow right_lightblue">Stroke</li>
</ul>

<div class="disclaimer"><b>Catatan:</b> Penggunaan baru untuk stem sel darah tali pusat sedang dalam penelitian. Bank darah tali pusat tidak menjamin bahwa sel akan menyediakan obat dan dapat diaplikasikan untuk setiap situasi. Dokter akan menentukan pengobatan yang paling utama. Penggunaan sel punca dari darah tali pusat untuk metode pengobatan masih merupakan eksperimental. Silahkan bekonsultasi ke dokter Anda.</div>

<div class="disclaimer">
<b>*Sumber:</b>
<ol style="line-height:150%">
<li>Robbins S. New development in umbilical cord blood technologies. ASCR Network. <a href="http://www.ascrnetwork.com/component/content/article/53- march-2009/373-new-developments- in-umbilical-cord-bloodtechnologies.html">http://www.ascrnetwork.com/component/content/article/53- march-2009/373-new-developments- in-umbilical-cord-bloodtechnologies.html</a>. Accessed November 21, 2011.</li>
<li>National Institutes of Health, ClinicalTrials.gov. A randomized study of autologous umbilical cord blood reinfusion in children with cerebral palsy. <a href="http://clinicaltrials.gov/ct2/show/NCT1147653">http://clinicaltrials.gov/ct2/show/NCT1147653</a>. Identifier NCT01147653. Accessed November 21, 2011.</li>
<li>U.S National Institutes of Health, ClinicalTrials.gov. Umbilical cord blood infusion to treat type 1 diabetes. Identifier: NCT00305344. <a href="http://clinicaltrials.gov/ct2/show/NCT00305344">http://clinicaltrials.gov/ct2/show/NCT00305344</a>. Accessed September 11, 2012.</li>
</ol>
<br/>
Jika Anda membutuhkan informasi lebih lanjut silahkan hubungi kami di {{ phoneFullTag }} atau email ke {{ emailFullTag }}
</div>								
{% endblock %}