{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Pengambilan Darah Tali Pusat</h2>
						<p><img width="630" height="330" src="http://www.stemcord.com/wp-content/uploads/2013/04/collecting_cordblood.jpg" class="attachment-post-thumbnail wp-post-image" alt="collecting_cordblood" /></p>
						<p>Pengambilan darah tali pusat adalah prosedur yang tidak rumit, membutuhkan waktu sekitar 5 menit dan dapat dilakukan baik dalam persalinan normal , sectio maupun untuk kelahiran kembar. Setelah bayi Anda lahir,  dokter akan memotong dan menjepit  tali pusat , darah  akan diambil dari tali pusat sebelum tali pusat dibuang. Stemcord menggunakan metode Collection Bag untuk mengambil  darah tali pusat yang dikumpulkan ke dalam collection bag.</p>

<span class="darkblue">Untuk membantu Anda membuat keputusan yang tepat,  kami  berinisiatif mengumpulkan beberapa pertanyaan yang sering diajukan kepada kami.</span>

<ul class="accordion page_margin_top">
	<li><div id="accordion-benefits4-1"><h3>Apakah ada resiko bagi Ibu maupun bayi selama pengambilan?</h3></div><div class="clearfix">
		<p>Tidak ada resiko baik untuk Ibu maupun bayi dalam proses pengambilan, karena darah tali pusat ini diambil setelah bayi dilahirkan. Darah yang diambil sendiri tidak berhubungan langsung dengan darah Ibu, sehingga tidak perlu khawatir Ibu akan kekurangan darah akibat pengambilan ini.</p>
	</div></li>
	
	<li><div id="accordion-benefits4-2"><h3>Apakah rumah sakit menyediakan alat untuk mengambil darah tali pusat?</h3></div><div class="clearfix">
		<p>Setelah mendaftar dengan Stemcord,  Anda akan mendapatkan “Collection Kit” yang akan digunakan untuk mengambil darah tali pusat anak Anda. Collection Kit berisi semua peralatan dan perlengkapan yang diperlukan untuk proses pengambilan darah tali pusat. Yang perlu Anda lakukan hanyalah membawa Collection Kit ke rumah sakit dan memberikannya kepada petugas medis di rumah sakit. </p>
	</div></li>
	
	<li><div id="accordion-benefits4-3"><h3>Bagaimana darah tali pusat ini dikirimkan ke laboratorium StemCord?</h3></div><div class="clearfix">
		<p>Setelah menerima telpon Anda mengenai pemberitahuan persalinan Anda, Staf kami akan berjaga di rumah sakit. Setelah darah diterima oleh staf kami, maka ia akan mengirimkan darah ini melalui kurir ke laboratorium kami di Singapura.</p>
	</div></li>
	
	<li><div id="accordion-benefits4-4"><h3>Berapa banyak sel punca yang bisa didapatkan dari sebuah tali pusat?</h3></div><div class="clearfix">
		<p>Jumlah sel punca yang dapat diambil bervariasi dari bayi ke bayi lain, tergantung dari berat badan mereka, tebal tipisnya tali pusat, dan juga banyaknya volume darah yang terambil.</p>
	</div></li>
	
	<li><div id="accordion-benefits4-5"><h3>Apakah jumlah sel punca yang diambil dari tali pusat ini cukup untuk digunakan? </h3></div><div class="clearfix">
		<p>Hal ini penting untuk memaksimalkan volume darah yang diambil dari tali pusat,  karena hal ini sangat berkaitan dengan jumlah sel yang didapatkan. Jumlah minimal dari sekali  pengambilan adalah 200 juta sel. Akan tetapi lebih dari 25% pengguna StemCord mencapai lebih dari miliaran sel.</p>
		<p>Oleh karena itu sebagian besar sample kami memadai  untuk digunakan oleh anak-anak. Banyak juga yang dapat digunakan hingga orang dewasa dengan berat kurang lebih 50 kg. Untuk sebuah transplantasi yang sukses, diperlukan sedikitnya 10 juta sel per kilogram berat badan. Bila dalam pengambilan didapatkan jumlah sel yang tinggi, maka penggunaan berkali-kali dapat dilakukan.</p>
	</div></li>
	
	<li><div id="accordion-benefits4-6"><h3>Apakah akan ada kontaminasi dalam darah tali pusat? </h3></div><div class="clearfix">
		<p>Kontaminasi bakteri dapat terjadi akibat adanya bakteri dalam jalan lahir. Pada beberapa ibu hamil, dapat terjadi pertumbuhan yang berlebihan dari bakteri-bakteri ini sehingga menembus ke tali pusat dan mengakibatkan kontaminasi. Sebagai tambahan, factor lain seperti persalinan premature, ketuban pecah dini dan tali pusat yang tipis juga dapat meningkatkan resiko kontaminasi bakteri.</p>
	</div></li>
	
	<li><div id="accordion-benefits4-7"><h3>Bagaimana jika kami tidak tinggal di Singapura? </h3></div><div class="clearfix">
		<p>Bila Anda tinggal di Negara-negara dimana ada kantor representative kami, silakan hubungi mereka. Untuk Indonesia, hubungi Hotline 24 Jam kami di (021) 520 6555/ 6.</p>
	</div></li>
</ul>									
{% endblock %}