{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Pengambilan Darah Tali Pusat</h2>
						<p>Sel punca ini dapat dicairkan dan digunakan kapanpun keluarga Anda membutuhkannya. Hubungi Hotline 24 Jam kami di {{ phoneFullTag }} lalu kami akan melepaskan dan mengirimkan sel punca bayi Anda sesuai yang diperlukan ke rumah sakit yang ditunjuk.</p>

<p>StemCord mengakui bahwa ibu adalah pemilik dari sel punca ini sampai si anak mencapai usia 21 tahun.  Setelah itu, sang ibu berhak memindahkan hak kepemilikannya dan pembayaran biaya pemeliharaannya kepada si anak.</p>									
					
{% endblock %}