{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Penyimpanan Darah Tali Pusat</h2>
						<p><img width="630" height="330" src="http://www.stemcord.com/wp-content/uploads/2013/03/banking_cordblood_fea.jpg" class="attachment-post-thumbnail wp-post-image" alt="banking_cordblood_fea" /></p>
						<h3 class="page_margin_top">Bank Darah Tali Pusat</h3>
<p>Transplantasi darah tali pusat yang pertama kali berhasil dilakukan adalah pada tahun 1988 pada seorang anak laki-laki berusia 5 tahun, dengan Anemia Fanconi, yang memiliki usia harapan hidup yang rendah. Donornya adalah adik perempuannya yang baru saja lahir. Lebih dari 17 tahun kemudian, anak laki-laki ini masih hidup dan sembuh dari penyakitnya tersebut.</p>

<img class="size-full wp-image-1341 alignleft" alt="differentiation_stemcell" src="http://www.stemcord.com/wp-content/uploads/2013/03/banking_cord_blood.jpg" width="300" height="350" /><h3 class="page_margin_top">Aman dan Tidak Sakit</h3><p>Semakin banyak keluarga yang memilih untuk mengambil, memproses, dan menyimpan darah tali pusat bayi mereka karena Aman, tidak sakit, dan tidak memiliki kontroversi dalam proses pengambilannya. Sel punca tersebut memiliki potensi untuk menyembuhkan berbagai jenis penyakit, baik penyakit yang umum dan kanker atau kelainan darah seperti sickle-cell anemia, thalassemia, dan leukemia.</p>
<br /><br />
<h3 class="page_margin_top">Lebih Cocok dan Tingkat Komplikasi yang Rendah</h3>
<p>Hanya ada satu kali kesempatan untuk mengambil darah tali pusat yang sangat berharga ini. Sel punca dari tali pusat adalah sel yang masih sangat muda dan sehat, dan lebih memiliki kesempatan yang besar untuk memberi kecocokan bila digunakan untuk transplantasi. <br /><br />Merupakan sumber yang lebih disukai untuk transplantasi, karena memiliki tingkat komplikasi yang lebih rendah dibandingkan dengan transplantasi yang menggunakan sum-sum tulang. Dapat tersedia secara cepat jika dibutuhkan (jika disimpan di Bank Darah Tali Pusat Swasta), sehingga mengurangi waktu pencarian donor sel punca yang cocok dan pengobatan dapat dilaksanakan segera.</p>

<p>Garansi 100% kecocokan untuk bayi tersebut . Darah tali pusat juga dapat berpotensi memiliki peluang untuk kemungkinan kecocokan bagi saudara kandung dan orang tua. Calon orang tua menyimpan darah tali pusat untuk keluarga mereka, sel punca tidak hanya menyediakan perlindungan bagi kesehatan lebih dari itu sebagai pilihan pengobatan di masa mendatang. Beberapa keluarga mempunyai faktor risiko yang jelas, tetapi sering orang tua menyimpan untuk keamanan karena mengetahui manfaat dari sel punca suatu saat dibutuhkan untuk anak mereka atau anggota keluarga lainnya.</p>

<h3 class="page_margin_top">Sebuah Potensi Perawatan Medis dan Pengobatan Masa Depan</h3>
<p>Studi klinis terakhir menunjukkan bahwa sel punca darah tali pusat memiliki keunikan yang dapat digunakan untuk berbagai macam pengembangan teknologi. Dokter-dokter sangat antusias mengenai potensi darah tali pusat dalam bidang terapi genetic dan memperbaiki sel. Ketika Anda menyimpan darah tali pusat bayi Anda, Anda memberikan kemungkinan pemeliharaan suatu garis kehidupan yang amat berharga yang suatu saat dapat memberikan pilihan pengobatan yang tiada habisnya di masa mendatang.</p>
<br />
<span class="darkblue heavy">Untuk membantu Anda membuat keputusan yang tepat, kami berinisiatif mengumpulkan beberapa pertanyaan yang sering diajukan kepada kami.</span>

<ul class="accordion page_margin_top">
	<li><div id="accordion-benefits3-1"><h3>Siapa saja yang perlu menyimpan? </h3></div><div class="clearfix">
		<p>Semua orang tua sebaiknya menyimpan darah tali pusat bayinya kecuali Anda yang telah mendapat peringatan sebelumnya oleh dokter kandungan dikarenakan kondisi kehamilan Anda yang begitu riskan dan tidak memungkinkan untuk proses pengambilan. Penyimpaan darah tali pusat sabagi asuransi biologis ini kami anjurkan untuk para calon orang tua seperti berikut ini:</p>
		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">
				<span class="darkblue heavy">Keluarga dengan riwayat kelainan darah dan kanker</span><br />
				Bank darah tali pusat memberikan potensi untuk transplantasi sel punca sebagai tambahan pilihan pengobatan.
			</li>
			<li class="icon_small_arrow right_lightblue">
				<span class="darkblue heavy">Keluarga kecil, keluarga dengan anak tunggal, kehamilan yang sulit  atau terlambat atau pasangan kurang subur</span><br />
				Dalam situasi ini, si anak mungkin saja menjadi anak tunggal, sehingga ada kemungkinan ia tidak mendapatkan donor yang cocok bila diperlukan.
			</li>
			<li class="icon_small_arrow right_lightblue">
				<span class="darkblue heavy">Perkawinan campur (dari etnis yang berbeda)</span><br />
				Ini akan sulit bagi pasangan untuk mendapatkan donor yang cocok dikarenakan konstitusi genetik yang sangat berbeda.
			</li>
			<li class="icon_small_arrow right_lightblue">
				<span class="darkblue heavy">Kelahiran anak pertama</span><br />
				Sangat disarankan untuk menyimpan darah tali pusat dari anak pertama, karena kita tidak pernah tahu apakah akan ada kehamilan yang berikutnya. Sehingga bila anak tersebut menjadi anak tunggal, jika suatu hari nanti darah tali pusat diperlukan, ia tidak perlu bergantung pada sel punca keluarga yang lain.
			</li>
		</ul>
	</div></li>
	
	<li><div id="accordion-benefits3-2"><h3>Apakah Saya harus menyimpan darah tali pusat semua anak Saya?</h3></div><div class="clearfix">
		<p>Darah tali pusat dari setiap anak memiliki keunikan. Menyimpan darah tali pusat dari setiap anak akan memastikan kecocokan genetik bagi setiap anak. Disamping itu akan meningkatkan kemungkinan tambahan Anda memiliki cadangan darah tali pusat bagi anggota keluarga lainnya. Bagi kembar identik, disarankan untuk menyimpan darah tali pusat kedua bayi untuk mendapatkan sel punca dalam jumlah sebanyak-banyaknya. Hal ini diakibatkan pada pengambilan darah saat persalinan kembar biasanya volume yang didapat lebih sedikit, sehingga dengan mengambil darah dari kedua bayi kembar identik ini akan meningkatkan kecukupan jumlah sel punca untuk keperluan transplantasi.</p>
	</div></li>
	
	<li><div id="accordion-benefits3-3"><h3>Apakah darah tali pusat bayi Saya bisa digunakan untuk saudara kandungnya?</h3></div><div class="clearfix">
		<p>Ya. Darah tali pusat bayi Anda potensial dapat digunakan untuk anggota keluarga yang lain, terutama saudara kandungnya. Kkarena  dalam transplantasi darah tali pusat kita masih dapat menggunakan sel punca ini meskipun ada (hingga) dua antigen yang tidak cocok.</p>
	</div></li>
	
	<li><div id="accordion-benefits3-4"><h3>Apakah Saya harus pilih penyimpana darah tali pusat yang dekat dengan rumah Saya? </h3></div><div class="clearfix">
		<p>Keamanan dan kelangsungan hidup sel punca Anda adalah jauh lebih penting ketimbang jarak antara tempat tinggal Anda dan lokasi penyimpanan. Berikut adalah kriteria terpenting dalam memilih bank darah tali pusat adalah:

		<ul class="multiline-list clearfix">
			<li class="icon_small_arrow right_lightblue">
		Pengambilan darah tali pusat bayi Anda menghasilkan jumlah sel punca sebanyak mungkin, dan sel-selnya masih aktif dan hidup seAndainya nanti diperlukan untuk transplantasi. StemCord telah memberikan kontribusi dalam merawat pasien yang menderita kanker. Keberhasilan transplantasi sel punca yang telah disimpan dengan StemCord ini adalah bukti langkah-langkah pemrosesan dan metode penyimpanan StemCord yang ketat.
			</li>
			<li class="icon_small_arrow right_lightblue">
		Laboratorium dan fasilitas penyimpanan StemCord berada di lokasi yang tidak memiliki sejarah terkena bencana alam seperti topan, gempa bumi dan tornado. Laboratorium StemCord terletak di lokasi yang aman di Science Park I dan II. SeAndainya diperlukan, sel punca Anda dapat dikirimkan ke sentral pengobatan di seluruh dunia.
			</li>
			<li class="icon_small_arrow right_lightblue">
		Bank darah tali pusat yang stabil secara finansial dan akan tetap eksis di masa depan untuk menjamin sel punca bayi Anda akan selalu tersedia jika diperlukan. StemCord didirikan dengan tujuan  penyimpanan jangka panjang karena kami percaya penggunaan terbaik sel punca di masa depan. StemCord adalah bank darah tali pusat satu-satunya di Singapura yang menguntungkan  dengan kekuatan finansial untuk mempertahankan kebutuhan jangka panjang penyimpanan darah tali pusat.
			</li>
		</ul></p>
	</div></li>
	
	<li><div id="accordion-benefits3-5"><h3>Dapatkah Saya menyimpan darah tali pusat di bank darah tali pusat umum? </h3></div><div class="clearfix">
		<p>Ketika Anda mendonasikan darah tali pusat bayi Anda ke bank darah tali pusat umum, maka darah ini dapat digunakan untuk kepentingan penelitian atau untuk orang lain. Penting sekali bagi para orang tua untuk memahami bahwa tidak semua sampel darah tali pusat yang didonasikan akan disimpan. Disiplin yang sama dilakukan bagi donasi darah pada umumnya, bahwa tidak semua darah layak untuk disimpan. Penolakan dari bank umum dapat berdasarkan dari riwayat kesehatan keluarga, riwayat medis ibu, volume pengumpulan, dan pemeriksaan sampel darah ibu.</p>
		<p>Jika sel autolog tidak tersedia atau tidak dapat digunakan, maka pilihan berikutnya adalah sel punca dari keluarga (lebih diutamakan saudara kandung). Darah tali pusat dari orang yang sama sekali tidak memiliki hubungan darah memiliki resiko yang besar untuk terjadinya reaksi penolakan atau GVHD. Darah tali pusat yang memiliki hubungan darah akan mengurangi resiko pada sampel transplantasi yang mungkin mengandung masalah genetik yang dapat menyebabkan penyakit pada penerima donor, ini dikarenakan tidak ada informasi sebelumnya tentang sejarah genetik keluarga si pendonor.</p>
		<p>Sel punca darah tali pusat, lebih muda dibandingkan sel punca dewasa maka dari itu memiliki kemungkinan kecocokan yang tinggi dalam garis keluarga dibandingkan sel punca dewasa dari sumsum tulang belakang. Bank darah umum dapat menyediakan kecukupan jumlah sampel akan tetapi tidak dapat menjamin kecocokan yang tinggi antara donor dan penerima. Sementara keluarga yang menyimpan darah tali pusat bayinya akan memiliki kesempatan tinggi untuk mendapatkan darah tali pusat yang cocok bagi anggota keluarganya.</p>
	</div></li>
	
	<li><div id="accordion-benefits3-6"><h3>Seberapa barukah penyimpanan darah tali pusat ini?</h3></div><div class="clearfix">
		<p>Bank darah tali pusat yang pertama didirikan pada tahun 1992. StemCord adalah pelopor penyimpanan darah tali pusat di singapura, didirikan tahun 2002. Saat ini sudah lebih dari 30.000 keluarga telah mengambil keputusan untuk menyimpan darah tali pusat anak mereka di StemCord.</p>
	</div></li>
</ul>									
{% endblock %}