{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Sel Punca Darah Tali Pusat</h2>
						<p><img width="630" height="330" src="http://www.stemcord.com/wp-content/uploads/2013/03/stemcells.jpg" class="attachment-post-thumbnail wp-post-image" alt="stemcells" /></p>
						<h3 class="page_margin_top">Apakah Sel Punca itu?</h3>
<p>Sel punca adalah sel yang paling primitif di dalam tubuh kita, dan dapat berkembang menjadi organ-organ lain yang memiliki fungsi spesifik. Menurut sumbernya, sel punca dapat digolongkan menjadi sel punca dari embrio (embrionic stem cell) dan sel punca dewasa (adult stem cell). Embrionic stem cell didapatkan dari janin/embrio, dan merupakan sel punca yang paling poten, namun penggunaannya dalam bidang medis dan penelitian terbentur pada kontroversi masalah etika.</p>

<p>Sel punca &#8220;Dewasa&#8221; adalah sel punca yang ditemukan di dalam berbagai organ/ bagian tubuh setelah melewati tahap embrio / janin. Pada kenyataannya setiap organ/bagian tubuh kita mengandung sel puncanya masing-masing, contoh: sel punca darah, sel punca lemak, sel punca otot jantung, sel punca saraf, sel punca kulit dll. Sel punca inilah yang akan mengembangkan dan mematangkan setiap organ tubuh kita. Dalam beberapa organ, sel punca ini akan menjadi yang non-aktif setelah organ tersebut menjadi matang, namun ada juga yang tetap aktif, seperti sel punca darah selama kita hidup, secara terus-menerus membentuk sel-sel darah baru.</p>


<h3 class="page_margin_top">Diferensiasi Dari Sebuah Sel Punca</h3><img class="size-full wp-image-1341 alignleft" alt="differentiation_stemcell" src="http://www.stemcord.com/wp-content/uploads/2013/03/stemcells_differentiation.jpg" width="630" height="330" />
<p>Sel punca darah dapat ditemukan di darah tali pusat, sumsum tulang, dan pada sirkulasi darah tepi. Sel punca darah ini akan terus berkembang dan akhirnya menjadi sel- sel darah setelah matang, meliputi sel darah merah, sel darah putih, dan trombosit. Sel-sel ini akan melakukan fungsi-fungsi yang spesifik, seperti membawa oksigen (merah), melawan infeksi (putih), dan mencegah pendarahan (trombosit).</p>
<br /><br />
<h3 class="page_margin_top">Mengapa Sel Punca Begitu Penting?</h3>
<p>Pada tahun 1960, darah sel punca pertama kali digunakan untuk mengobati kanker. Sel Punca Darah ini didapatkan dari sumsum tulang belakang untuk mengobati pasien yang mengidap leukemia.</p>

<p>Pada awal tahun, pengobatan dengan cara ini kurang berhasil, akan tetapi seiring waktu, transplantasi / cangkok sumsum tulang belakang menjadi pilihan untuk menyelamatkan jiwa pasien - pasien yang mengidap leukemia dan berbagai macam penyakit kelainan/keganasan darah yang lain. Karena kebutuhan akan sel punca inilah, berbagai riset dan penelitian kemudian berhasil menemukan keberadaan sel punca di dalam darah tali pusat, dan pada akhirnya digunakan dalam transplantasi darah tali pusat.</p>
<h3 class="page_margin_top">Apakah Sel Punca Darah Tali Pusat itu?</h3>
<img class="size-full wp-image-1346 alignleft" alt="stock-photo-human-fetus-inside-the-womb-133423676" src="http://www.stemcord.com/wp-content/uploads/2013/03/baby_with_cordattached.jpg" width="300" height="370" /><p>Setelah kelahiran bayi, tali pusat dan plasenta biasanya akan dibuang. Akan tetapi, saat ini diketahui bahwa darah yang terdapat dalam tali pusat dan plasenta ini adalah sumber yang sangat kaya akan sel punca.</p>

<p>Seperti sumsum tulang, sel punca dari darah tali pusat dapat digunakan untuk mengobati berbagai macam penyakit yang berhubungan dengan darah dan sistem kekebalan tubuh, leukemia dan tumor padat tertentu serta beberapa kelainan bawaan.</p>

<p>Sel punca adalah bahan pembangun dalam darah dan sistem kekebalan tubuh kita. Sel-sel ini dapat berkembang menjadi sel-sel lain dalam tubuh kita. Sel punca darah tali pusat merupakan pasangan yang cocok untuk bayi tersebut dan membawa peluang kecocokan yang signifikan untuk anggota keluarga yang lain.</p>

<p>Penelitian secara konsisten  menunjukan bahwa darah tali pusat adalah sumber alternatif yang efektif dari sel punca darah (hematopoietic stem cells  atau HSC) untuk transplantasi pada orang dewasa yang setidaknya menunjukkan hasil yang sebanding dengan sumber HSC lain pada pasien dewasa.</p>			{% endblock %}