<!--==============================-->
 
</div><!-- page_layout -->
</div><!-- sc_page relative noborder -->
 
<div class="push"></div>
</div> <!-- site_container -->

<div id="bottom-curve"></div>
<div class="footer_container">
	<div class="footer">
		<div class="footer_box_container clearfix">
			<div class="footer_box">
							<div class="textwidget"><h3 class="box_header">
	<a href="{{ url('tentang-kami') }}" title="Tentang Kami">Tentang Kami</a>
</h3>
<ul class="footer_info_container clearfix">
	<li class="footer_info_row">
		<div class="footer_info_left">
			<a href="/tentang-kami/tentang-stemcord" title="Tentang StemCord">
				Tentang StemCord
			</a>
		</div>
		<div class="footer_info_right">
			<a href="/tentang-kami/akreditasi/" title="Akreditasi">
				Akreditasi
			</a>
		</div>
	</li>
	<li class="footer_info_row">
		<div class="footer_info_left">
			<a href="/tentang-kami/layanan-kami" title="Layanan Kami">
				Layanan Kami
			</a>
		</div>
		<div class="footer_info_right">
			<a href="/tentang-kami/fasilitas/" title="Fasilitas">
				Fasilitas
			</a>
		</div>
	</li>
	<li class="footer_info_row">
		<div class="footer_info_left">
			<a href="/tentang-kami/pendiri" title="Pendiri">
				Pendiri
			</a>
		</div>
		<div class="footer_info_right">
			<a href="/tentang-kami/video-kami" title="Video Kami">
				Video Kami
			</a>
		</div>
	</li>
	<li class="footer_info_row">
		<div class="footer_info_left">
			<a href="/tentang-kami/sejarah/" title="Sejarah">
				Sejarah
			</a>
		</div>
		
		<div class="footer_info_right">
			<a href="https://foursquare.com/v/stemcord-indonesia/4e13c2e2fa7622d439e4ea00" title="Lokasi Stemcord Indonesia">
				Lokasi
			</a>
		</div>
		
	</li>
</ul></div>
					</div>
			<div class="footer_box">
							<div class="textwidget"><h3 class="box_header">
	<a href="{{ url('layanan-pelanggan') }}" title="Layanan Pelanggan">Layanan Pelanggan</a>
</h3>
<ul class="footer_info_container clearfix">
	<li class="footer_info_row">
		<div class="footer_info_left">
			<a href="/layanan-pelanggan/friend-refer-friend/" title="Friend Refer Friend">
				Friend Refer Friend
			</a>
		</div>
		<div class="footer_info_right">
			<a href="/layanan-pelanggan/penyerahan-dokumen/" title="Penyerahan Dokumen">
				Penyerahan Dokumen
			</a>
		</div>
	</li>
	<li class="footer_info_row">
		<div class="footer_info_left">
			<a href="/layanan-pelanggan/perbaharui-informasi-anda/" title="Perbaharui Informasi Anda">
				Perbaharui Informasi Anda
			</a>
		</div>
		<div class="footer_info_right">
			<a href="/layanan-pelanggan/download-form/" title="Download Form">
				Download Form
			</a>
		</div>
	</li>
	<li class="footer_info_row">
		<div class="footer_info_left">
			<a href="/layanan-pelanggan/pilihan-pembayaran" title="Pilihan Pembayaran">
				Pilihan Pembayaran
			</a>
		</div>
		<div class="footer_info_right">
			<a href="/layanan-pelanggan/kotak-saran/" title="Kotak Saran">
				Kotak Saran
			</a>
		</div>
	</li>
	<!--
	<li class="footer_info_row">
		<div class="footer_info_left">
			<a href="/layanan-pelanggan/stemcord-client-feedback/" title="StemCord Client Feedback">
				StemCord Client Feedback
			</a>
		</div>
	</li>
	-->
</ul></div>
					</div>
			<div class="footer_box last">
							<div class="textwidget"><h3 class="box_header">
	<a href="{{ url('untuk-klien/kontak-kami') }}" title="Hubungi Kami">Hubungi Kami</a>
</h3>
<div class="footer_info_container">

	<h3><span style="color:#fff;">PT. PUTRA MAS INDAH</span></h3>
	<a href="http://stemcord.co">www.stemcord.co</a>
	<div class="clearfix"></div>

	<span class="orange">Sales & Marketing Office:</span><br>
	Tamara Center, Suite #636.<br>Jl. Jend Sudirman Kav. 24. Jakarta 12920 Indonesia<br>
	Tel: {{ phoneSimple }}<br>Fax: {{ faxSimple }}<br><br>
Email: <a href="mailto:info@stemcord.co">info@stemcord.co</a><br><br>

	<span class="orange">Billing Office</span><br>
	Tamara Center, Suite #636.<br>Jl. Jend Sudirman Kav. 24. Jakarta 12920 Indonesia<br>
	Tel: {{ phoneSimple }}<br>Fax: {{ faxSimple }}<br><br>
Email: <a href="mailto:billing@stemcord.co">billing@stemcord.co</a><br><br>

</div></div>
				</div>
		</div> <!-- footer_box_container -->
		<div class="copyright_area clearfix">
			<div class="copyright_left">
							<div class="textwidget"><ul class="foot-menu clearfix">
	<li><a href="/footnotes/privacy-policy">Privacy</a></li>
	<li><a href="/footnotes/terms-and-conditions">Terms & Conditions</a></li>
	<li><a href="/footnotes/disclaimer">Disclaimer</a></li>
	<li><a href="/footnotes/site-map">Sitemap</a></li>
</ul></div>
					</div>
			<div class="copyright_right">
							<div class="textwidget"><span class="copyright-text">Copyright &copy 2008-{{ date('Y') }} {{ companyName }}. All rights reserved.</span> <a class="scroll_top" href="#top" title="Scroll to top">Top ^</a><script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create', 'UA-37834509-2', 'stemcord.com');ga('send', 'pageview');</script></div>
					</div>
		</div> <!-- copyright_area -->
	</div> <!-- footer -->
</div> <!-- footer_container -->
<!--
<script type='text/javascript' src='http://www.stemcord.com/wp-content/plugins/contact-form-7/includes/js/jquery.form.min.js?ver=3.40.0-2013.08.13'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var _wpcf7 = {"loaderUrl":"http:\/\/www.stemcord.com\/wp-content\/plugins\/contact-form-7\/images\/ajax-loader.gif","sending":"Sending ..."};
/* ]]> */
</script>
<script type='text/javascript' src='http://www.stemcord.com/wp-content/plugins/contact-form-7/includes/js/scripts.js?ver=3.5.2'></script>
-->
</div><!-- full_container -->