<div id="full_container">
<!--========== Logo and Menu ==========-->
		<div class="header_container">
		
			<div id="top" class="clearfix">
				<div id="top-bar-container" class="clearfix">
					<div id="top-bar" class="clearfix">
						<a href="{{ url('untuk-klien/kontak-kami') }}" class="top-links" title="Kontak Kami">Kontak Kami</a><span class="top-links-separator">|</span>
						<a href="{{ url('untuk-klien/tanya-dokter') }}" class="top-links" title="Tanya Direktur Medis Kami">Tanya Direktur Medis Kami</a><span class="top-links-separator">|</span>
						<a href="{{ url('layanan-pelanggan') }}" class="top-links" title="Pusat Pelanggan">Pusat Pelanggan</a>
						<div id="searchform">
	<input class="searchtext" type="text" name="gquery" id="gquery" value="Search the site" onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;"/>
	<input type="submit" id="gsearch_go" class="searchbtn" value=" ">
</div>						<a class="social-youtube" href="http://www.youtube.com/stemcordsingapore" target="_blank"></a>
						<a class="social-facebook" href="https://www.facebook.com/StemCord" target="_blank"></a>
					</div>
				</div>
			</div>

			<div class="header clearfix">
			
				<div class="header-bar clearfix">
					
					<div class="header_top clearfix">
						<div class="header_right">
							<span id="stemcord-hotline-title">HOTLINE 24-JAM:</span>
							<a id="stemcord-hotline" href="tel:+62215206555" title="{{ companyName }} Hotline">{{ phoneSimple }}</a>
						</div>
					</div>
					
					<div class="header_left">
						<a id="header-logo" href="{{ url() }}" title="{{ companyName }}">
						</a>
					</div>
					
					<div class="header_right">
						<a href="{{ url('perbedaan-stemcord/fact-netcord-accreditation') }}" title="Accredited by FACT-NetCord" style="border-bottom: 0;"><div id="stemcord-fact"> </div></a>
					</div>
				</div>
				
				<ul id="menu-main" class="sf-menu header_right"><li class="submenu-nochild"><a href="{{ url('tentang-kami') }}">TENTANG KAMI</a> 
<ul class="sub-menu">
<li><a  href="{{ url() }}tentang-kami/tentang-stemcord">Tentang StemCord</a> </li>
<li><a  href="{{ url() }}tentang-kami/layanan-kami/">Layanan Kami</a> </li>
<li><a  href="{{ url() }}tentang-kami/pendiri/">Pendiri</a> </li>
<li><a  href="{{ url() }}tentang-kami/sejarah/">Sejarah</a> </li>
<li><a  href="{{ url() }}tentang-kami/akreditasi/">Akreditasi</a> </li>
<li><a  href="{{ url() }}tentang-kami/fasilitas/">Fasilitas</a> </li>
<li><a  href="{{ url() }}tentang-kami/video-kami/">Video Kami</a> </li>
<!--
<li><a  href="{{ url() }}tentang-kami/karir/">Karir</a> </li>
-->
</ul>
</li>
<li class="submenu-nochild"><a  href="{{ url('bank-darah-tali-pusat') }}">BANK DARAH TALI PUSAT</a> 
<ul class="sub-menu">
<li><a  href="{{ url() }}bank-darah-tali-pusat/keuntungan-bank-darah-tali-pusat/">Keuntungan Bank Darah Tali Pusat</a> </li>
<li><a  href="{{ url() }}bank-darah-tali-pusat/sel-punca-darah-tali-pusat/">Sel Punca Darah Tali Pusat</a> </li>
<li><a  href="{{ url() }}bank-darah-tali-pusat/penyimpanan-darah-tali-pusat/">Penyimpanan Darah Tali Pusat</a> </li>
<li><a  href="{{ url() }}bank-darah-tali-pusat/pengumpulan-darah-tali-pusat/">Pengumpulan Darah Tali Pusat</a> </li>
<li><a  href="{{ url() }}bank-darah-tali-pusat/pemrosesan-penyimpanan-darah-tali-pusat/">Pemrosesan &#038; Penyimpanan Darah Tali Pusat</a> </li>
<li><a  href="{{ url() }}bank-darah-tali-pusat/pengambilan-darah-tali-pusat/">Pengambilan Darah Tali Pusat</a> </li>
<li><a  href="{{ url() }}bank-darah-tali-pusat/daftar-penyakit-yang-dapat-ditangani/">Daftar Penyakit yang Dapat Ditangani</a> </li>
<li><a  href="{{ url() }}bank-darah-tali-pusat/masa-depan-darah-tali-pusat/">Masa Depan Darah Tali Pusat</a> </li>
</ul>
</li>
<li class="submenu-nochild"><a href="{{ url('perbedaan-stemcord') }}">PERBEDAAN STEMCORD</a> 
<ul class="sub-menu">
<li><a  href="{{ url() }}perbedaan-stemcord/mengapa-stemcord/">Mengapa StemCord?</a> </li>
<li><a  href="{{ url() }}perbedaan-stemcord/keuntungan-stemcord/">Keuntungan StemCord</a> </li>
<li><a  href="{{ url() }}perbedaan-stemcord/stemcord-bonus-cover/">StemCord Bonus Cover</a> </li>
<li><a  href="{{ url() }}perbedaan-stemcord/fact-netcord-accreditation/">FACT-NetCord Accreditation</a> </li>
<li><a  href="{{ url() }}perbedaan-stemcord/langkah-langkah-penyimpanan-dengan-stemcord/">Langkah-langkah Penyimpanan Dengan StemCord</a> </li>
</ul>
</li>
<li class="submenu-nochild"><a href="{{ url('harga-pendaftaran') }}">HARGA &#038; PENDAFTARAN</a> 
<ul class="sub-menu">
<li><a  href="{{ url() }}harga-pendaftaran/harga/">Harga</a> </li>
<li><a  href="{{ url() }}harga-pendaftaran/bagaimana-caranya-mendaftar/">Bagaimana Caranya Mendaftar</a> </li>
<li><a  href="{{ url() }}harga-pendaftaran/permintaan-information-kit">Permintaan Information Kit</a> </li>
</ul>
</li>
<li class="submenu-nochild"><a href="{{ url('event-artikel') }}">EVENT &#038; ARTIKEL</a> 
<ul class="sub-menu">
<li><a  href="{{ url() }}event-artikel/event/">Event</a> </li>
<li><a  href="{{ url() }}event-artikel/artikel/">Artikel</a> </li>
<li><a  href="{{ url() }}event-artikel/siaran-pers/">Siaran Pers</a> </li>

</ul>
</li>
<li class="submenu-nochild"><a  href="{{ url('tanya-jawab') }}">TANYA JAWAB</a> 
<ul class="sub-menu">
<li><a  href="{{ url() }}tanya-jawab/sel-punca-darah-tali-pusat/">Sel Punca Darah Tali Pusat</a> </li>
<li><a  href="{{ url() }}tanya-jawab/penyimpanan-darah-tali-pusat/">Penyimpanan Darah Tali Pusat</a> </li>
<li><a  href="{{ url() }}tanya-jawab/pengambilan-darah-tali-pusat/">Pengambilan Darah Tali Pusat</a> </li>
<li><a  href="{{ url() }}tanya-jawab/pemrosesan-penyimpanan/">Pemrosesan &#038; Penyimpanan</a> </li>
<li><a  href="{{ url() }}tanya-jawab/pengeluaran-darah-tali-pusat/">Pengeluaran Darah Tali Pusat</a> </li>
<li><a  href="{{ url() }}tanya-jawab/tentang-stemcord/">Tentang StemCord</a> </li>
<li><a  href="{{ url() }}tanya-jawab/registrasi-stemcord/">Registrasi StemCord</a> </li>
<li><a  href="{{ url() }}tanya-jawab/tentang-fact-netcord/">Tentang FACT-NetCord</a> </li>
</ul>
</li>
</ul>				<div class="mobile_menu">
					<select>
						<div class="menu-main-container"><option value="{{ url('tentang-kami') }}">TENTANG KAMI
<ul class="sub-menu">
<option value="{{ url('tentang-kami/tentang-stemcord') }}"> - Tentang Stemcord</li>
<option value="{{ url('tentang-kami/layanan-kami') }}"> - Layanan Kami</li>
<option value="{{ url('tentang-kami/pendiri') }}"> - Pendiri</li>
<option value="{{ url('tentang-kami/sejarah') }}"> - Sejarah</li>
<option value="{{ url('tentang-kami/akreditasi') }}"> - Akreditasi</li>
<option value="{{ url('tentang-kami/fasilitas') }}"> - Fasilitas</li>
<option value="{{ url('tentang-kami/video-kami') }}"> - Video Kami</li>
</ul>
</li>
<option value="{{ url('bank-darah-tali-pusat') }}">BANK DARAH TALI PUSAT
<ul class="sub-menu">
<option value="{{ url('bank-darah-tali-pusat/keuntungan-bank-darah-tali-pusat') }}"> - Keuntungan Bank Darah Tali Pusat</li>
<option value="{{ url('bank-darah-tali-pusat/sel-punca-darah-tali-pusat') }}"> - Sel Punca Darah Tali Pusat</li>
<option value="{{ url('bank-darah-tali-pusat/penyimpanan-darah-tali-pusat') }}"> - Penyimpanan Darah Tali Pusat</li>
<option value="{{ url('bank-darah-tali-pusat/pengumpulan-darah-tali-pusat') }}"> - Pengumpulan Darah Tali Pusat</li>
<option value="{{ url('bank-darah-tali-pusat/pemrosesan-penyimpanan-darah-tali-pusat') }}"> - Pemrosesan &#038; Penyimpanan Darah Tali Pusat</li>
<option value="{{ url('bank-darah-tali-pusat/pengambilan-darah-tali-pusat') }}"> - Pengambilan Darah Tali Pusat</li>
<option value="{{ url('bank-darah-tali-pusat/daftar-penyakit-yang-dapat-ditangani') }}"> - Daftar Penyakit yang Dapat Ditangani</li>
<option value="{{ url('bank-darah-tali-pusat/masa-depan-darah-tali-pusat') }}"> - Masa Depan Darah Tali Pusat</li>
</ul>
</li>
<option value="{{ url('perbedaan-stemcord') }}">PERBEDAAN STEMCORD
<ul class="sub-menu">
<option value="{{ url('perbedaan-stemcord/mengapa-stemcord') }}"> - Mengapa StemCord?</li>
<option value="{{ url('perbedaan-stemcord/keuntungan-stemcord') }}"> - Keuntungan StemCord</li>
<option value="{{ url('perbedaan-stemcord/stemcord-bonus-cover') }}"> - StemCord Bonus Covers</li>
<option value="{{ url('perbedaan-stemcord/fact-netcord-accreditation') }}"> - FACT-NetCord Accreditation</li>
<option value="{{ url('perbedaan-stemcord/langkah-langkah-penyimpanan-dengan-stemcord') }}"> - Langkah-langkah Penyimpanan Dengan StemCord</li>
</ul>
</li>
<option value="{{ url('harga-pendaftaran') }}">HARGA &#038; PENDAFTARAN
<ul class="sub-menu">
<option value="{{ url('harga-pendaftaran/harga') }}"> - Harga</li>
<option value="{{ url('harga-pendaftaran/bagaimana-caranya-mendaftar') }}"> - Bagaimana Caranya Mendaftar</li>
<option value="{{ url('harga-pendaftaran/permintaan-information-kit') }}"> - Permintaan Information Kit</li>
</ul>
</li>
<option value="{{ url('event-artikel') }}">EVENT &#038; ARTIKEL
<ul class="sub-menu">
<option value="{{ url('event-artikel/event') }}"> - Event</li>
<option value="{{ url('event-artikel/artikel') }}"> - Artikel</li>
<option value="{{ url('event-artikel/siaran-pers') }}"> - Siaran Pers</li>
</ul>
</li>
<option value="{{ url('tanya-jawab') }}">TANYA JAWAB
<ul class="sub-menu">
<option value="{{ url('tanya-jawab/sel-punca-darah-tali-pusat') }}"> - Sel Punca Darah Tali Pusat</li>
<option value="{{ url('tanya-jawab/penyimpanan-darah-tali-pusat') }}"> - Penyimpanan Darah Tali Pusat</li>
<option value="{{ url('tanya-jawab/pengambilan-darah-tali-pusat') }}"> - Pengambilan Darah Tali Pusat</li>
<option value="{{ url('tanya-jawab/pemrosesan-penyimpanan') }}"> - Pemrosesan &#038; Penyimpanan</li>
<option value="{{ url('tanya-jawab/pengeluaran-darah-tali-pusat') }}"> - Pengeluaran Darah Tali Pusat</li>
<option value="{{ url('tanya-jawab/tentang-stemcord') }}"> - Tentang StemCord</li>
<option value="{{ url('tanya-jawab/registrasi-stemcord') }}"> - Registrasi StemCord</li>
<option value="{{ url('tanya-jawab/tentang-fact-netcord') }}"> - Tentang FACT-NetCord</li>
</ul>
</li>
</div>					</select>
				</div>
				<!--
				<ul class="sf-menu header_right">
				</ul>
				<div class="mobile_menu">
				</div>
				-->
			</div>
		</div>
		
		<div id="top-fill"></div>
		<div id="top-curve"></div>