<ul class="home_box_container clearfix">
	<li id="side_home_box_1" class="home_box light_orange">
		<div id="home-box-widget"><h3 class="home-box-header">Gratis Info Kit</h3><div class="home-box-content"><img class="home-box-img" src="{{ url() }}img/stemcord-info-kit.jpg"><p class="home-box-text">Pelajari lebih lanjut tentang manfaat dari bank darah tali pusat. Klik di sini untuk mendapatakan GRATIS&nbsp;<a class="home-box-link" href="/pricing-and-enrolment/request-for-stemcords-information-kit/">Info Kit</a></p></div></div>	</li>
	<li class="separator-sidebar">&nbsp;</li>
	<li id="side_home_box_4" class="home_box dark_orange">
		<div id="home-box-widget"><h3 class="home-box-header">Membuat Appointment</h3><div class="home-box-content"><img class="home-box-img" src="{{ url() }}img/stemcord-make-an-appointment.jpg"><p class="home-box-text">Hubungi 021-520-6555/6 atau buat appointment dengan kami dengan konsultasi gratis.&nbsp;<a class="home-box-link" href="/client-centre/make-an-appointment/">Membuat Appointment</a></p></div></div>	</li>
	<li class="separator-sidebar">&nbsp;</li>
	<li id="side_home_box_2" class="home_box orange">
		<div id="home-box-widget"><h3 class="home-box-header">Kegiatan Yang akan datang</h3><div class="home-box-content"><img class="home-box-img" src="{{ url() }}img/stemcord-events.jpg"><p class="home-box-text">Bergabunglah Acara kami, Seminar dan Workshop yang diselenggarakan untuk mempersiapkan Anda menjadi seorang Ibu.&nbsp;<a class="home-box-link" href="/news-and-event/parenting-seminar/">Lihat Events</a></p></div></div>	</li>
	<li class="separator-sidebar">&nbsp;</li>
	<li id="side_home_box_3" class="home_box dark_orange">
		<div id="home-box-widget"><h3 class="home-box-header">Beritahukan Teman Anda</h3><div class="home-box-content"><img class="home-box-img" src="{{ url() }}img/stemcord-refer-a-friend.jpg"><p class="home-box-text">Sebarkan dan berbagi pengetahuan tentang bank darah tali pusat dengan teman-teman Anda.&nbsp;<a class="home-box-link" href="/client-centre/refer-a-friend/">Ajak Mereka Bergabung</a></p></div></div>	</li>
</ul>