{% include "partials/header.phtml" %}

<!-- slider nav 480 -->
<div class="slider-nav-480 clearfix">
  <a class="slider-nav-prev-480"></a>
  <a class="slider-nav-next-480"></a>
</div>

<div class="site_container narrow"> <!-- remove narrow class for wide screen -->

<!-- slider nav -->
<a class="slider-nav-prev"></a>
<a class="slider-nav-next"></a>

<!--========== Home Slider Images ==========-->
<!-- slider -->
<ul class="slider">
        <li style="background-image: url('{{ url('img/best-gift.jpg') }}'); width=1093px; height=670px">
      &nbsp;
    </li>
        <li style="background-image: url('{{ url('img/hope-for-the-future.jpg') }}'); width=1093px; height=670px">
      &nbsp;
    </li>
        <li style="background-image: url('{{ url('img/why-stemcord.jpg') }}');  width=1093px; height=670px">
      &nbsp;
    </li>
        <li style="background-image: url('{{ url('img/stemcord-multiple-storage.jpg') }}'); width=1093px; height=670px">
      &nbsp;
    </li>
  </ul>
<!--==============================-->

<div class="sc_page relative noborder">

<!--========== Home Slider Content ==========-->
<!-- slider content -->
<div class="slider_content_box clearfix">
        <div class="slider_content clearfix" style="display: block;">
        
      <div class="slider_text">
                    <h1 class="slider_pretitle slider2_pretitle">
              <span class="mediumtext"> </span>           </h1>
                <h1 class="slider_title slider2_title">
          <span class="largetext"> <br> <br> <br> <br> </span>        </h1>
                  <h2 class="slider_subtitle slider2_subtitle">
            <span class="smalltext"> </span>          </h2>
              </div>
                        <a title="SIGN UP NOW >>" href="/for-clients/make-an-appointment/" class="slider_link slider2_link" style="float:left;">SIGN UP NOW >></a>
                  </div>
        <div class="slider_content clearfix">
        
      <div class="slider_text">
                    <h1 class="slider_pretitle slider3_pretitle">
              <span class="mediumtext mediumweight">BANK bersama STEMCORD</span>            </h1>
                <h1 class="slider_title slider3_title">
          <span class="xlargetext"><b>Harapan</b> untuk <b>Masa Depan</b></span>        </h1>
                  <h2 class="slider_subtitle slider3_subtitle">
            <span class="smalltext">Simpan <b>Sel Punca Darah Tali Pusat</b><br>Bayi Anda sebagai Asuransi Biologi untuk Masa Depan.</span>         </h2>
              </div>
                        <a title="PELAJARI BAGAIMANA" href="/cord-blood-banking/benefits-of-cord-blood-banking/" class="slider_link slider3_link" style="float:left;">PELAJARI BAGAIMANA</a>
                  </div>
        <div class="slider_content clearfix">
        
      <div class="slider_text">
                  <h1 class="slider_pretitle slider4_pretitle">
            <span class="mediumtext">BANK DARAH TALI PUSAT SINGAPURA </span>          </h1>
                <h1 class="slider_title slider4_title">
          <span class="largetext"><b>Paling Bergengsi</b><br> dengan Akreditasi</span>        </h1>
                  <h2 class="slider_subtitle slider4_subtitle">
            <span class="smalltext"><b>FACT-NetCord</b></span>          </h2>
              </div>
                        <a title="WHY IS THIS IMPORTANT?" href="/stemcord-difference/fact-netcord-accreditation/" class="slider_link slider4_link" style="float:left;">KENAPA HAL INI PENTING?</a>
                  </div>
        <div class="slider_content clearfix">
        
      <div class="slider_text">
                  <h1 class="slider_pretitle slider5_pretitle">
            <span class="mediumtext"><b>SATU-SATUNYA</b> BANK DARAH TALI PUSAT YANG MEMBERIKAN PENYIMPANAN </span>          </h1>
                <h1 class="slider_title slider5_title">
          <span class="largetext">dalam 2 Cryobags di<br>2 <b>Lokasi Terpisah</b></span>        </h1>
                  <h2 class="slider_subtitle slider5_subtitle">
            <span class="smalltext">Nikmati Fleksibilitas Menggunakan <b>apa yang Dibutuhkan</b></span>         </h2>
              </div>
                        <a title="LEARN MORE" href="/stemcord-difference/the-stemcord-advantage/" class="slider_link slider5_link" style="float:left;">PELAJARI LEBIH LANJUT</a>
                  </div>
  </div>
<!--==============================-->
 
<!--========== Home Boxes ==========-->
 <ul class="home_box_container clearfix">
  <li id="home_box_1" class="home_box">
    <div id="home-box-widget"><h3 class="home-box-header">Gratis Info Kit</h3><div class="home-box-content"><img class="home-box-img" src="{{ url('img/stemcord-info-kit.jpg') }}" width=330 height=150><p class="home-box-text">Pelajari lebih lanjut tentang manfaat dari bank darah tali pusat. Klik di sini untuk mendapatakan GRATIS&nbsp;<a class="home-box-link" href="/pricing-and-enrolment/request-for-stemcords-information-kit/">Info Kit</a></p></div></div> </li>
  <li id="home_box_2" class="home_box">
    <div id="home-box-widget"><h3 class="home-box-header">Kegiatan Yang akan datang</h3><div class="home-box-content"><img class="home-box-img" src="{{ url('img/stemcord-events.jpg') }}" width=330 height=150><p class="home-box-text">Bergabunglah dengan Acara kami, Seminar dan Workshop untuk mempersiapkan Anda menjadi seorang Ibu.&nbsp;<a class="home-box-link" href="/news-and-event/educational-talk/">Lihat Events</a></p></div></div> </li>
  <li id="home_box_3" class="home_box">
    <div id="home-box-widget"><h3 class="home-box-header">Beritahukan Teman Anda</h3><div class="home-box-content"><img class="home-box-img" src="{{ url('img/stemcord-refer-a-friend.jpg') }}" width=330 height=150><p class="home-box-text">Sebarkan dan berbagi pengetahuan tentang bank  darah tali pusat dengan teman-teman Anda.&nbsp;<a class="home-box-link" href="/client-centre/refer-a-friend/">Ajak  Mereka bergabung</a></p></div></div> </li>
</ul>
<!--==============================-->
 
<!--========== Content ==========-->
<div class="page_layout page_margin_top clearfix">
 
<!-- The Loop -->

  <div id="post-8" class="post-8 page type-page status-publish hentry">
    
    <div class="entry clear">
            <div id="home-content">
<div class="announcement page_margin_top clearfix">
<ul class="columns no_width">
  <li class="column_left">
<h2>Ingin tahu lebih lanjut tentang Bank Darah Tali Pusat?</h2>
Hubungi {{ phoneSimple }} atau buat appointment dengan kami dengan konsultasi gratis</li>
  <li class="column_right">
<div class="vertical_align">
<div class="vertical_align_cell"><a class="more blue large" title="Membuat Appointment" href="/layanan-pelanggan/membuat-appointment/">Membuat Appointment</a></div>
</div></li>
</ul>
</div>
<h3 class="page_margin_top box_header">Keamanan, Pengalaman, Keahlian dan Kualitas</h3>
<ul class="gallery gallery_3_columns isotope">

<li class="gallery_box isotope-item" id="gallery-item-1"style="cursor: auto;"><img src="{{ url('img/info1.jpg') }}" width=310 height=200 /><div class="description"><h3>Akreditasi FACT-NetCord</h3><p>
StemCord adalah bank darah tali pusat yang pertama di Asia Tenggara dan Singapura yang berhasil mendapatkan akreditasi <b>FACT-NetCord</b>, suatu Badan Akreditasi Internasional yang paling bergengsi yang secara khusus menangani bank darah tali pusat.
<a title="gallery_item_title" href="/perbedaan-stemcord/fact-netcord-accreditation/">Mengapa ini penting?</a></div></li>

<li class="gallery_box isotope-item" id="gallery-item-2"style="cursor: auto;"><img src="{{ url('img/info2.jpg') }}" width=310 height=200 /><div class="description"><h3>StemCord Bonus Covers</h3><p>
Bonus Covers secara otomatis ditambahkan pada paket bank darah tali pusat, yang Anda cintai terjamin mendapatkan tambahan pertanggungan dan perlindungan.
<a title="gallery_item_title" href="/perbedaan-stemcord/stemcord-bonus-cover/">Lebih lanjut</a></div></li>

<li class="gallery_box isotope-item" id="gallery-item-3"style="cursor: auto;"><img src="{{ url('img/info3.jpg') }}" width=310 height=200 /><div class="description"><h3>Langkah-langkah penyimpanan sel punca darah tali pusat bayi anda</h3><p>
Dedikasi StemCord untuk selalu memberikan standar kualitas kontrol tertinggi dalam hal mutu untuk menjaga darah tali pusat bayi Anda.
<a title="gallery_item_title" href="/perbedaan-stemcord/langkah-langkah-penyimpanan-dengan-stemcord/">Mari Mulai</a></div></li>

</ul>
<div class="columns full_width page_margin_top clearfix" id="home-final-third">
<div class="left clearfix"><h3 class="box_header">Events and Workshops</h3></div>
<div class="right clearfix">
<h3 class="box_header">Like us on Facebook</h3>
<iframe style="border: none; overflow: hidden; width: 100%; max-width: 300px; height: 290px;" src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fstemcord&amp;width=300&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=true&amp;appId=230674160397683" height="240" width="320" frameborder="0" scrolling="no"></iframe>

</div>
</div>
</div>                </div><!--end entry-->
    
  </div><!--end post-->

  <div class="navigation index">
    <div class="alignleft"></div>
    <div class="alignright"></div>
  </div><!--end navigation-->


<!-- End The Loop -->

{% include "partials/footer.phtml" %}

