{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">FACT-NetCord Accreditation</h2>
						<p>StemCord adalah bank darah tali pusat yang pertama di Asia Tenggara dan Singapura yang  berhasil mendapatkan akreditasi <a href="http://www.factwebsite.org/" target="_blank">FACT-NetCord</a>, suatu Badan Akreditasi Internasional yang paling bergengsi yang secara khusus menangani bank darah tali pusat.</p>

<p style="text-align: center;"><img class="aligncenter size-full wp-image-322" alt="StemCord's FACT-NetCord Accreditation" src="http://www.stemcord.com/wp-content/uploads/2013/04/abt_accreditation.jpg" width="443" height="340" /></p>

<p>Akreditasi FACT-NetCord yang berhasil didapatkan StemCord pada 10 Januari 2011 khusus menangani Pengambilan darah tali pusat, Pemrosesan, Pengujian, Penyimpanan, Seleksi dan Pengeluaran, menegaskan kembali reputasi StemCord sebagai :
<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">
Pemimpin dalam industri bank darah tali pusat , dan sebagai
	</li>
	<li class="icon_small_arrow right_lightblue">
Perusahaan yang dikelola oleh para ahli medis yang profesional, yang senantisasa berusaha untuk mencapai stAndar Internasional tertinggi dalam memberikan pelayanan kesehatan yang berkualitas dalam program bank darah tali pusat.
	</li>
</ul></p>

<h3 class="page_margin_top">KeAndalan dan Pentingnya Akreditasi FACT-NetCord</h3>
<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">
FACT-NetCord adalah suatu badan akreditasi paling bergengsi yang membahas semua aspek kualitas dalam pengobatan terapi seluler: perawatan klinis, pengelolaan donor, pengumpulan sel, pengolahan sel, penyimpanan sel (bank), transportasi sel, administrasi sel, pemilihan sel dan pengeluaran sel.
	</li>
	<li class="icon_small_arrow right_lightblue">
Standarisasi  FACT-NetCord didefinisikan oleh tim internasional yang terdiri dari para pakar dalam bidang terapi seluler dari seluruh dunia dan diperbarui secara berkala melalui kerjasama dan masukan dari peneliti dan penemu yang bertanggung jawab untuk memajukan bidang ini. Serta secara aktif melibatkan masukan dari komunitas transplantasi dan masyarakat.
	</li>
	<li class="icon_small_arrow right_lightblue">
Para profesional dalam bidang kesehatan selular terapi  memastikan stAndar minimum yang harus terpenuhi dan bank darah tali pusat dengan Akreditasi FACT-NetCord  tidak hanya memenuhi persyaratan tersebut tetapi melebihi stAndar ini dan stAndarisasi lain yang telah ditetapkan oleh badan pemerintah.
	</li>
</ul>

<h3 class="page_margin_top">Kenapa Memilih Bank Darah Tali Pusat yang ter Akreditasi FACT-NetCord?</h3>
<p>Menyimpan darah tali pusat bayi Anda adalah komitmen jangka panjang dan karenanya penting untuk melakukan penyimpanan di bank darah tali pusat dengan stAndard kualitas tertinggi. Akreditasi FACT-NetCord yang didapat oleh suatu bank darah tali pusat meningkatkan kepercayaan pasien dan juga dokter untuk mendapatkan unit darah tali pusat yang berkualitas tinggi dan memastikan hasil yang diinginkan pasien. FACT-NetCord adalah satu-satunya badan akreditasi yang membahas semua aspek kualitas pengumpulan darah tali pusat, pemrosesan, pengujian, penyimpanan, seleksi dan pengeluaran.</p>

<p>FACT-NetCord adalah suatu Badan Akreditasi Internasional yang amat bergengsi dan karenanya hanya sedikit bank darah tali pusat yang berhasil mendapatkan akreditasi ini.</p>

<p>StemCord berusaha keras untuk mendapatkan FACT-NetCord dengan proses yang amat sangat ketat, karena kami percaya bahwa praktek dan pelayanan yang berkualitas adalah hal yang sangat penting. StemCord terus mempertahankan Akreditasi FACT-NetCord ini sehingga mampu memberikan pelayananan berkualitas tinggi dan terapi seluler dan menyediakan layanan kesehatan untuk pasien.</p>

<h3 class="box_header page_margin_top">Berikut keterangan lebih lengkap tentang FACT-NetCord </h3>

<ul class="accordion page_margin_top">
	<li><div id="accordion-stemcord4-1"><h3>Apa itu FACT-NetCord?</h3></div><div class="clearfix">
		<p>FACT (Foundation for the Accreditation of Cellular Therapy) menetapkan dan mempromosikan stAndar tertinggi untuk kualitas perawatan pasien dan kinerja laboratorium dengan keyakinan bahwa sebuah akreditasi yang sah  sebaiknya menilai dari kedua aspek . NetCord foundation adalah suatu jaringan Internasional non-profit bank darah tali pusat publik diciptakan untuk mempromosikan terbentuknya bank darah tali pusat dengan kualitas tinggi dan meningkatkan kualitas produk darah tali pusat melalui studi dan penelitian.</p>
		<p>Menyadari dampak global perbankan darah tali pusat dan transplantasi, FACT bekerja sama dengan NetCord di tahun 2000 untuk mengembangkan stAndar Internasional untuk pengambilan, pengolahan, pengujian , perbankan , seleksi dan pelepasan darah tali pusat. Sampai saat ini, FACT-NetCord adalah organisasi akreditasi yang paling bergengsi khususnya untuk bank darah tali pusat. </p>
	</div></li>
	
	<li><div id="accordion-stemcord4-2"><h3>Siapa yang mengembangkan program akreditasi FACT-NetCord?</h3></div><div class="clearfix">
		<p>Inspeksi dan program  akreditasi FACT dikembangkan oleh Dr. Phyllis Warkentin, Direktur Medis FACT, direktur dan pejabat FACT, serta lembaga internasional untuk terapi sel (ISCT), Lembaga Amerika untuk transplantasi darah dan sumsum tulabf ( ASBMT) , dan regulasi stAndar.
		Edisi pertama FACT stAndar dipublikasikan pada tahun 2000.</p>
	</div></li>
	
	<li><div id="accordion-stemcord4-3"><h3>Apa yang membedakan akreditasi FACT-NetCord dengan yang lainnya?</h3></div><div class="clearfix">
		<p>FACT-NetCord adalah satu-satunya organisasi akreditasi yang menangani semua aspek kualitas terapi sel hematopoietic (pengumpulan, pengolahan, dan transplantasi). Sebuah akreditasi FACT-NetCord diberikan setelah sukses pendokumentasian / bukti sesuai dengan stAndar FACT-NetCord. StAndar ini dikembangkan oleh tim ahli yang terkenal di dunia internasional di bidang terapi seluler. Mereka hanya melingkupi  seperangkat persyaratan internasional yang mencakup klinis maupun praktek laboratorium, dengan kepercayaan bahwa kualitas hanya bisa didapat jika masalah klinis dan laboratorium  secara efektif ditangani.</p>
	</div></li>
</ul>									
{% endblock %}