{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Keuntungan StemCord</h2>
						<p><img width="630" height="330" src="http://www.stemcord.com/wp-content/uploads/2013/04/stemcord_advantage.jpg" class="attachment-post-thumbnail wp-post-image" alt="stemcord_advantage" /></p>
						<ul class="accordion page_margin_top">
	<li><div id="accordion-stemcord1-1"><h3>Multiple Cryo Units: Penggunaan Bagi Seluruh Anggota Keluarga</h3></div><div class="clearfix">
		<p>StemCord adalah satu-satunya bank darah tali pusat di Singapura yang menyimpan darah tali pusat dalam 2 kantong darah, membuat Anda dapat menggunakan darah tali pusat sesuai dengan kebutuhan, serta menggunakan sistem yang diakui  U.S. FDA-approved, AABB dan FACT untuk penyimpanan sel punca jangka panjang - yaitu cryobags.</p>
	</div></li>
	
	<li><div id="accordion-stemcord1-2"><h3>Penyimpanan di Dua Lokasi yang Terpisah</h3></div><div class="clearfix">
		<p>StemCord adalah satu-satunya bank darah tali pusat di Singapura yang memisahkan darah tali pusat bayi Anda pada dua lokasi penyimpanan yang berbeda, di Science Park I dan II sebagai tambahan keamanan dan ketenangan pikiran Anda. </p>
	</div></li>
	
	<li><div id="accordion-stemcord1-3"><h3>Didukung dan Dikelola oleh Ahli Medis yang Sangat Terpercaya </h3></div><div class="clearfix">
		<p>StemCord didirikan dan dikelola oleh ahli kanker, ahli darah dan dokter-dokter yang terkenal dan berpengalaman serta memiliki kontribusi tinggi dalam proses transplantasi sel punca sumsum tulang dan darah tepi di Singapura.</p>
	</div></li>
	
	<li><div id="accordion-stemcord1-4"><h3>Pemrosesan Yang Sudah Terbukti di Laboratorium StemCord</h3></div><div class="clearfix">
		<p>Bank darah tali pusat kami dikelola oleh para ahli dibidangnya dan mendapat lisensi teknologi medis dalam penyimpanan darah tali pusat. Laboratorium StemCord telah memproses, menyimpan dan telah sukses menggunakan sel punca dari sumsum tulang dan darah tepi untuk berbagai macam pasien kanker dengan transplantasi sel punca konvensional.</p>
	</div></li>
	
	<li><div id="accordion-stemcord1-5"><h3>Memiliki Dua Laboratorium Khusus dan Fasilitas Penyimpanan</h3></div><div class="clearfix">
		<p>StemCord memiliki dan mengoperasikan dua laboratorium dan fasilitas penyimpanannya sendiri, didedikasikan hanya untuk pengambilan, pemrosesan, dan penyimpanan sel punca. Kami mengadopsi stAndar kualitas kontrol tertertinggi dan memberi jaminan pada viabilitas sel punca.</p>
	</div></li>
	
	<li><div id="accordion-stemcord1-6"><h3>Transportasi dan Penyimpanan yang Aman</h3></div><div class="clearfix">
		<p>StemCord memastikan bahwa darah tali pusat bayi Anda dibawa sampai ke laboratorium kami dengan selamat untuk menjalani pemrosesan dan penyimpanan sesegera mungkin.</p>
	</div></li>
	
	<li><div id="accordion-stemcord1-7"><h3>Bank Darah Tali Pusat yang Paling Kokoh di Singapura</h3></div><div class="clearfix">
		<p>StemCord adalah bank darah tali pusat swasta pertama di Singapura. Kami juga salah satu bank darah tali pusat terbesar yang telah  mengumpulkan, memproses dan menyimpan lebih dari 25.000 sampel darah tali pusat.</p>
	</div></li>
	
	<li><div id="accordion-stemcord1-8"><h3>Kemampuan Fiskal yang Kuat</h3></div><div class="clearfix">
		<p>StemCord percaya bahwa sel punca akan berguna di masa depan. Oleh karena itu, perusahaan harus stabil secara financial dan tetap eksis di masa yang akan datang. StemCord adalah bank darah tali pusat swasta Singapura yang menguntungkan, dengan kemampuan mempertahankan viabilitas sel-nya.</p>
	</div></li>
	
	<li><div id="accordion-stemcord1-9"><h3>Lisensi  dari Kementrian Kesehatan Singapura </h3></div><div class="clearfix">
		<p>StemCord mendapat lisensi dan diaudit oleh Kementrian Kesehatan Singapura.</p>
	</div></li>
	
	<li><div id="accordion-stemcord1-10"><h3>Akreditasi FACT-NetCord</h3></div><div class="clearfix">
		<p>StemCord merupakan bank darah tali pusat pertama di Asia Tenggara yang berhasil mendapatkan Akreditasi International paling bergengsi dari <a href="http://www.factwebsite.org/" target="_blank">FACT-NetCord</a>.</p>
	</div></li>
	
	<li><div id="accordion-stemcord1-11"><h3>Keberadaan di Area Regional yang Luas</h3></div><div class="clearfix">
		<p>StemCord memiliki jaringan yang terus berkembang dengan kantor-kantor perwakilan di Brunei, Indonesia, Filipina, dan Vietnam.</p>
	</div></li>
	
	<li><div id="accordion-stemcord1-12"><h3>Layanan 24 Jam: Respons Cepat</h3></div><div class="clearfix">
		<p>StemCord adalah mitra terpercaya Anda dalam penyimpanan darah tali pusat, beroperasi selama 365 hari per tahun, 24 jam per hari, untuk memberi Anda perhatian penuh, seperti yang Anda butuhkan.</p>
	</div></li>
</ul>
{% endblock %}