{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Langkah-langkah Penyimpanan Dengan StemCord</h2>
						<div class="video-container"><iframe width="640" height="360" src="//www.youtube.com/embed/UUpe_iZVjcA?feature=player_embedded" frameborder="0" allowfullscreen></iframe></div>

<p>Dedikasi StemCord untuk selalu memberikan stAndar kualitas kontrol tertinggi dalam hal mutu untuk menjaga darah tali pusat bayi Anda. Komitmen kami:
<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">
Menjaga viabilitas sel punca darah tali pusat
	</li>
	<li class="icon_small_arrow right_lightblue">
Menyimpan sel punca Anda sebanyak mungkin
	</li>
	<li class="icon_small_arrow right_lightblue">
Memaksimalkan potensi dengan menyimpan dalam beberapa unit penyimpanan 
	</li>
	<li class="icon_small_arrow right_lightblue">
Meminimalkan resiko kontaminasi dan tertukarnya sampel 
	</li>
</ul>
<br />
<h3 class="box_header">Langkah bermutu yang kami ambil dalam penyimpanan darah tali pusat</h3>
<ul class="accordion page_margin_top">
	<li><div id="accordion-stemcord5-1"><h3>Langkah 1: Pendaftaran yang Mudah</h3></div><div class="clearfix">
		<p>Hubungi {{ phoneFullTag }} untuk pendaftaran, dan staf kami akan membuat janji temu untuk menjelaskan lebih lanjut mengenai proses selanjutnya. Setelah melakukan pendaftaran (lebih baik sebelum usia kehamilan kurang dari 28 minggu), Anda akan menerima Collection Box. Informasikan dokter kebidanan  yang  menangani  Anda  bahwa Anda  telah mendaftar untuk penyimpanan darah tali pusat dengan StemCord </p>
	</div></li>
	
	<li><div id="accordion-stemcord5-2"><h3>Langkah 2: Hubungi StemCord</h3></div><div class="clearfix">
		<p>Bawalah Collection Box Anda ke rumah sakit dan hubungi hotline 24jam kami di {{ phoneFullTag }} pada saat menjelang kelahiran</p>
	</div></li>
	
	<li><div id="accordion-stemcord5-3"><h3>Langkah 3: Pengumpulan Darah yang Aman dan Mudah </h3></div><div class="clearfix">
		<p>Proses pengambilan darah tali pusat aman, cepat dan tidak sakit baik pada si ibu dan bayi nya. Setelah kelahiran bayi, dokter akan menjepit lalu memotong tali pusat, dan darah tali pusat akan dikumpulkan ke dalam kantong darah dengan metode gravitasi. Prosedur ini membutuhkan waktu kurang dari 5 menit. Kami juga membutuhkan 2 tabung darah ibu untuk diperiksa. Staf kami akan mengumpulkan seluruh kelengkapan Collection Box beserta formulirnya lalu mengemasnya untuk segera dikirim ke laboratorium kami di Singapura untuk diproses dan disimpan dengan aman.</p>
	</div></li>
	
	<li><div id="accordion-stemcord5-4"><h3>Langkah 4: Standar Ketat dalam Pemrosesan</h3></div><div class="clearfix">
		<p><img style="margin-left:10px;" align="right" alt="Stemcord Testing" src="http://www.stemcord.com/wp-content/uploads/2013/04/stemcord-stringent-standards-of-processing.jpg" />

		Di laboratorium canggih kami, darah tali pusat yang telah dikumpulkan kemudian akan dibekukan secara sistematis, proses pembekuan berlangsung bertahap turun -1o . Hingga suhu penyimpanan mencapai suhu optimal -180o C, darah tali pusat disimpan dalam tank yang berisi nitrogen cair. Proses ini dilakukan untuk memastikan integritas dan viabilitas sel. Sebagai tambahan, setiap unit darah tali pusat akan ditangani secara terpisah dan diproses secara otomatis untuk menghindari tertukarnya unit darah tali pusat.</p>
	</div></li>
	
	<li><div id="accordion-stemcord5-5"><h3>Langkah 5: Tes Laboratorium</h3></div><div class="clearfix">
		<p>Untuk memastikan bahwa darah tali pusat yang diambil aman dan dapat digunakan untuk transplantasi, maka StemCord akan melakukan beberapa tes terhadap darah tali pusat dan darah ibu, seperti berikut:</p>
		<div class="page_margin_top clearfix">
			<div class="column_left" style="width:280px"><strong>Penyakit-Penyakit Menular pada Darah Ibu:</strong>
			<ul class="multiline-list clearfix">
				<li class="icon_small_arrow right_lightblue">HIV1/2</li>
				<li class="icon_small_arrow right_lightblue">VDRL</li>
				<li class="icon_small_arrow right_lightblue">HBsAG</li>
				<li class="icon_small_arrow right_lightblue">HCV</li>
				<li class="icon_small_arrow right_lightblue">CMV (Cytomegalovirus)</li>
				<li class="icon_small_arrow right_lightblue">HTLV I/I (Human T-Lymphotropic Virus)</li>
			</ul></div>
			<div class="column_right" style="width:280px"><strong>Darah Tali Pusat:</strong>
			<ul class="multiline-list clearfix">
				<li class="icon_small_arrow right_lightblue">Pre &#038; Post Nucleated Cell Count</li>
				<li class="icon_small_arrow right_lightblue">Cell Viability</li>
				<li class="icon_small_arrow right_lightblue">ABO &#038; Rh</li>
				<li class="icon_small_arrow right_lightblue">CD34</li>
				<li class="icon_small_arrow right_lightblue">Bacteria Culture</li>
				<li class="icon_small_arrow right_lightblue">Fungal Culture</li>
			</ul></div>
		</div>
	</div></li>
	
	<li><div id="accordion-stemcord5-6"><h3>Langkah 6: Penyimpanan Ganda: 2 Cryo Unit dan Lokasi Terpisah</h3></div><div class="clearfix">
		<p><img style="margin-left:10px;" align="right" alt="Stemcord Testing" src="http://www.stemcord.com/wp-content/uploads/2013/04/stemcord-multiple-storage.jpg" />

		Di StemCord darah tali pusat diproses dan disimpan dalam tank nitrogen cair. StemCord adalah satu-satunya bank di Singapura yang menyimpan darah tali pusat bayi Anda dalam beberapa cryo unit, menggunakan sistem yang diakui  U.S. FDA-approved, AABB dan FACT untuk penyimpanan sel punca jangka panjang - yaitu cryo bags. Dengan menyimpan darah tali pusat dalam beberapa unit membuat Anda dapat menggunakan darah tali pusat sesuai dengan kebutuhan. Hal ini dikarenakan jika sekali darah tali pusat dicairkan maka darah tersebut tidak bisa dibekukan kembali (re-frozen). Sebagai tambahan keamanan dan perlindungan, StemCord memisahkan unit penyimpanan dalam 2 laboratorium di lokasi yang terpisah.</p>
	</div></li>
	
	<li><div id="accordion-stemcord5-7"><h3>Langkah 7: Penggunaan</h3></div><div class="clearfix">
		<p>Sel punca ini dapat dicairkan dan digunakan kapanpun keluarga Anda membutuhkannya. Hubungi hotline 24 jam kami di {{ phoneFullTag }} untuk memberi pelayanan terbaik kepada Anda.</p>
	</div></li>
</ul>									
{% endblock %}