{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Mengapa StemCord ?</h2>
						<div class="video-container"><iframe width="640" height="360" src="//www.youtube.com/embed/7bDfOahg4lU?feature=player_embedded" frameborder="0" allowfullscreen></iframe></div>

<p>Sejak awal, StemCord didirikan dengan satu misi, untuk memproses dan menyimpan sel punca darah tali pusat bayi Anda. Kami mengerti bahwa ini adalah komitmen jangka panjang, dan mendedikasikan diri kami agar menjadi bank darah tali pusat yang terpercaya, memberikan pelayanan yang terbaik bagi Anda untuk saat ini hingga masa yang akan datang. Berikut ini adalah beberapa kelebihan yang menjadikan kami sebagai pilihan yang terbaik dari bank darah tali pusat lainnya.</p>

<h3 class="page_margin_top">Stabilitas Perusahaan </h3>
<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">
StemCord adalah <span class="darkblue">bank darah tali pusat swasta pertama di Singapura</span> yang dilisensi oleh DepKes Singapura dan mulai beroperasi pada 6 Maret 2002. StemCord mengadopsi standar kualitas kontrol tertinggi dalam menjaga viabilitas sel punca.
	</li>
	<li class="icon_small_arrow right_lightblue">
StemCord holds the honour of being the <span class="darkblue">bank darah tali pusat pertama di Asia Tenggara dan satu-satunya bank darah tali pusat di Singapura yang mendapat Akreditasi <a href="/stemcord/fact-netcord-accreditation" target="_blank" alt="FACT-NetCord Accreditation">FACT-NetCord</a></span>. FACT-NetCord adalah suatu Badan Akreditasi International yang paling bergengsi yang secara khusus menangani Bank Darah Tali Pusat untuk Pengumpulan darah tali pusat, Pemrosesan, Pengujian, Penyimpanan, Seleksi dan Pengeluaran (release) darah tali pusat autolog.
	</li>
	<li class="icon_small_arrow right_lightblue">
StemCord adalah bank darah tali pusat swasta pertama dan <span class="darkblue">terbesar yang paling diminati di Singapura</span>. Pada Maret 2007, kami menetapkan sebagai tonggak baru di Singapura, karena kami sudah memiliki lebih dari 10.000 unit darah tali pusat yang disimpan pada laboratorium kami. Target utama kami adalah untuk memperbanyak cabang di berbagai daerah.
	</li>
	<li class="icon_small_arrow right_lightblue">
StemCord <span class="darkblue">didedikasikan untuk memproses dan menyimpan sel punca darah tali pusat</span>. Kami mendukung usaha penelitian dan pengembangan, akan tetapi kami tidak terlibat dalam usaha penelitian dan pengembangan yang beresiko secara finansial. Perusahaan kami memberi Anda keuntungan dan dapat dipercaya.
	</li>
	<li class="icon_small_arrow right_lightblue">
Keunikan StemCord terletak pada fakta bahwa <span class="darkblue">pemegang sahamnya adalah dokter-dokter</span> yang memahami bilogi dan seluk beluk sel punca, oleh karena itu StemCord memiliki visi yang lebih baik mengenai bagaimana penggunaan terbaik sel punca di masa depan. Dan seperti praktek medis mereka, kepentingan klien StemCord selalu menjadi yang paling utama.
	</li>
</ul>

<h3 class="page_margin_top">Metode Pemrosesan dan Penyimpanan yang Handal dan Terpercaya </h3>
<img class="size-full wp-image-1341 alignleft" alt="differentiation_stemcell" src="http://www.stemcord.com/wp-content/uploads/2013/03/2-bags-freezing.jpg" width="630" height="330" />
<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">
StemCord adalah <span class="darkblue">satu-satunya bank darah tali pusat di Singapura yang menyimpan darah tali pusat Anda di beberapa unit penyimpanan</span>. Dengan pengembangan penggunaan sel punca yang sangat pesat dalam hal terapi regeneratif, menyimpan sel punca dalam beberapa unit penyimpanan memungkinkan Anda untuk dapat menggunakannya beberapa kali. Sistem penyimpanan kami juga menghilangkan potensi kontaminasi silang selama penyimpanan, menjadikan kami sebagai penyimpanan darah tali pusat yang paling aman.
	</li>
	<li class="icon_small_arrow right_lightblue">
StemCord <span class="darkblue">memisahkan setiap unit darah tali pusat Anda di dua lokasi berbeda</span> untuk meningkatkan keamanan dan ketenangan pikiran Anda. Ini dilakukan karena visi StemCord untuk menyimpan dalam beberapa unit penyimpanan.
	</li>
</ul>									
{% endblock %}