{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">StemCord Bonus Cover</h2>
						<p><img width="630" height="400" src="http://www.stemcord.com/wp-content/uploads/2013/04/stemcord_bonuscovers.png" class="attachment-post-thumbnail wp-post-image" alt="stemcord_bonuscovers" /></p>
						<p>StemCord adalah satu-satunya bank darah tali pusat di Singapura yang telah mengambil langkah proaktif untuk memberikan tambahan beberapa fitur yang kami muat dalam paket StemCord, Bank Darah Tali Pusat Anda. kami berinisiatif untuk menawarkan bonus tidak hanya satu, tapi tiga Bonus Covers*: StemCord Care21, StemCord QualityPlus, StemCord AssuredPlus, yang Anda cintai terjamin mendapatkan tambahan pertanggungan dan perlindungan.</p>

<h3 class="page_margin_top">Bagaimana caranya mendaftar StemCord Bonus Covers?</h3>
<p>Semua klien StemCord baik itu klien baru ataupun klien yang sudah lama bergabung dimana darah tali pusat anak mereka telah diproses dan disimpan oleh StemCord secara otomatis dapat menikmati keuntungan dari StemCord Bonus Covers*<sup>1</sup>. Cukup hubungi (021)5206555/6 dan Client Relation Executive kami akan memberikan informasi lebih lanjut pada Anda.</p>
<br />
<h3 class="box_header">Paket StemCord Bonus Covers</h3>
<ul class="accordion page_margin_top">
<li><div id="accordion-stemcord3-1"><h3>StemCord Care21</h3></div><div class="clearfix">
<h4>Apa itu?</h4>
Menanggung anak Anda hingga berumur 21 tahun bilamana salah satu orang tua kandung meninggal dunia*
<h4 class="page_margin_top">Detail</h4>
Anda tidak perlu lagi khawatir apa yang akan terjadi pada penyimpanan darah tali pusat anak Anda jika terjadi keadaan tak terduga dimana Anda atau ayah biologis anak Anda meninggal dunia. StemCord mengetahui betapa pentingnya melindungi yang Anda cintai. Dengan StemCord Care21 bonus cover, kami akan membebaskan secara total* biaya tahunan penyimpanan darah tali pusat anak Anda dan melanjutkan penyimpanan* unit darah tali pusat sampai anak Anda berusia 21 tahun. 
<h4 class="page_margin_top">Dokumen apa saja yang Saya perlukan untuk mengajukan klaim? </h4>
Dalam hal tak terduga yang kami perlukan untuk melakukan klaim adalah sebagai berikut:

diperlukan<sup>2</sup> surat kematian.

</div></li>

<li><div id="accordion-stemcord3-2"><h3>StemCord QualityPlus</h3></div><div class="clearfix">
<h4>Apa itu?</h4>
Membayarkan S$ 25,000 sebagai penggantian biaya transplantasi*
<h4 class="page_margin_top">Detail</h4>
Ketika Anda telah mempercayakan darah tali pusat anak Anda pada StemCord, Anda akan terlindungi oleh StemCord QualityPlus, jaminan kualitas darah tali pusat anak Anda agar layak digunakan. Bilamana unit darah tali pusat anak Anda yang telah diproses dan disimpan di StemCord akan digunakan dalam transplantasi sel punca yang telah mengikuti standarisasi serta praktek medis yang diakui akan tetapi tidak berhasil dicangkokkan, maka StemCord akan membayar S$ 25,000 untuk membantu biaya yang dikeluarkan untuk pengadaan sumber sel punca alternatif jika ada indikasi medis. 
<h4 class="page_margin_top">Dokumen apa saja yang Saya perlukan untuk mengajukan klaim? </h4>
Dalam hal tak terduga yang kami perlukan untuk melakukan klaim adalah sebagai berikut:

menyerahkan<sup>2</sup> laporan laboratorium serta pernyataan yang mendukung dari dokter yang merawat bahwa  pencangkokan telah gagal.

</div></li>

<li><div id="accordion-stemcord3-3"><h3>StemCord AssuredPlus</h3></div><div class="clearfix">
<h4>Apa itu?</h4>
Membayarkan Biaya Tes HLA Resolusi Rendah pada unit darah tali pusat*
<h4 class="page_margin_top">Detail</h4>
Ketika unit darah tali pusat akan digunakan Anda tidak perlu lagi khawatir akan keselamatan Anda dan orang yang Anda cintai. StemCord AssuredPlus menjamin dan meningkatkan keselamatan pasien dengan melakukan Tes HLA Resolusi rendah* pada unit darah tali pusat yang diminta untuk transplantasi. 
<h4 class="page_margin_top">Dokumen apa saja yang Saya perlukan untuk mengajukan klaim?</h4>
In the unforeseen event that a claim needs to be made:

Dalam hal tak terduga yang kami perlukan untuk melakukan klaim adalah sebagai berikut:  untuk dapat mengeluarkan unit darah tali pusat, klien harus melengkapi formulir persetujuan dan formulir permintaan pelepasan darah  tali pusat yang disahkan oleh dokter yang akan melakukan transplantasi.<sup>2</sup>

</div></li>
</ul>

<div class="disclaimer">

<p>Catatan Penting dan Sanggahan</p>

<p>*Untuk persyaratan yang lebih detail, ketentuan-ketentuan, dan pengecualian silakan merujuk pada Bonus Covers yang terlampir dalam Perjanjian Darah Tali Pusat StemCord yang dapat diperoleh dari Customer Service StemCord. StemCord Pte. Ltd.  berhak mengubah, menambah atau mengganti setiap  syarat dan ketentuan StemCord BonusCovers dari waktu ke waktu tanpa ada pemberitahuan sebelumnya. Untuk salinan daftar syarat dan ketentuan StemCord BonusCovers, silahkan email ke {{ emailFullTag }}</p>

<p><sup>1</sup> Untuk mendapatkan keuntungan Bonus Covers ini, sebelumnya Anda diminta untuk menAndatangani Perjanjian Darah Tali Pusat StemCord dan masih aktif menyimpan darah tali pusat bayi Anda. Pertanggungan ini akan terus menerus bejalan dan keuntungan Bonus Covers dapat terus Anda nikmati  selama biaya penyimpanan tahunan darah tali pusat/ segala biaya yang menyangkut StemCord telah dibayar lunas sesuai dengan ketentuan yang ditetapkan dalam Perjanjian Darah Tali Pusat StemCord.</p>

<p><sup>2</sup> Silahkan merujuk pada Perjanjian Darah Tali Pusat StemCord (BonusCovers Appendix I) untuk persyaratan yang lebih detail, ketentuan-ketentuan, dan pengecualian. Dalam hal klaim, klien memerlukan Perjanjian Darah Tali Pusat  yang asli, identitas dan keterangan klien, serta didukung oleh formulir terkait dari dokter yang akan melakukan  transplantasi. Untuk salinan daftar syarat dan ketentuan StemCord BonusCovers, silahkan email ke {{ emailFullTag }}.</p>

</div>									
{% endblock %}