{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Bagaimana Caranya Mendaftar</h2>
						<p><img width="630" height="330" src="http://www.stemcord.com/wp-content/uploads/2013/04/stemcord_howtogetstarted.jpg" class="attachment-post-thumbnail wp-post-image" alt="stemcord_howtogetstarted" /></p>
						<div class="dropcap"><div class="dropcap_label"><h3>1</h3></div>
Untuk pendaftaran hubungi {{ phoneFullTag}} atau isi <a href="/for-clients/make-an-enquiry/" alt="Form Kontak">Form Kontak</a> untuk informasi lebih lanjut. Client Relation Executive kami akan mengatur pertemuan dengan Anda untuk menberikan informasi yang Anda butuhkan.<br />&nbsp;</div>

<div class="dropcap"><div class="dropcap_label"><h3>2</h3></div>
Daftarkan diri Anda ke StemCord (lebih baik pada usia sebelum usia kehamilan mencapai 28 minggu) dengan cara:
<div style="margin-left:55px">
<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">Tandatangani perjanjian StemCord</li>
	<li class="icon_small_arrow right_lightblue">Melengkapi formulir riwayat kesehatan</li>
	<li class="icon_small_arrow right_lightblue">Anda akan menerima Cord Blood Collection Box yang berisi peralatan pengambilan darah</li>
	<li class="icon_small_arrow right_lightblue">Membayar biaya pendaftaran (tunai ataupun transfer)</li>
</ul></div>
</div>

<div class="dropcap"><div class="dropcap_label"><h3>3</h3></div>
Informasikan dokter Anda pada pertemuan selanjutnya bahwa Anda telah mendaftar untuk penyimpanan darah tali pusat dengan StemCord<br />&nbsp;</div>

<div class="dropcap"><div class="dropcap_label"><h3>4</h3></div>
Pada saat hari kelahiran:
<div style="margin-left:55px">
<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">Hubungi help-line StemCord di <span class="lightblue">{{ phoneFullTag}} atau 0811 8800 488.</span></li>
	<li class="icon_small_arrow right_lightblue">informasikan kepada dokter/ perawat untuk mengambil darah tali pusat pada saat kelahiran bayi Anda </li>
	<li class="icon_small_arrow right_lightblue">Serahkan Cord Blood Collection Box kepada perawat yang bertugas </li>
	<li class="icon_small_arrow right_lightblue">hubungi saluran 24-jam kami <span class="lightblue">{{ phoneFullTag}}</span> sesudah selesai.</li>
</ul></div><br />&nbsp;</div>									
{% endblock %}