{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Harga</h2>
						<p><img width="630" height="330" src="http://www.stemcord.com/wp-content/uploads/2013/04/stemcord_pricing.jpg" class="attachment-post-thumbnail wp-post-image" alt="{{ companyName }} Harga" /></p>
						<p>Saat tiba waktunya melakukan pembayaran, StemCord memberikan Anda fleksibilitas dan pilihan yang sesuai dengan kebutuhan keluarga Anda.</p>

<p>Bersama StemCord, Anda dapat dengan mudah memilih salah satu dari pilihan berikut:</p>


<table class="timetable" style="margin-top: 0;">
	<thead class="row_head"><tr>
		<th>Standard Payment Plans<br />(w/o) GST</th><th>Annual Plan</th><th>6-Year Plan</th><th>11-Year Plan</th><th>21-Year Plan</th>
	</tr></thead>
	<tbody>
	<tr class="row_gray">
		<td>One-Time Enrolment Fee</td><td>$2000</td><td>$2000</td><td>$2000</td><td>$2000</td>
	</tr>
	<tr>
		<td>1<sup>st</sup> Year Storage Fee</td><td>INCLUSIVE</td><td>INCLUSIVE</td><td>INCLUSIVE</td><td>INCLUSIVE</td>
	</tr>
	<tr class="row_gray">
		<td>2<sup>nd</sup> &#038; Subsequent Year Fees</td><td>$275<br />($275/year)**</td><td>$1250<br />($250 x 5)</td><td>$2375<br />($237.50 x 10)</td><td>$4500<br />($225 x 20)</td>
	</tr>
	<tr style="border-top: 1px solid #234397;color: #333;">
		<td style="font-weight:bold;font-family: 'Avenir LT W01 85 Heavy', Helvetica, sans-serif;">Total Payable*</td><td style="font-weight:bold;font-family: 'Avenir LT W01 85 Heavy', Helvetica, sans-serif;">$2000</td><td style="font-weight:bold;font-family: 'Avenir LT W01 85 Heavy', Helvetica, sans-serif;">$3250</td><td style="font-weight:bold;font-family: 'Avenir LT W01 85 Heavy', Helvetica, sans-serif;">$4375</td><td style="font-weight:bold;font-family: 'Avenir LT W01 85 Heavy', Helvetica, sans-serif;">$6500</td>
	</tr>
	</tbody>
</table>
<br />&nbsp;

<p>Kami senang bisa melayani Anda. Untuk informasi lebih detail tentang StemCord atau informasi harga terbaru silakan hubungi kami di {{ phoneFullTag }} or <a href="{{ url('untuk-klien/buat-janji') }}">buat janji temu (Appointment)</a></p>

<a title="Daftar Sekarang" href="{{ url('harga-pendaftaran/bagaimana-caranya-mendaftar') }}" class="page_margin_top more orange icon_round_arrow">Daftar Sekarang</a>
<br />&nbsp;<br />&nbsp;

<div class="disclaimer"><p>* Pembayaran  dilakukan pada saat penandatanganan Perjanjian , sebelum penyerahan kotak perlengkapan pengambilan darah (Collection Kit).<br />
** Pembayaran ini akan jatuh tempo pada saat tanggal ulang tahun kelahiran anak mulai tahun ke-2 dan seterusnya.</p></div>								
{% endblock %}