{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Permintaan Informasi Kit</h2>
{% if isSubmit %}
						<ul>

	<li id="gallery-details-1" class="gallery_item_details"><div class="columns no_width"><div class="column_left"><div class="details_box">


<br />
<p>Dear <strong>{{ name }}</strong>, Permintaan Information Kit Anda sudah diterima.</p>
<p>Terima kasih telah mengirimkan permintaan informasi ini. Staf kami akan mengontak Anda dengan segera. Apabila ada yang ingin ditanyakan lebih lanjut silahkan menghubungi {{ phoneFullTag }} atau HP {{ mobileCall }}.</p>
<br />
<p>Terima kasih</p>
<br />
<p>Salam,<br />
StemCord</p>
		
	<ul class="controls page_margin_top"><li><a href="{{ url('harga-pendaftaran/permintaan-information-kit') }}">Kembali ke halaman sebelumnya</a></li></ul></div></div></div></li>
</ul>
{% else %}
<div class="gallery-hide">

<p>Untuk mengetahui lebih lanjut tentang  penyimpanan darah tali pusat dan manfaatnya saat ini. Mohon mengisi formulir di bawah ini untuk permohonan  kit informasi StemCord  yang akan dikirim ke email Anda secara gratis. Jika Anda memilih untuk memiliki kit informasi yang dikirimkan ke alamat tempat tinggal Anda sebagai gantinya, silakan mengisi pada  bagian bawah ini.</p>

<div class="wpcf7" id="wpcf7-f402-p403-o1">
<div class="screen-reader-response"></div>
<form action="{{ url('harga-pendaftaran/permintaan-information-kit') }}" method="post" class="wpcf7-form wpcf7-acceptance-as-validation" novalidate="novalidate">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="402" />
<input type="hidden" name="_wpcf7_version" value="3.8.1" />
<input type="hidden" name="_wpcf7_locale" value="" />
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f402-p403-o1" />
<input type="hidden" name="_wpnonce" value="5fa306ae64" />
</div>
<div class="contact_form">

<div class="note">bagian yang ditandai dengan * wajib diisi.</div>

<div class="clearfix">
<h3 class="box_header page_margin_top">Detail Kontak</h3>
<fieldset class="left">

    <label>Nama *</label><div class="block">
        <span class="wpcf7-form-control-wrap kit-req-name"><input type="text" name="kit-req-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" id="kit-req-name" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Alamat Email *</label><div class="block">
        <span class="wpcf7-form-control-wrap kit-req-email"><input type="email" name="kit-req-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email text_input" aria-required="true" aria-invalid="false" /></span>
    </div>
	
</fieldset>

<fieldset class="right">

	<label>Nomor Kontak *</label><div class="block">
        <span class="wpcf7-form-control-wrap kit-req-contact-num"><input type="text" name="kit-req-contact-num" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Waktu terbaik untuk di-telepon *</label>
    <div class="block">
        <span class="wpcf7-form-control-wrap kit-req-best-time-to-call"><select name="kit-req-best-time-to-call" class="wpcf7-form-control wpcf7-select wpcf7-validates-as-required select-box" aria-required="true" aria-invalid="false"><option value="">---</option><option value="Pagi">Pagi</option><option value="Siang">Siang</option><option value="Malam">Malam</option></select></span>
    </div>
	
</fieldset>

</div>
<div class="clearfix">

<h3 class="box_header page_margin_top">Detail Surat Menyurat</h3>

<fieldset class="left">

    <label>Alamat Surat Menyurat *</label><div class="block">
        <span class="wpcf7-form-control-wrap kit-req-mail-address"><textarea name="kit-req-mail-address" cols="40" rows="7" class="wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false"></textarea></span>
    </div>

</fieldset>
	
<fieldset class="right">

    <label>Negara *</label><div class="block">
        <span class="wpcf7-form-control-wrap kit-req-country"><input type="text" name="kit-req-country" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Kode Pos *</label><div class="block">
        <span class="wpcf7-form-control-wrap kit-req-postalcode"><input type="text" name="kit-req-postalcode" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>
</div>
<div class="clearfix">

<h3 class="box_header page_margin_top">Detail Kelahiran Bayi</h3>

<fieldset class="left">
    
	<label>Rencana Tanggal Kelahiran</label><div class="block">
        <span class="wpcf7-form-control-wrap kit-req-expected-date-of-delivery"><input type="text" name="kit-req-expected-date-of-delivery" value="" size="40" class="wpcf7-form-control wpcf7-text pick-date text_input" aria-invalid="false" /></span>
    </div>
	
	<div class="block">
        <span class="wpcf7-form-control-wrap kit-req-not-expecting"><span class="wpcf7-form-control wpcf7-checkbox"><span class="wpcf7-list-item first last"><input type="checkbox" name="kit-req-not-expecting[]" value="Centang jika tidak tahu" />&nbsp;<span class="wpcf7-list-item-label">Centang jika tidak tahu</span></span></span></span>
    </div>
	
	<div class="note"><p>Silahkan isi isian dengan NA pada bagian ini apabila tidak di-kehendaki</p></div>
	
</fieldset>

<fieldset class="right">


    <label>Nama dokter kebidanan *</label><div class="block">
        <span class="wpcf7-form-control-wrap kit-req-gynaecologist"><input type="text" name="kit-req-gynaecologist" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>
	
</fieldset>

</div>

<div class="clearfix">

<h3 class="box_header page_margin_top">Bagaimana Anda mengetahui tentang StemCord</h3>

<fieldset class="left">

    <label>Referral *</label><div class="block">
        <span class="wpcf7-form-control-wrap kit-req-referral"><select name="kit-req-referral" class="wpcf7-form-control wpcf7-select wpcf7-validates-as-required select-box" aria-required="true" aria-invalid="false"><option value="">---</option><option value="Dokter">Dokter</option><option value="Perawat">Perawat</option><option value="Teman/Relasi">Teman/Relasi</option><option value="Klien StemCord">Klien StemCord</option><option value="NA">NA</option></select></span>
    </div>

</fieldset>

<fieldset class="right">

    <label>Iklan *</label><div class="block">
        <span class="wpcf7-form-control-wrap kit-req-advertisement"><select name="kit-req-advertisement" class="wpcf7-form-control wpcf7-select wpcf7-validates-as-required select-box" aria-required="true" aria-invalid="false"><option value="">---</option><option value="Surat Kabar">Surat Kabar</option><option value="Majalah">Majalah</option><option value="Internet Search Engine">Internet Search Engine</option><option value="Brosur di praktek dokter/rumahsakit">Brosur di praktek dokter/rumahsakit</option><option value="Seminar">Seminar</option><option value="Facebook">Facebook</option><option value="Lainnya">Lainnya</option></select></span>
    </div>

</fieldset>
</div>
<fieldset class="page_margin_top" style="clear:both;">

<h3 class="box_header page_margin_top">Lainnya</h3>

    <label>Pesan/Pertanyaan</label><div class="block">
        <span class="wpcf7-form-control-wrap kit-req-message"><textarea name="kit-req-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea text_input" aria-invalid="false"></textarea></span>
    </div>

</fieldset>

<p class="submit-consent">Dengan meng-input form ini. Saya menerima dan setuju untuk disertakan dalam mailing list StemCord dan dihubungi oleh Stemcord dan rekanan untuk komunikasi lebih lanjut.<br>
Saya menyukai untuk dihubungi via:
<span class="wpcf7-form-control-wrap contact-by"><span class="wpcf7-form-control wpcf7-checkbox wpcf7-validates-as-required"><span class="wpcf7-list-item first"><input type="checkbox" name="contact-by[]" value="Telepon" />&nbsp;<span class="wpcf7-list-item-label">Telepon</span></span><span class="wpcf7-list-item last"><input type="checkbox" name="contact-by[]" value="SMS" />&nbsp;<span class="wpcf7-list-item-label">SMS</span></span></span></span></p>

<p><input type="submit" value="Kirim" class="wpcf7-form-control wpcf7-submit more blue" /></p>
</div><div class="wpcf7-response-output wpcf7-display-none"></div></form></div>

</div>
{% endif %}									
{% endblock %}