{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Akreditasi</h2>
						<h3 class="page_margin_top">Lisensi  dari Kementrian Kesehatan Singapura</h3>
<p>StemCord mendapat lisensi dan diaudit oleh Kementrian Kesehatan Singapura.</p>
<p style="text-align: center;"><img class="aligncenter" alt="Singapore's Ministry of Health License" src="http://www.stemcord.com/wp-content/uploads/2013/04/abt_license.jpg" width="443" height="650" /></p>

<h3 class="page_margin_top">Akreditasi FACT-NetCord (Foundation for the Accreditation of Cellular Therapy and NetCord)</h3>
<p>StemCord merupakan Bank Darah Tali Pusat pertama di Asia Tenggara yang berhasil mendapatkan <a href="{{ url('perbedaan-stemcord/fact-netcord-accreditation') }}">akreditasi FACT-NetCord</a> suatu Badan International paling bergengsi yang secara khusus menangani bank darah tali pusat</p>
<p style="text-align: center;"><img class="aligncenter" alt="StemCord's FACT-NetCord Accreditation" src="http://www.stemcord.com/wp-content/uploads/2013/04/abt_accreditation.jpg" width="443" height="340" /></p>									
					
{% endblock %}