{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Fasilitas</h2>
						<p>StemCord memiliki kantor di dua fasilitas terkenal di Singapura – di rumah sakit  bergengsi yakni  <a title="Cari Kami" href="{{ url('untuk-klien/kontak-kami') }}">Gleneagles Medical Centre</a> dan <a title="Cari Kami" href="{{ url('untuk-klien/kontak-kami') }}">Rumah Sakit Mount Elizabeth Novena</a> yang baru diresmikan. StemCord merupakan satu-satunya bank darah tali pusat di Singapura dengan dua laboratorium terpisah. Laboratorium ini secara khusus dilengkapi dan didedikasikan untuk pemrosesan dan penyimpanan sel punca.</p>

<p>Dapat dipastikan bahwa StemCord menerapkan standar tertinggi terhadap pemrosesan dan kualitas kontrol dalam menjaga viabilitas sel agar dapat digunakan untuk transplantasi.</p>

<ul class="clearfix">
	<li class="col-one-third">
<div class="facilities-table-header left-rounded bg-darkblue">
<h3>Prosedur<br/>StemCord</h3>
</div>
<div class="facilities-table-fill bg-brightblue">
<div class="facilities-table-fill-element"><img alt="" src="http://www.stemcord.com/wp-content/uploads/2013/04/tick.png" /></div>
</div></li>
	<li class="col-two-thirds">
<div class="facilities-table-header right-rounded bg-darkblue">
<h3>Prosedur Yang Direkomendasikan untuk Penyimpanan Darah Tali Pusat</h3>
</div>
<div class="facilities-table-content bg-lightgray">
<ul class="multiline-list bg-lightgray">
	<li class="icon_small_arrow right_black">Darah Tali Pusat harus sudah diproses dan dibekukan dalam waktu 48 jam setelah diambil</li>
	<li class="icon_small_arrow right_black">Diikuti oleh proses pembekuan dan penyimpanan yang memenuhi standar</li>
	<li class="icon_small_arrow right_black">Unit darah tali pusat harus disimpan dalam nitrogen cair atau pada temperatur yang sepadan dengan nitrogen cair</li>
</ul>
</div></li>
</ul>
<ul class="clearfix">
	<li class="col-one-third">
<div class="facilities-table-header bg-darkblue">
<h3>StemCord</h3>
</div>
<div class="facilities-table-fill bg-brightblue">
<div class="facilities-table-fill-element">

<img alt="" src="http://www.stemcord.com/wp-content/uploads/2013/04/tick.png" />

<p>2 tabung darah ibu akan diambil dan diuji.</p>

</div>
</div></li>
	<li class="col-two-thirds">
<div class="facilities-table-header bg-darkblue">
<h3>Test Laboratorium yang diperlukan</h3>
</div>
<div class="facilities-table-content bg-lightgray">
<span>Darah Ibu untuk Penyakit-Penyakit Menular:</span><ul class="list bg-lightgray">
	<li class="icon_small_arrow right_black">HIV1/2</li>
	<li class="icon_small_arrow right_black">VDRL</li>
	<li class="icon_small_arrow right_black">HBsAG</li>
	<li class="icon_small_arrow right_black">HCV</li>
	<li class="icon_small_arrow right_black">CMV (Cytomegalovirus)</li>
	<li class="icon_small_arrow right_black">HTLV I/I (Human T-Lymphotropic Virus)</li>
</ul>
</div></li>
</ul>
<ul class="clearfix">
	<li class="col-one-third">
<div class="facilities-table-fill bg-brightblue">
<div class="facilities-table-fill-element"><img alt="" src="http://www.stemcord.com/wp-content/uploads/2013/04/tick.png" /></div>
</div></li>
	<li class="col-two-thirds">
<div class="facilities-table-content bg-lightgray">
<span>Darah Tali Pusat:</span><ul class="list bg-lightgray">
	<li class="icon_small_arrow right_black">Pre &amp; Post Nucleated Cell Count</li>
	<li class="icon_small_arrow right_black">Cell Viability</li>
	<li class="icon_small_arrow right_black">ABO &amp; Rh</li>
	<li class="icon_small_arrow right_black">CD34</li>
	<li class="icon_small_arrow right_black">Bacteria Culture</li>
	<li class="icon_small_arrow right_black">Fungal Culture</li>
</ul>
</div></li>
</ul>									
{% endblock %}