{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Layanan kami</h2>
						<p><img width="630" height="330" src="{{ url('img/stemcord-our_services.jpg') }}" class="attachment-post-thumbnail wp-post-image" alt="Layanan {{ companyName }}" /></p>
						<p>StemCord adalah bank darah tali pusat yang paling kokoh di Singapura, yang secara khusus menangani Pengumpulan darah tali pusat, Pemrosesan, Penyimpanan dan Pengeluaran (release).</p>

<p>Sementara Laboratorium StemCord berada di Singapura, kami memiliki kantor perwakilan di negara - negara berkembang, kami melayani pengambilan darah tali pusat di negara kawasan Asia Pasifik lainnya, dengan syarat dan ketentuan berlaku.</p>

<p>Kami percaya bahwa sel punca akan sangat berguna di masa mendatang, dan perusahaan ini kuat secara financial dan tetap eksis di masa depan.</p>

<p>Untuk melindungi kepentingan klien, kami tidak ikut dalam kegiatan penelitian dan pengembangan yang beresiko secara financial, demi melindungi integritas dan keutuhan perusahaan ini.</p>

<p>Sebagai bagian dari komitmen kami untuk menyelamatkan kehidupan, kami menyediakan jasa pengambilan dan pengiriman sel punca untuk tujuan transplantasi di Singapura, tanpa biaya apapun. </p>

<p>Dengan memilih Kami sebagai bank darah tali pusat anak Anda akan memberikan ketenangan pikiran karena kami akan selalu hadir di setiap langkah Anda, sampai ke masa depan.</p>

<p>Untuk informasi lebih lanjut, hubungi kami di <a href="tel:{{ phoneCall }}"><span class="lightblue">{{ phoneSimple }}</span></a>.</p>

<span class="darkblue"><i>Providing you with Security, Experience, Expertise &amp; Quality.</i></span>									
					
{% endblock %}