{% extends "layouts/template.phtml" %}
{% block content %}
		
			 	
					<h2 class="box_header">Pendiri</h2>
						<ul class="gallery_item_details_list clearfix">
	<li id="gallery-details-1" class="gallery_item_details clearfix page_margin_top"><div class="columns no_width"><div class="column_left"><div class="details_box">
<div class="founder-intro clearfix">
	<div class="founder-intro-image">
		<img src="{{ url('img/dr_teo_cheng_peng.jpg') }}" width="102" height="144" title="Dr Teo Cheng Peng" align="left" />
	</div>
	<div class="founder-intro-text">
		<h2>Dr Teo Cheng Peng</h2>
		<span class="darkblue"><strong>Ketua / Direktur Medis dan Co -Founder,<br />
		StemCord Pte Ltd</strong><br />
		Konsultan Hematologi & MBBS Dokter (Singapura), <br />
		M.Med (Internis) FAMS (Hematologi)</span>
	</div>
</div>

<div class="founder-profile clearfix">
<p>DrTeo Cheng Peng, lahir tahun 1959, sekolah di Kuala Lumpur. Mendapat pengakuan atas hasil akademik yang sangat baik di GCE 'A' Ujian Tingkat dan kegiatan ekstrakurikuler, ia dianugerahi Beasiswa Komisi Pelayanan Publik oleh Pemerintah Singapura untuk belajar Kedokteran di National University of Singapura. Lulus  Sarjana Kedokteran dan Bedah pada tahun 1984.</p>
<p>Setelah menyelesaikan magang pada tahun 1985, ia memutuskan untuk mengejar pelatihan pascasarjana di Internal Medicine dan menjadi residen di Departemen Kedokteran, RS National University. Menyelesaikan residensi dan mendapat Master of Medicine ( Internal Medicine ) pada tahun 1987. Tetap di Departemen untuk mengikuti pendidikan lanjutan di Hematologi -Onkologi. Sebagai penghargaan atas prestasinya, ia dianugerahi beasiswa lain untuk melatih di Royal Marsden Hospital, Cancer Centre terkemuka di Inggris. Terlibat dalam Program transplantasi sumsum tulang dan sel punca perifer  untuk pengobatan berbagai keganasan.</p>
<p>Setelah kembali ke Singapura, ia mengembangkan Program Transplantasi Sumsum Tulang dan Sel punca Perifer di RS National University. Merupakan Principal Dokter yang bertugas dan bertanggung jawab dari pasien pertama yang menjalani transplantasi sumsum tulang di Rumah Sakit National University. Mendapat anugerah  dana besar bagi upaya penelitian oleh Dewan totalisasi Singapura. Dan diakui sebagai Fellow of the Academy of Medicine, Singapura, pada tahun 1993.</p>
<p>Pada tahun 1995, DrTeo direkrut sebagai Konsultan, untuk memimpin Program Transplantasi Sumsum tulang dan sel punca di Departemen Onkologi, Rumah Sakit Umum Singapura (General Hospital). Dari tahun 1995 sampai 1997, memimpin
tim untuk transplantasi lebih dari 50 pasien dengan berbagai kanker, termasuk kanker payudara, limfoma, multiple myeloma, penyakit Hodgkin, leukemia, sarcoma dan kanker nasofaring. Sebagai penghargaan atas upaya penelitian yang dilakukan, dr. Teo dianugerahi dana besar lain oleh Dewan Penelitian Medis Nasional.
</p>
<p>DrTeo secara luas dipublikasikan di berbagai jurnal kedokteran dan berpartisipasi di berbagai konferensi internasional. Saat ini bekerja di Parkway Cancer Centre di RS Gleneagles, dan terus mengembangkan program Transplantasi Sel Punca di sana.</p>
</div>

	<ul class="controls page_margin_top"><li><a href="#gallery-details-close" class="close"></a></li><li><a href="#gallery-details-3" class="prev icon_small_arrow left_black"></a></li><li><a href="#gallery-details-2" class="next icon_small_arrow right_black"></a></li></ul></div></div></div></li>

	<li id="gallery-details-2" class="gallery_item_details clearfix page_margin_top"><div class="columns no_width"><div class="column_left"><div class="details_box">
<div class="founder-intro clearfix">
	<div class="founder-intro-image">
		<img src="{{ url('img/dr_ang_peng_tiam.jpg') }}" width="102" height="144" title="Dr Ang Peng Tiam" />
	</div>
	<div class="founder-intro-text">
		<h2>Dr Ang Peng Tiam</h2>
		<span class="darkblue"><strong>Direktur dan Co -Founder,<br />
		StemCord Pte Ltd</strong><br />
		Konsultan Onkologi Medis & MBBS Dokter (Singapore),<br />
		M.Med (Internal Medicine) MRCP (United Kingdom ),<br />
		FRCP (Edinburgh) FRCP (London),<br />
		FAMS (Onkologis) FACP (USA)</span>
	</div>
</div>

<div class="founder-profile clearfix">
<p>DrAngPengTiam, lahir 1958, bersekolah di Anglo-Chinese School. Sebagai penghargaan atas prestasi akademik dan ekstra kurikuler, ia dianugerahi beasiswa Presiden pada tahun 1977 untuk belajar Kedokteran di National University di Singapura. </p>
<p>Lulus Sarjana Kedokteran dan Bedah tahun 1982, kemudian melakukan residensi di bagian Interna dan mendapat Master of Medicine ( Internist )  tahun 1986. Mendapat Medali Emas Prof Sir Gordon Arthur Ransome  untuk menjadi kandidat teratas dalam Pemeriksaan klinis. Pada tahun yang sama, ia melewati ujian keanggotaan dan diakui sebagai Anggota Royal College of Physicians (Inggris).</p>
<p>Menyadari kebutuhan akan ahli onkologi medis di Singapura, Pemerintah Singapura memberikan  beasiswa HMDP untuk pelatihan lanjutan di Onkologi Medis di MD Anderson Cancer Institute, Houston, Texas. Dia melanjutkan untuk tahun keduanya di bagian Onkologi Stanford University Medical Centre.</p>
<p>Setelah menyelesaikan pelatihan di Onkologi Medis, Dr Ang ditinjuk menjadi Kepala pendiri Departemen Onkologi Medis di RS Umum Singapura (SGH) pada tahun 1991. Dia juga menjabat sebagai Direktur di Pusat Onkologi dan Clinical Associate Professor di Fakultas Kedokteran, National University of Singapore.</p>
<p>Mendapatkan Fellow of the Academy of Singapore pada tahun 1990, Fellow dari American College of Physicians pada tahun 1993, Fellow dari Royal College of Physicians (Edinburgh) pada tahun 1995, dan Fellow of the Royal College of Physicians (London) pada tahun 1997. Dr. Ang juga merupakah anggota Dewan-bersertifikat dari Masyarakat Eropa Onkologi Medis, Masyarakat Amerika Onkologi Klinis dan anggota Masyarakat Hematologi International. Juga sebagai Presiden Masyarakat Onkologi di Singapura.</p>
<p>Saat ini bekerja sebagai Konsultan Senior Onkologi Medis di Parkway Cancer Centre di Rumah Sakit Mount Elizabeth, selain terus melayani sebagai Konsultan Tamu di RS Umum Singapura (SGH). Dr. Ang Peng Tiam tertarik  dalam penelitian dan telah menerbitkan  lebih dari 100 makalah dan abstrak. Mendapat anugerah National Science Award Singapura pada tahun 1996 untuk kontribusinya yang luar biasa di bidang Penilitian Medis.</p>
</div>
	<ul class="controls page_margin_top"><li><a href="#gallery-details-close" class="close"></a></li><li><a href="#gallery-details-1" class="prev icon_small_arrow left_black"></a></li><li><a href="#gallery-details-3" class="next icon_small_arrow right_black"></a></li></ul></div></div></div></li>

	<li id="gallery-details-3" class="gallery_item_details clearfix page_margin_top"><div class="columns no_width"><div class="column_left"><div class="details_box">

<div class="founder-intro clearfix">
	<div class="founder-intro-image">
		<img src="{{ url('img/dr_leong_see_odd.jpg') }}" width="102" height="144" title="Dr Leong See Odd" align="left" />
	</div>
	<div class="founder-intro-text">
		<h2>Dr Leong See Odd</h2>
		<span class="darkblue"><strong>Chief Executive Officer and Co-Founder,<br />
		StemCord Pte Ltd</strong><br />
		MBBS (Singapore), M.Med (Internal Medicine) MRCP (UK),<br />
		FAMS FRCP (EDIN)</span>
	</div>
</div>

<div class="founder-profile clearfix">
<p>Dr Leong See Odd, lahir pada tahun 1961, menempuh pendidikan di Raffles Institution, melanjutkan studi Kedokteran di Universitas Nasional Singapura.
Lulus Sarjana Kedokteran dan Bedah pada tahun 1986.
</p>
<p>Setelah selesai magang dan Layanan Nasional, memutuskan untuk mengejar pelatihan pascasarjana di bidang Penyakit Dalam (interna) dan menjalankan residensi di Departemen Kedokteran (Interna) tahun 1991. Pada tahun yang sama, ia melewati ujian keanggotaan dan diterima sebagai Anggota Royal College of Physicians (Inggris).</p>
<p>Melanjutkan di Departemen Kedokteran, National University Hospital, ia mengejar pelatihan lanjutan di bidang ginjal. Sebagai penghargaan atas prestasinya, ia dianugerahi beasiswa HMDP untuk mendapat pelatihan di RS Guy, sebuah Pusat Ginjal terkemuka di Inggris.</p>
<p>Diakui sebagai Fellow dari Academy of Medicine of Singapore pada tahun 1996. Dr Leong telah banyak mempublikasikan tulisan  di banyak peer–review jurnal  dan berpartisipasi dalam berbagai konferensi internasional. Saat ini bekerja sebagai dokter ahli ginjal  di RS Gleneagles, Singapura, dan terus melayani sebagai Konsultan Tamu di Rumah Sakit Tan Tock Seng.  Selain itu aktif sebagai dokter yang menangani banyak pusat-pusat cuci darah (dialysis) di Singapura.</p>
</div>
	<ul class="controls page_margin_top"><li><a href="#gallery-details-close" class="close"></a></li><li><a href="#gallery-details-2" class="prev icon_small_arrow left_black"></a></li><li><a href="#gallery-details-1" class="next icon_small_arrow right_black"></a></li></ul></div></div></div></li>

</ul>

<div class="gallery-hide">
<p>Sangatlah penting untuk mengenal perusahaan yang akan menyimpan darah tali pusat anak Anda. Bagi StemCord, para ahli medis yang ada di balik perusahaan ini menunjukan standar tertinggi terhadap kualitas penyimpanan darah tali pusat.Para pendiri StemCord adalah dokter ahli kanker, ahli darah, dan ahli ginjal terkenal yang memiliki kontribusi penting dalam program transplantasi sel punca sum-sum tulang dan darah tepi di Singapura. </p>

<p>
<img class="wp-post-image" align="middle" width="630" height="360" alt="StemCord Pendiri" src="{{ url('img/pendiri-stemcord.jpg') }}" />
</p>

<h3 class="page_margin_top">Pendiri StemCord</h3>
<p>
<a href="/tentang-kami/pendiri/#gallery-details-1" alt="Dr Teo Cheng Peng">Dr Teo Cheng Peng</a>, Chairman/Medical Director (atas, kanan)<br />
<a href="/tentang-kami/pendiri/#gallery-details-2" alt="Dr Ang Peng Tiam">Dr Ang Peng Tiam</a>, Director (atas, tengah)<br />
<a href="/tentang-kami/pendiri/#gallery-details-3" alt="Dr Leong See Odd">Dr Leong See Odd</a>, Chief Executive Officer (atas, kiri)<br />
</p>

<p>Mereka melihat banyak pasien kanker yang membutuhkan transplantasi sel punca tapi kemudian putus asa karena ketidak tersediaan pilihan ini. Oleh karena itu, mereka memutuskan bahwa bank darah tali pusat akan menyediakan suatu bentuk asuransi biologis bagi pasien yang mengidap kanker. Mereka mendirikan StemCord pada tahun 2002 dengan komitmen untuk menyediakan layanan yang terjangkau, profesional, dan dapat diAndalkan untuk membantu masyarakat mengetahui lebih lanjut mengenai sel punca dan memberikan kesempatan untuk menyimpan darah tali pusat yang berguna bagi generasi selanjutnya.</p>

<p>Sebagai tambahan, para pendiri kami memutuskan beberapa langkah dengan tujuan memaksimalkan potensi darah taIi pusat untuk penggunaan lebih dari sekali terapi. Di StemCord, darah tali pusat akan disimpan dalam beberapa kantong darah (multiple cryo unit). Dengan menyimpan darah tali pusat dalam beberapa cryo units ini, membuat Anda dapat menggunakan darah tali pusat sesuai dengan kebutuhan. Hal ini dikarenakan jika sekali darah tali pusat dicairkan maka darah tersebut tidak bisa dibekukan kembali (re-frozen ). Selain hal diatas, penyimpanan darah tali pusat dalam beberapa cryo units ini akan menyimpan darah tali pusat bayi Anda di 2 lokasi terpisah sebagai tambahan perlindungan gAnda dan dan tentunya ketenangan atas penyimpanan yang dilakukan. Sesuai dengan misi Kami, StemCord bertujuan untuk menyediakan Harapan Bagi Masa Depan.</p>

</div>									
{% endblock %}