{% extends "layouts/template.phtml" %}
{% block content %}
<h2 class="box_header">Sejarah</h2>
						<ul class="gallery_item_details_list clearfix">
	<li id="gallery-details-1" class="gallery_item_details clearfix page_margin_top"><div class="columns no_width"><div class="column_left"><div class="details_box">
		<h3>Tribute to Women</h3>
		<ul class="gallery gallery_2_columns_sidebar isotope">
			<li class="gallery_box isotope-item" id="gallery-item-1"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/TtW1_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/TtW1.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-2"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/TtW2_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/TtW2.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-3"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/TtW3_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/TtW3.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-4"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/TtW4_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/TtW4.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-5"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/TtW5_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/TtW5.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-6"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/TtW6_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/TtW6.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-7"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/TtW7_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/TtW7.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-8"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/TtW8_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/TtW8.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-9"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/TtW9_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/TtW9.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-10"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/TtW10_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/TtW10.jpg" class="fancybox open_lightbox"></a></li></ul></li>
		</ul>
	<ul class="controls page_margin_top"><li><a href="#gallery-details-close" class="close"></a></li></ul></div></div></div></li>
	<li id="gallery-details-2" class="gallery_item_details clearfix page_margin_top"><div class="columns no_width"><div class="column_left"><div class="details_box">
		<h3>BabyCare Festival 2007</h3>
		<ul class="gallery gallery_2_columns_sidebar isotope">
			<li class="gallery_box isotope-item" id="gallery-item-11"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest1_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest1.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-12"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest2_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest2.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-13"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest3_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest3.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-14"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest4_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest4.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-15"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest5_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest5.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-16"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest6_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest6.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-17"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest7_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest7.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-18"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest8_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest8.jpg" class="fancybox open_lightbox"></a></li></ul></li>
			<li class="gallery_box isotope-item" id="gallery-item-19"><img src="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest9_thumb.jpg" /><ul class="controls"><li><a href="http://www.stemcord.com/wp-content/uploads/2013/04/babycarefest9.jpg" class="fancybox open_lightbox"></a></li></ul></li>
		</ul>
	<ul class="controls page_margin_top"><li><a href="#gallery-details-close" class="close"></a></li></ul></div></div></div></li>
	<li id="gallery-details-3" class="gallery_item_details clearfix page_margin_top"><div class="columns no_width"><div class="column_left"><img class="gallery-details-feature" src="/wp-content/uploads/2013/04/ten_thousandth_customer.jpg" /></div><div class="column_right"><div class="details_box">
		<h3>10,000th Customer</h3>
<p>Mrs Heng Koon Gek (centre), who became StemCord&#8217;s ten-thousandth customer of StemCord on 3 March 2007, with Dr Ang Peng Tiam, Director and Co-Founder of StemCord (left) and Dr Leong See Odd, Chief Executive Officer and Co-Founder of StemCord (right).</p>
	<ul class="controls page_margin_top"><li><a href="#gallery-details-close" class="close"></a></li></ul></div></div></div></li>

</ul>

<ul class="items_list page_margin_top clearfix">

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2002</span></div>
	<div class="right" style="float:left;width:85%;">
Bank darah tali pusat pertama yang mendapat lisensi oleh Kementrian Kesehatan Singapura, dan memulai hari pertama beroperasi di hari yang sama
	</div></li>

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2003</span></div>
	<div class="right" style="float:left;width:85%;">
Menyimpan 800 sampel darah tali pusat dalam tahun pertama
	</div></li>

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2003</span></div>
	<div class="right" style="float:left;width:85%;">
Mengembangkan basis operasi di tingkat regional dengan berdirinya StemCord Indonesia dan StemCord Filipina
	</div></li>

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2004</span></div>
	<div class="right" style="float:left;width:85%;">
Berdirinya StemCord Brunei
	</div></li>

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2006</span></div>
	<div class="right" style="float:left;width:85%;">
Roadshow <a href="#gallery-details-1">Tribute to Women</a> di Suntec City dalam rangka ulang tahun ke-5 StemCord
	</div></li>

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2007</span></div>
	<div class="right" style="float:left;width:85%;">
Registrasi <a href="#gallery-details-3">pelanggan StemCord ke 10.000</a>, mengukuhkan StemCord sebagai bank darah tli pusat terbesar di Singapura
	</div></li>

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2007</span></div>
	<div class="right" style="float:left;width:85%;">
Sebagai yang pertama kali melakukan penyimpanan di 2 lokasi terpisah di Singapura
	</div></li>

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2007</span></div>
	<div class="right" style="float:left;width:85%;">
<a href="#gallery-details-2">BabyCare Festival 2007</a>
	</div></li>

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2008</span></div>
	<div class="right" style="float:left;width:85%;">
Peluncuran StemShield  – asuransi medis bagi klien StemCord yang dapat menggantikan biaya transplantasi sel punca
	</div></li>

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2009</span></div>
	<div class="right" style="float:left;width:85%;">
Dalam proses untuk mendapat Akreditasi FACT, tim pengawas FACT melakukan pemeriksaan awal dengan memeriksa semua aspek kualitas dari pengelolaan laboratorium termasuk pengumpulan, pemrosesan, penyimpanan, transportasi darah tali pusat serta administrasinya 
	</div></li>

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2009</span></div>
	<div class="right" style="float:left;width:85%;">
Registrasi pelanggan StemCord ke 20.000
	</div></li>

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2011</span></div>
	<div class="right" style="float:left;width:85%;">
Bank darah tali pusat pertama di Asia Tenggara yang <a href="{{ url('perbedaan-stemcord/fact-netcord-accreditation') }}" alt="FACT-NetCord Accreditation">mendapat Akreditasi</a> yaitu <a href="http://www.factwebsite.org/" target="_blank">FACT-NetCord International Standards</a> untuk Pengumpulan darah tali pusat, Pemrosesan, Pengujian, Penyimpanan, Seleksi, dan Pengeluaran (Release) unit darah tali pusat autolog	
	</div></li>

	<li class="clearfix"><div class="left" style="float:left;width:10%;margin-right:5%;"><span class="lightblue">2012</span></div>
	<div class="right" style="float:left;width:85%;">
Telah memproses dan menyimpan lebih dari 30,000 unit darah tali pusat di laboratorium khusus dan fasilitas penyimpanan milik StemCord sendiri
	</div></li>

</ul>
<div class="disclaimer"><p>* Dahulu website <a href="http://www.stemcord.co.id">Stemcord Indonesia Lama</a> adalah berakhiran co.id sekarang terbaru berakhiran <strong>.co</strong></p></div>									
{% endblock %}