{% include "partials/header.phtml" %}

<!--==============================-->
<div class="site_container narrow topborder"> <!-- remove narrow class for wide screen -->

<div class="sc_page relative noborder">

<!-- The Loop -->

<!--========== Content ==========-->
	<div class="page_layout page_margin_top clearfix">
	
	<div class="page_header clearfix">
		<div class="page_header_left">
			<!-- Breadcrumbs -->
			<ul class="bread_crumb"><li><a href="http://www.stemcord.com" title="Home">Home</a></li><li class="separator icon_small_arrow right_gray">&nbsp;</li><li><a href="http://www.stemcord.com/about-us/">About Us</a></li><li class="separator icon_small_arrow right_gray">&nbsp;</li><li>About StemCord</li>		</div>
	</div>

			<div class="page_left page_margin_top">
		
			 	
					<h2 class="box_header">Tentang StemCord</h2>
						<div class="video-container"><iframe width="640" height="360" src="//www.youtube.com/embed/66mh2OQXcNU?feature=player_embedded" frameborder="0" allowfullscreen></iframe></div>
<p>StemCord <a href="/about-us/our-founders" target="_blank" alt="Our Founders">didirikan dan dikelola oleh para Ahli Medis terkemuka</a> dengan tujuan memberi harapan akan masa depan. Sejak awal, StemCord terus menjaga konsistensi visi dan misi yaitu:
</p>
<ul class="multiline-list clearfix">
	<li class="icon_small_arrow right_lightblue">
Menyediakan layanan yang terjangkau, profesional dan dapat diAndalkan bagi setiap keluarga untuk menyimpan darah tali pusat anak mereka
	</li>
	<li class="icon_small_arrow right_lightblue">
Mem beri informasi yang jelas mengenai nilai dari sel punca dalam darah tali pusat
	</li>
	<li class="icon_small_arrow right_lightblue">
Memberi mereka pilihan pengobatan tambahan untuk mengobati penyakit di masa mendatang
	</li>
</ul>

<h3 class="page_margin_top">Bank Darah Tali Pusat Swasta yang pertama di Singapore</h3>
<p>StemCord adalah Bank Darah Tali Pusat Swasta yang pertama kali mendapatkan izin dari Departemen Kesehatan Singapura. Sejak hari pertama beroperasi, 6 Maret 2002, StemCord membantu masyarakat mengetahui lebih lanjut mengenai sel punca dan memberikan kesempatan untuk melakukan asuransi biologis yang berguna bagi generasi selanjutnya.</p>

<h3 class="page_margin_top">Standar Kualitas Kontrol yang Tertinggi</h3>
<p>StemCord terus menjaga lebih dari 25,000 sampel darah tali pusat  dengan stAndar kualitas kontrol tertinggi. StemCord adalah bank darah tali pusat pertama di Asia Tenggara dan satu-satunya di Singapura yang mendapat Akreditasi <a href="/stemcord/fact-netcord-accreditation" target="_blank" alt="FACT-NetCord Accreditation">FACT-NetCord</a> (Foundation for the Accreditation of Cellular Therapy and NetCord).</p>

<p>FACT-NetCord adalah suatu Badan Akreditasi International yang paling bergengsi yang secara khusus menangani Bank Darah Tali Pusat untuk Pengumpulan darah tali pusat, Pemrosesan, Pengujian, Penyimpanan, Seleksi dan Pengeluaran (release)</p>

<h3 class="page_margin_top">Satu-satunya Bank Darah Tali Pusat  yang Terbesar, Kokoh dan Terpecaya</h3>
<p>Dalam tahun pertama beroperasi, StemCord mengumpulkan 800 sampel  darah tali pusat. Dan saat ini, lebih dari 25,000 sampel darah tali pusat telah disimpan di laboratorium penyimpanan kami. StemCord berdiri sebagai bank darah tali pusat swasta paling kokoh dan terbesar di Singapura.</p>

<p>StemCord berpusat di Singapura dengan kantor-kantor cabang di Brunei, Indonesia, Filipina dan Vietnam. Dengan memilih StemCord sebagai bank penyimpanan darah tali pusat, Anda yakin telah memilih partner terpercaya yang menerapkan stAndar tertinggi terhadap kualitas kontrol dalam menjaga viabilitas sel yang Anda percayakan kepada kami. </p>									
					
		
		</div> <!-- page_left -->

<!-- End The Loop -->

<!--==============================-->
 
<!--========== Sidebar ==========-->
<div class="page_right page_margin_top">
	<div id="child-page-widget"><ul class="child-widget-list">
		<li class="child-widget-list-item current"><div class="child-widget-list-arrow"></div><span>Tentang StemCord</span><div class="child-widget-list-separator"></div></li>
		<li class="child-widget-list-item"><a href="http://stemcord.co/tentang-kami/layanan-kami/" title="Layanan Kami">Layanan Kami</a><div class="child-widget-list-separator"></div></li>
		<li class="child-widget-list-item"><a href="http://stemcord.co/tentang-kami/pendiri/" title="Pendiri">Pendiri</a><div class="child-widget-list-separator"></div></li>
		<li class="child-widget-list-item"><a href="http://stemcord.co/tentang-kami/sejarah/" title="Sejarah">Sejarah</a><div class="child-widget-list-separator"></div></li>
		<li class="child-widget-list-item"><a href="http://stemcord.co/tentang-kami/akreditasi/" title="Akreditasi">Akreditasi</a><div class="child-widget-list-separator"></div></li>
		<li class="child-widget-list-item"><a href="http://stemcord.co/tentang-kami/fasilitas/" title="Fasilitas">Fasilitas</a><div class="child-widget-list-separator"></div></li>
		<li class="child-widget-list-item"><a href="http://stemcord.co/tentang-kami/video-kami/" title="Video Kami">Video Kami</a><div class="child-widget-list-separator"></div></li>
		<li class="child-widget-list-item"><a href="http://stemcord.co/tentang-kami/karir/" title="Karir">Karir</a><div class="child-widget-list-separator"></div></li>
	</ul></div><div class="separator-sidebar">&nbsp;</div>
	
<!--========== Home Boxes ==========-->
{% include "partials/sidehomebar.phtml" %}
<!--==============================--></div> <!-- page_right -->

{% include "partials/footer.phtml" %}