{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Video Kami</h2>
						<ul class="gallery_item_details_list clearfix">
	<li id="gallery-details-1" class="gallery_item_details page_margin_top clearfix"><div class="columns no_width"><div class="column_left"><div class="video-container"><iframe width="630" height="354" src="http://www.youtube.com/embed/qfJHUDrm9Sg?rel=0&wmode=transparent" frameborder="0" allowfullscreen></iframe></div></div><div class="column_right"><div class="details_box">
<h2>StemCord, Hope for the Future</h2>
<p>StemCord is Singapore’s most established private cord blood bank, specialising in the collection, processing, storage, and retrieval of cord blood stem cells.</p>
	<ul class="controls page_margin_top"><li><a href="#gallery-details-close" class="close"></a></li><li><a href="#gallery-details-2" class="next icon_small_arrow right_black"></a></li></ul></div></div></div></li>

	<li id="gallery-details-2" class="gallery_item_details page_margin_top clearfix"><div class="columns no_width"><div class="column_left"><div class="video-container"><iframe width="630" height="354" src="http://www.youtube.com/embed/O9NCCtRDFKw?rel=0&wmode=transparent" frameborder="0" allowfullscreen></iframe></div></div><div class="column_right"><div class="details_box">
<h2>Apa itu Sel Punca dan Kegunaannya</h2>
<p>Following the birth of a baby, the umbilical cord is usually discarded along with the placenta. However, it is now known that blood retrieved from the umbilical cord is a rich source of blood stem cells.</p>
	<ul class="controls page_margin_top"><li><a href="#gallery-details-close" class="close"></a></li><li><a href="#gallery-details-1" class="prev icon_small_arrow left_black"></a></li><li><a href="#gallery-details-3" class="next icon_small_arrow right_black"></a></li></ul></div></div></div></li>

	<li id="gallery-details-3" class="gallery_item_details page_margin_top clearfix"><div class="columns no_width"><div class="column_left"><div class="video-container"><iframe width="630" height="354" src="http://www.youtube.com/embed/weaqCzudNiI?rel=0&wmode=transparent" frameborder="0" allowfullscreen></iframe></div></div><div class="column_right"><div class="details_box">
<h2>Keuntungan StemCord</h2>
<p>From day one, StemCord was established to focus on one main objective &#8211; the processing and preservation of your baby&#8217;s precious cord blood stem cells. We understand that this is a long-term commitment and are dedicated to being your trusted cord blood bank, providing you with the best possible service, now and into the future.</p>
	<ul class="controls page_margin_top"><li><a href="#gallery-details-close" class="close"></a></li><li><a href="#gallery-details-2" class="prev icon_small_arrow left_black"></a></li><li><a href="#gallery-details-4" class="next icon_small_arrow right_black"></a></li></ul></div></div></div></li>

	<li id="gallery-details-4" class="gallery_item_details page_margin_top clearfix"><div class="columns no_width"><div class="column_left"><div class="video-container"><iframe width="630" height="354" src="http://www.youtube.com/embed/UUpe_iZVjcA?rel=0&wmode=transparent" frameborder="0" allowfullscreen></iframe></div></div><div class="column_right"><div class="details_box">
<h2>Prosedur Pengambilan Darah Tali Pusat</h2>
<p>StemCord is dedicated to maintaining the highest standards of quality control in the safe handling of your baby&#8217;s precious cord blood.</p>
	<ul class="controls page_margin_top"><li><a href="#gallery-details-close" class="close"></a></li><li><a href="#gallery-details-3" class="prev icon_small_arrow left_black"></a></li><li><a href="#gallery-details-5" class="next icon_small_arrow right_black"></a></li></ul></div></div></div></li>

	<li id="gallery-details-5" class="gallery_item_details page_margin_top clearfix"><div class="columns no_width"><div class="column_left"><div class="video-container"><iframe width="630" height="354" src="http://www.youtube.com/embed/aCRiL_2sQGQ?rel=0&wmode=transparent" frameborder="0" allowfullscreen></iframe></div></div><div class="column_right"><div class="details_box">
<h2>Transportasi & Pemrosesan Darah Tali Pusat</h2>
<p>Stem cells from the umbilical cord are young and healthy cells, and are better matches when used for transplants. More and more families have chosen to collect, process and store their baby&#8217;s cord blood.</p>
	<ul class="controls page_margin_top"><li><a href="#gallery-details-close" class="close"></a></li><li><a href="#gallery-details-4" class="prev icon_small_arrow left_black"></a></li><li><a href="#gallery-details-6" class="next icon_small_arrow right_black"></a></li></ul></div></div></div></li>

	<li id="gallery-details-6" class="gallery_item_details page_margin_top clearfix"><div class="columns no_width"><div class="column_left"><div class="video-container"><iframe width="630" height="354" src="http://www.youtube.com/embed/66mh2OQXcNU?rel=0&wmode=transparent" frameborder="0" allowfullscreen></iframe></div></div><div class="column_right"><div class="details_box">
<h2>Tentang StemCord</h2>
<p>StemCord is founded by renowned medical practitioners with the mission of bringing hope for the future.</p>
	<ul class="controls page_margin_top"><li><a href="#gallery-details-close" class="close"></a></li><li><a href="#gallery-details-5" class="prev icon_small_arrow left_black"></a></li></ul></div></div></div></li>

</ul>

<ul class="gallery gallery_2_columns_sidebar isotope">
	<li class="gallery_box isotope-item" id="gallery-item-1"><img src="http://img.youtube.com/vi/qfJHUDrm9Sg/0.jpg" /><div class="description"><h3>StemCord, Hope for the Future</h3></div><ul class="controls"><li><a href="#gallery-details-1" class="open_details"></a></li></ul></li>

	<li class="gallery_box isotope-item" id="gallery-item-2"><img src="http://img.youtube.com/vi/O9NCCtRDFKw/0.jpg" /><div class="description"><h3>What are Stem Cells and its uses</h3></div><ul class="controls"><li><a href="#gallery-details-2" class="open_details"></a></li></ul></li>

	<li class="gallery_box isotope-item" id="gallery-item-3"><img src="http://img.youtube.com/vi/weaqCzudNiI/0.jpg" /><div class="description"><h3>The StemCord Advantage</h3></div><ul class="controls"><li><a href="#gallery-details-3" class="open_details"></a></li></ul></li>

	<li class="gallery_box isotope-item" id="gallery-item-4"><img src="http://img.youtube.com/vi/UUpe_iZVjcA/0.jpg" /><div class="description"><h3>Cord Blood Banking Procedure</h3></div><ul class="controls"><li><a href="#gallery-details-4" class="open_details"></a></li></ul></li>

	<li class="gallery_box isotope-item" id="gallery-item-5"><img src="http://img.youtube.com/vi/aCRiL_2sQGQ/0.jpg" /><div class="description"><h3>Transportation &#038; Processing of Cord Blood</h3></div><ul class="controls"><li><a href="#gallery-details-5" class="open_details"></a></li></ul></li>

	<li class="gallery_box isotope-item" id="gallery-item-6"><img src="http://img.youtube.com/vi/66mh2OQXcNU/0.jpg" /><div class="description"><h3>About StemCord</h3></div><ul class="controls"><li><a href="#gallery-details-6" class="open_details"></a></li></ul></li>

</ul>
	{% endblock %}