
<h2>Penyerahan Dokumen: Ibu {{ name }}</h2>
<br/>
<p>Mohon dokumen atas nama berikut ini di-follow up:</p>
<br/>
<table>
	<tr>
		<td>SCP</td>
		<td>:</td>
		<td>{{ scp }}</td>
	</tr>
	<tr>
		<td>Nama</td>
		<td>:</td>
		<td>{{ name }}</td>
	</tr>
	<tr>
		<td>Email</td>
		<td>:</td>
		<td>{{ email }}</td>
	</tr>
	<tr>
		<td>Nomor Kontak</td>
		<td>:</td>
		<td>{{ phone }}</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
	<tr>
		<td>Nomor KTP</td>
		<td>:</td>
		<td>{{ mothersId }}</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
	<tr>
		<td>Keterangan</td>
		<td>:</td>
		<td>{{ notes }}</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
	<tr>
		<td>Lebih suka dihubungi via</td>
		<td>:</td>
		<td>{{ contactPreference }}</td>
	</tr>
</table>

<p>Terima kasih</p>
<br/>
<br/>
<p>[AUTO]Website Administrator</p>


