
<h2>Perbaharui Informasi oleh: Ibu {{ name }}</h2>
<br/>
<p>Mohon informasi terbaru dari nama berikut ini di-follow up:</p>
<br/>
<table>
	<tr>
		<td>Nomor SCP</td>
		<td>:</td>
		<td>{{ scp }}</td>
	</tr>
	<tr>
		<td>Nama Ibu (sesuai kontrak/Agreement)</td>
		<td>:</td>
		<td>{{ name }}</td>
	</tr>
	<tr>
		<td>Nomor Identifikasi Ibu (KTP)</td>
		<td>:</td>
		<td>{{ idNumber }}</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
	<tr>
		<td>Nomor HP saat ini</td>
		<td>:</td>
		<td>{{ phoneCurrent }}</td>
	</tr>
	<tr>
		<td>Nomor HP yang baru</td>
		<td>:</td>
		<td>{{ phoneNew }}</td>
	</tr>
	<tr>
		<td>Alamat Email saat ini</td>
		<td>:</td>
		<td>{{ emailCurrent }}</td>
	</tr>
	<tr>
		<td>Alamat Email baru</td>
		<td>:</td>
		<td>{{ emailNew }}</td>
	</tr>
	<tr>
		<td>Alamat surat menyurat saat ini</td>
		<td>:</td>
		<td>{{ mailingCurrent }}</td>
	</tr>
	<tr>
		<td>Alamat surat menyurat yang baru</td>
		<td>:</td>
		<td>{{ mailingNew }}</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
	<tr>
		<td>Tanggal Efektif Perubahan</td>
		<td>:</td>
		<td>{{ startDate }}</td>
	</tr>
	<tr>
		<td>Komentar</td>
		<td>:</td>
		<td>{{ comments }}</td>
	</tr>
	<tr>
		<td>Lebih suka dihubungi via</td>
		<td>:</td>
		<td>{{ contactPreference }}</td>
	</tr>
</table>

<p>Terima kasih</p>
<br/>
<br/>
<p>[AUTO]Website Administrator</p>


