
<h2>Permintaan Information Kit: Ibu {{ name }}</h2>
<br/>
<p>Mohon permintaan information kit atas nama berikut ini di-follow up:</p>
<br/>
<table>
	<tr>
		<td>Nama</td>
		<td>:</td>
		<td>{{ name }}</td>
	</tr>
	<tr>
		<td>Email</td>
		<td>:</td>
		<td>{{ email }}</td>
	</tr>
	<tr>
		<td>Nomor Kontak</td>
		<td>:</td>
		<td>{{ phone }}</td>
	</tr>
	<tr>
		<td>Waktu terbaik untuk di-telepon</td>
		<td>:</td>
		<td>{{ timeToPhone }}</td>
	</tr>
	<tr>
		<td>Alamat</td>
		<td>:</td>
		<td>{{ address }}</td>
	</tr>
	<tr>
		<td>Kodepos</td>
		<td>:</td>
		<td>{{ postalCode }}</td>
	</tr>
	<tr>
		<td>Negara</td>
		<td>:</td>
		<td>{{ country }}</td>
	</tr>
	<tr>
		<td>Rencana Tanggal Kelahiran</td>
		<td>:</td>
		<td>{{ birthDate }}</td>
	</tr>
	<tr>
		<td>Nama Dokter Kebidanan</td>
		<td>:</td>
		<td>{{ doctorName }}</td>
	</tr>
	<tr>
		<td>Referral</td>
		<td>:</td>
		<td>{{ referral }}</td>
	</tr>
	<tr>
		<td>Iklan</td>
		<td>:</td>
		<td>{{ ads }}</td>
	</tr>
	<tr>
		<td>Pertanyaan</td>
		<td>:</td>
		<td>{{ message }}</td>
	</tr>
	<tr>
		<td>Lebih suka dihubungi via</td>
		<td>:</td>
		<td>{{ contactPreference }}</td>
	</tr>
</table>

<p>Terima kasih</p>
<br/>
<br/>
<p>[AUTO]Website Administrator</p>

