
<h2>Teman Mereferensikan Teman (Friend Refer Friend): Ibu {{ name }}</h2>
<br/>
<p>Mohon informasi referensi teman berikut ini di-follow up:</p>
<br/>
<table>
	<tr>
		<td>Nomor SCP</td>
		<td>:</td>
		<td>{{ scpNo }}</td>
	</tr>
	<tr>
		<td>Nama Ibu (sesuai kontrak/agreement)</td>
		<td>:</td>
		<td>{{ motherName }}</td>
	</tr>
	<tr>
		<td>Nomor Identifikasi Ibu</td>
		<td>:</td>
		<td>{{ motherIc }}</td>
	</tr>
	<tr>
		<td>Nomor Handphone Ibu</td>
		<td>:</td>
		<td>{{ motherContact }}</td>
	</tr>
	<tr>
		<td>Alamat Email</td>
		<td>:</td>
		<td>{{ motherEmail }}</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
	<tr><td><strong>Teman 1</strong></td></tr>
	<tr>
		<td>Nama Teman</td>
		<td>:</td>
		<td>{{ nameFriend1 }}</td>
	</tr>
	<tr>
		<td>Alamat Email Teman</td>
		<td>:</td>
		<td>{{ emailFriend1 }}</td>
	</tr>
	<tr>
		<td>Telepon Teman</td>
		<td>:</td>
		<td>{{ contactFriend1 }}</td>
	</tr>
	<tr>
		<td>Rumah Sakit Teman</td>
		<td>:</td>
		<td>{{ hospitalFriend1 }}</td>
	</tr>
	{% if nameFriend2 is defined %}
	<tr><td>&nbsp;</td></tr>
	<tr><td><strong>Teman 2</strong></td></tr>
	<tr>
		<td>Nama Teman</td>
		<td>:</td>
		<td>{{ nameFriend2 }}</td>
	</tr>
	<tr>
		<td>Alamat Email Teman</td>
		<td>:</td>
		<td>{{ emailFriend2 }}</td>
	</tr>
	<tr>
		<td>Telepon Teman</td>
		<td>:</td>
		<td>{{ contactFriend2 }}</td>
	</tr>
	<tr>
		<td>Rumah Sakit Teman</td>
		<td>:</td>
		<td>{{ hospitalFriend2 }}</td>
	</tr>	
	{% endif %}
	{% if nameFriend3 is defined %}
	<tr><td>&nbsp;</td></tr>
	<tr><td><strong>Teman 3</strong></td></tr>
	<tr>
		<td>Nama Teman</td>
		<td>:</td>
		<td>{{ nameFriend3 }}</td>
	</tr>
	<tr>
		<td>Alamat Email Teman</td>
		<td>:</td>
		<td>{{ emailFriend3 }}</td>
	</tr>
	<tr>
		<td>Telepon Teman</td>
		<td>:</td>
		<td>{{ contactFriend3 }}</td>
	</tr>
	<tr>
		<td>Rumah Sakit Teman</td>
		<td>:</td>
		<td>{{ hospitalFriend3 }}</td>
	</tr>	
	{% endif %}
	{% if nameFriend4 is defined %}
	<tr><td>&nbsp;</td></tr>
	<tr><td><strong>Teman 4</strong></td></tr>
	<tr>
		<td>Nama Teman</td>
		<td>:</td>
		<td>{{ nameFriend4 }}</td>
	</tr>
	<tr>
		<td>Alamat Email Teman</td>
		<td>:</td>
		<td>{{ emailFriend4 }}</td>
	</tr>
	<tr>
		<td>Telepon Teman</td>
		<td>:</td>
		<td>{{ contactFriend4 }}</td>
	</tr>
	<tr>
		<td>Rumah Sakit Teman</td>
		<td>:</td>
		<td>{{ hospitalFriend4 }}</td>
	</tr>	
	{% endif %}
	<tr><td>&nbsp;</td></tr>
	<tr>
		<td>Memilih dihubungi dengan cara</td>
		<td>:</td>
		<td>{{ contactPreference }}</td>
	</tr>
</table>

<p>Terima kasih</p>
<br/>
<br/>
<p>[AUTO]Website Administrator</p>


