
<h2>Tanya Dokter oleh: {{ name }}</h2>
<br/>
<p>Mohon pertanyaan untuk Dokter atas nama berikut ini di-follow up:</p>
<br/>
<table>
	<tr>
		<td>Nama</td>
		<td>:</td>
		<td>{{ name }}</td>
	</tr>
	<tr>
		<td>Email</td>
		<td>:</td>
		<td>{{ email }}</td>
	</tr>
	<tr>
		<td>Nomor Kontak</td>
		<td>:</td>
		<td>{{ phone }}</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
	<tr>
		<td>Rencana Tanggal Kelahiran</td>
		<td>:</td>
		<td>{{ birthDate }}</td>
	</tr>
	<tr>
		<td>Rumah Sakit</td>
		<td>:</td>
		<td>{{ hospital }}</td>
	</tr>
	<tr>
		<td>Dokter/Bidan</td>
		<td>:</td>
		<td>{{ doctorName }}</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
	<tr>
		<td>Permohonan</td>
		<td>:</td>
		<td>{{ enquiry }}</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
	<tr>
		<td>Lebih suka dihubungi via</td>
		<td>:</td>
		<td>{{ contactPreference }}</td>
	</tr>
</table>

<p>Terima kasih</p>
<br/>
<br/>
<p>[AUTO]Website Administrator</p>


