<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{{ companyName }} | {{ title }}</title>
		<meta name="keywords" content="cord blood banking, {{ companyName }}, bank darah tali pusat" />
		<meta name="description" content="{{ metaDescription }}" />
		<meta name="robots" content="all" />
		{{ stylesheet_link('css/style/superfish.css') }}
		{{ stylesheet_link('css/style/jquery.qtip.css') }}
		{{ stylesheet_link('css/style/jquery-ui-1.9.2.custom.css') }}
		{{ stylesheet_link('css/styles.css?v=1.02') }}
		{{ stylesheet_link('css/responsive.css?v=1.02') }}

	</head>
	{{ content() }}
</html>
