<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{{ companyName }} | {{ title }}</title>
		<meta name="keywords" content="cord blood banking, {{ companyName }}, bank darah tali pusat" />
		<meta name="description" content="{{ metaDescription }}" />
		<meta name="robots" content="all" />
		{{ stylesheet_link('css/font.css') }}
		
		
		{{ stylesheet_link('css/style/reset.css') }}
		{{ stylesheet_link('css/style/superfish.css') }}
		{{ stylesheet_link('css/style/jquery.fancybox.css') }}
		{{ stylesheet_link('css/style/jquery.qtip.css') }}
		{{ stylesheet_link('css/style/jquery-ui-1.9.2.custom.css') }}
		
		{{ stylesheet_link('css/styles.css?v=1.02') }}
		{{ stylesheet_link('css/responsive.css?v=1.02') }}

		{{ javascript_include('js/jquery-1.8.3.min.js') }}
		{{ javascript_include('js/jquery-ui-1.9.2.custom.min.js') }}
		
		
		
		
		
		

       
	</head>
	
		
			{{ content() }}
		
	
</html>
