<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{{ companyName }} | {{ title }}</title>
		<meta name="keywords" content="{{ companyName }}, bank darah tali pusat, cord blood banking indonesia" />
		<meta name="description" content="{{ metaDescription }}" />
		<meta name="robots" content="all" />
		{{ stylesheet_link('css/style/superfish.css') }}
		{{ stylesheet_link('css/style/jquery.qtip.css') }}
		{{ stylesheet_link('css/style/jquery-ui-1.9.2.custom.css') }}
		{{ stylesheet_link('css/styles.css') }}
		{{ stylesheet_link('css/responsive.css') }}

		{% if putJavascriptAtTop == 'true' %}
		{{ javascript_include('js/jquery-1.8.3.min.js') }}
		{{ javascript_include('js/jquery-ui-1.9.2.custom.min.js') }}
		{% endif %}

	</head>
	{{ content() }}
</html>
