{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Buat Janji Appointment</h2>
                    {% if isSubmit %}
						<ul>

	<li id="gallery-details-1" class="gallery_item_details clearfix"><div class="columns no_width"><div class="column_left"><div class="details_box">


<br />
<p>Kepada Yth <strong>{{ name }}</strong>, Permintaan Appointment Anda sudah diterima.</p>
<p>Terima kasih telah mengirimkan permintaan informasi ini. Staff kami akan mengontak Anda dengan segera. Apabila ada yang ingin ditanyakan lebih lanjut silahkan hubungi {{ phoneFullTag }}.</p>
<br />
<p>Terima kasih</p>
<br />
<p>Salam,<br />
StemCord Indonesia</p>
        
    <ul class="controls page_margin_top"><li><a href="{{ url('untuk-klien/buat-janji') }}">Kembali ke halaman sebelumnya</a></li></ul></div></div></div></li>
</ul>
{% else %}
<div class="gallery-hide">

<p>Make an Appointment with us to find out more about Cord Blood Banking and our services.</p>

<p>Please complete the form below so we could better appoint a consultant to serve you. We shall be contacting you shortly to arrange for an appointment.</p>

<div class="wpcf7" id="wpcf7-f992-p993-o1">
<div class="screen-reader-response"></div>
<form action="{{ url('untuk-klien/buat-janji') }}" method="post" class="wpcf7-form wpcf7-acceptance-as-validation" novalidate="novalidate">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="992" />
<input type="hidden" name="_wpcf7_version" value="3.8.1" />
<input type="hidden" name="_wpcf7_locale" value="" />
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f992-p993-o1" />
<input type="hidden" name="_wpnonce" value="db285f9b0e" />
</div>
<div class="contact_form">
<div class="clearfix">
<div class="note">fields marked with * are mandatory</div>
<fieldset class="left">

    <label>Name *</label><div class="block">
        <span class="wpcf7-form-control-wrap appt-name"><input type="text" name="appt-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" id="appt-name" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>NRIC</label><div class="block">
        <span class="wpcf7-form-control-wrap appt-nric"><input type="text" name="appt-nric" value="" size="40" class="wpcf7-form-control wpcf7-text text_input" aria-invalid="false" /></span> 
    </div>

    <label>Contact Number *</label>
    <div class="block">
        <span class="wpcf7-form-control-wrap appt-contact-number"><input type="text" name="appt-contact-number" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span> 
    </div>

    <label>Email Address *</label>
    <div class="block">
        <span class="wpcf7-form-control-wrap appt-email"><input type="email" name="appt-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email text_input" aria-required="true" aria-invalid="false" /></span> 
    </div>

</fieldset>

<fieldset class="right">

    <label>Preferred Appointment Date *</label>
    <div class="block">
        <span class="wpcf7-form-control-wrap appt-preferred-date"><input type="text" name="appt-preferred-date" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required pick-date text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Expected Date of Delivery *</label>
    <div class="block">
        <span class="wpcf7-form-control-wrap appt-expected-date-of-delivery"><input type="text" name="appt-expected-date-of-delivery" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required pick-date text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Delivery Hospital *</label>
    <div class="block">
        <span class="wpcf7-form-control-wrap appt-delivery-hospital"><input type="text" name="appt-delivery-hospital" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Name of Gynaecologist *</label>
    <div class="block">
        <span class="wpcf7-form-control-wrap appt-gynaecologist"><input type="text" name="appt-gynaecologist" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>
</div>

<p class="submit-consent">By submitting this form, I accept and agree to be included in StemCord’s mailing list, and to be contacted by StemCord and partners for future communications.<br>
I prefer to be contacted by:
<span class="wpcf7-form-control-wrap contact-by"><span class="wpcf7-form-control wpcf7-checkbox wpcf7-validates-as-required"><span class="wpcf7-list-item first"><input type="checkbox" name="contact-by[]" value="Telephone" />&nbsp;<span class="wpcf7-list-item-label">Telephone</span></span><span class="wpcf7-list-item last"><input type="checkbox" name="contact-by[]" value="SMS" />&nbsp;<span class="wpcf7-list-item-label">SMS</span></span></span></span></p>

<p><input type="submit" value="Make an Appointment" class="wpcf7-form-control wpcf7-submit more blue" /></p>

</div><div class="wpcf7-response-output wpcf7-display-none"></div></form></div>

</div>
{% endif %} 																
{% endblock %}