{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Buat Enquiry</h2>
                    {% if isSubmit %}
						<ul>

	<li id="gallery-details-1" class="gallery_item_details clearfix"><div class="columns no_width"><div class="column_left"><div class="details_box">


<br />
<p>Dear <strong>{{ name }}</strong>, Permintaan Enquiry Anda sudah diterima.</p>
<p>Terima kasih telah mengirimkan permintaan informasi ini. Staff kami akan mengontak Anda dengan segera. Apabila ada yang ingin ditanyakan lebih lanjut silahkan hubungi {{ phoneFullTag }}.</p>
<br />
<p>Terima kasih</p>
<br />
<p>Salam,<br />
StemCord Indonesia</p>
        
    <ul class="controls page_margin_top"><li><a href="{{ url('untuk-klien/buat-enquiry') }}">Kembali ke halaman sebelumnya</a></li></ul></div></div></div></li>
</ul>
{% else %}
<div class="gallery-hide">

<p>Cukup masukan pertanyaan Anda dalam kotak di bawah dan kami akan merespon anda melalui email.</p>

<div class="wpcf7" id="wpcf7-f433-p436-o1">
<div class="screen-reader-response"></div>
<form action="{{ url('untuk-klien/buat-enquiry') }}" method="post" class="wpcf7-form wpcf7-acceptance-as-validation" novalidate="novalidate">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="433" />
<input type="hidden" name="_wpcf7_version" value="3.8.1" />
<input type="hidden" name="_wpcf7_locale" value="" />
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f433-p436-o1" />
<input type="hidden" name="_wpnonce" value="ba298f5097" />
</div>
<div class="contact_form">

<div class="clearfix">
<div class="note">Bagian  yang ditandai dengan * wajib diisi</div>
<fieldset class="left">

    <label>Nama *</label><div class="block">
        <span class="wpcf7-form-control-wrap ask-name"><input type="text" name="ask-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" id="ask-name" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Email *</label><div class="block">
        <span class="wpcf7-form-control-wrap ask-email"><input type="email" name="ask-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Nomor Kontak *</label><div class="block">
        <span class="wpcf7-form-control-wrap ask-contact-num"><input type="text" name="ask-contact-num" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>

<fieldset class="right">

    <label>Rencana melahirkan *</label><div class="block">
        <span class="wpcf7-form-control-wrap ask-expected-date-of-delivery"><input type="text" name="ask-expected-date-of-delivery" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required pick-date text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Rumah Sakit tempat melahirkan *</label><div class="block">
        <span class="wpcf7-form-control-wrap ask-hospital"><input type="text" name="ask-hospital" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Nama dokter kebidanan *</label><div class="block">
        <span class="wpcf7-form-control-wrap ask-gynaecologist"><input type="text" name="ask-gynaecologist" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>
</div>

<fieldset class="page_margin_top" style="clear:both;">

    <label>Subjek *</label><div class="block">
        <span class="wpcf7-form-control-wrap ask-subject"><select name="ask-subject" class="wpcf7-form-control wpcf7-select wpcf7-validates-as-required select-box" aria-required="true" aria-invalid="false"><option value="">---</option><option value="Registration">Registration</option><option value="Cord Blood Banking (Collection, Storage and Retrieval)">Cord Blood Banking (Collection, Storage and Retrieval)</option><option value="About StemCord">About StemCord</option><option value="Others">Others</option></select></span>
    </div>

    <label>Permohonan *</label><div class="block">
        <span class="wpcf7-form-control-wrap ask-enquiry"><textarea name="ask-enquiry" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false"></textarea></span>
    </div>

</fieldset>

<p class="submit-consent">Dengan meng-input form ini. Saya menerima dan setuju untuk disertakan dalam mailing list StemCord dan dihubungi oleh Stemcord dan rekanan untuk komunikasi lebih lanjut.<br>
Saya menyukai untuk dihubungi via:
<span class="wpcf7-form-control-wrap contact-by"><span class="wpcf7-form-control wpcf7-checkbox wpcf7-validates-as-required"><span class="wpcf7-list-item first"><input type="checkbox" name="contact-by[]" value="Telepon" />&nbsp;<span class="wpcf7-list-item-label">Telepon</span></span><span class="wpcf7-list-item last"><input type="checkbox" name="contact-by[]" value="SMS" />&nbsp;<span class="wpcf7-list-item-label">SMS</span></span></span></span></p>

<p><input type="submit" value="Kirim" class="wpcf7-form-control wpcf7-submit more blue" /></p>
</div><div class="wpcf7-response-output wpcf7-display-none"></div></form></div>

</div>
{% endif %} 								
{% endblock %}