{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Kontak Kami</h2>
						<h3 class="page_margin_top box_header">Sales &#038; Marketing Office</h3>
<p>Gleneagles Medical Centre<br />
6 Napier Road #02-13<br />
Singapore 258499<br />
Tel: (65) 6471 2002, Fax: (65) 6471 5255</p>

<p>Mount Elizabeth Novena Hospital<br />
38 Irrawaddy Road #01-15<br />
Singapore 329563<br />
Tel: (65) 6339 6018, Fax: (65) 6339 6 286</p>

<p>Email: <a href="mailto:customerservice@stemcord.com">customerservice@stemcord.com</a></p>

<h3 class="page_margin_top box_header">Billing Office</h3>
<p>89A Science Park Drive 1 #04-27/28<br />
The Rutherford<br />
Singapore 118261<br />
Tel: (65) 6777 5443, Fax: (65) 6774 4556<br />
Email: <a href="mailto:billing@stemcord.com">billing@stemcord.com</a></p>

<h3 class="page_margin_top box_header">Laboratories</h3>
<p>89A Science Park Drive 1 #04-27/28<br />
The Rutherford<br />
Singapore 118261<br />
<br />
41 Science Park Road #01-21<br />
The Gemini,<br />
Singapore 117610</p>

<h3 class="page_margin_top box_header">Regional Offices</h3>

<h4 class="page_margin_top">Indonesia</h4>
<p>PT. Putra Mas Indah<br />
Tamara Center, Suite #636<br />
Jl. Jend Sudirman Kav. 24<br />
Jakarta 12920, Indonesia<br />
Tel: (62) (21) 520 6555 / 520 6556, Fax: (62) (21) 520 6551<br />
Email: <a href="mailto:info@stemcord.com">info@stemcord.co</a><br />
Facebook: <a href="https://www.facebook.com/pages/Stemcord-Indonesia/149400268405542">Facebook Stemcord Indonesia</a><br />
Twitter: <a href="https://twitter.com/StemCord">Twitter Stemcord Indonesia</a><br />


<h4 class="page_margin_top">Philippines</h4>
<p>StemCord Phillipines, Inc<br />
Suite 601 (South) Cathedral Heights Bldg. Complex<br />
St. Luke&#8217;s Medical Center<br />
279 E. Rodriguez Sr. Blvd.<br />
Quezon City 1102, Philippines<br />
Trunk Lines: (632) 723 0101 ext 2601
<br />Direct Line: (632) 723 2333, Tele-fax: (632) 727 2303<br />
Email: <a href="mailto:stemcord@pldtdsl.net">stemcord@pldtdsl.net</a><br />
Ms Phoebe Tsai-Te, Chief Operating Officer<br />
Email: <a href="mailto:phoebe.coo@stemcord.com.ph">phoebe.coo@stemcord.com.ph</a></p>
Website: <a href="http://www.stemcord.com.ph">http://www.stemcord.com.ph</a></p>

<h3 class="page_margin_top box_header">Enquiries</h3>
<h4 class="page_margin_top">For Media Enquiries</h4>
<p>Please contact Valerie Wong, General Manager<br />
Email: <a href="mailto:valerie@stemcord.com">valerie@stemcord.com</a></p>

<h4 class="page_margin_top">For Marketing Enquiries</h4>
<p>Please contact Katherine Ong, Sales &#038; Marketing Manager<br />
Email: <a href="mailto:katherineong@stemcord.com">katherineong@stemcord.com</a></p>

<p>To submit your enquiry online, please click <a href="{{ url('untuk-klien/buat-enquiry') }}">here</a>.</p>																
{% endblock %}