{% extends "layouts/template.phtml" %}
{% block content %}
					<h2 class="box_header">Tanya Dokter</h2>
						<p><img width="630" height="330" src="http://www.stemcord.com/wp-content/uploads/2013/08/drteo_banner1.jpg" class="attachment-post-thumbnail wp-post-image" alt="drteo_banner" /></p>

						<ul class="gallery_item_details_list clearfix">
{% if !isSubmit %}
	<li id="gallery-details-1" class="gallery_item_details clearfix"><div class="columns no_width"><div class="column_left"><div class="details_box">


<p>Kami ingin membantu Anda lebih lanjut tentang penyimpanan darah tali pusat, sel punca dan kondisi medis yang dapat mempengaruhi proses penyimpanan darah tali pusat. Di sini, kami telah menyediakan daftar pertanyaan yang umum ditanyakan oleh pasien  kepada <a href="{{ url('tentang-kami/pendiri') }}">Direktur Medis</a> kami di waktu yang lalu. Jika Anda memiliki pertanyaan, jangan ragu untuk mengisi <a href="#gallery-details-1">formulir</a> ini dan kami akan menjawab kepada Anda segera</p>

<p>Untuk pertanyaan umum, silakan tinggalkan pesan Anda <a href="{{ url('untuk-klien/buat-enquiry') }}" title="Buat permohonan">di sini</a> atau hubungi hotline layanan pelanggan kami di {{ phoneFullTag }}.</p>
		<div class="wpcf7" id="wpcf7-f1262-p1199-o1">
<div class="screen-reader-response"></div>
<form action="{{ url('untuk-klien/tanya-dokter') }}#gallery-details-1" method="post" class="wpcf7-form wpcf7-acceptance-as-validation" novalidate="novalidate">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="1262" />
<input type="hidden" name="_wpcf7_version" value="3.8.1" />
<input type="hidden" name="_wpcf7_locale" value="" />
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f1262-p1199-o1" />
<input type="hidden" name="_wpnonce" value="00e9119cc5" />
<input type="text" name="input-pot" value= "" />
</div>
<div class="contact_form" style="margin-top: 0;">
<div class="clearfix">
<div class="note">Bagian  yang ditandai dengan * wajib diisi</div>
<fieldset class="left">

    <label>Nama *</label><div class="block">
        <span class="wpcf7-form-control-wrap aomd-name"><input type="text" name="aomd-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" id="aomd-name" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Alamat Email *</label><div class="block">
        <span class="wpcf7-form-control-wrap aomd-email"><input type="email" name="aomd-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Nomor Kontak *</label><div class="block">
        <span class="wpcf7-form-control-wrap aomd-contact-num"><input type="text" name="aomd-contact-num" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>

<fieldset class="right">

    <label>Rencana Tanggal Kelahiran *</label><div class="block">
        <span class="wpcf7-form-control-wrap aomd-expected-date-of-delivery"><input type="text" name="aomd-expected-date-of-delivery" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required pick-date text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Rumah Sakit Bersalin *</label><div class="block">
         <span class="wpcf7-form-control-wrap aomd-hospital"><input type="text" name="aomd-hospital" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

    <label>Nama Dokter Kebidanan *</label><div class="block">
        <span class="wpcf7-form-control-wrap aomd-gynaecologist"><input type="text" name="aomd-gynaecologist" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false" /></span>
    </div>

</fieldset>
</div>

<fieldset class="page_margin_top" style="clear:both;">

    <label>Permohonan *</label><div class="block">
        <span class="wpcf7-form-control-wrap aomd-enquiry"><textarea name="aomd-enquiry" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required text_input" aria-required="true" aria-invalid="false"></textarea></span>
    </div>

</fieldset>

<p class="submit-consent">Dengan mengirimkan formulir ini, saya menerima dan menyetujui untuk disertakan dalam StemCord milis, dan dihubungi oleh StemCord dan mitra untuk komunikasi lebih lanjut.<br>
Saya memilih untuk dihubungi dengan cara:
<span class="wpcf7-form-control-wrap contact-by"><span class="wpcf7-form-control wpcf7-checkbox wpcf7-validates-as-required"><span class="wpcf7-list-item first"><input type="checkbox" name="contact-by[]" value="Telepon" />&nbsp;<span class="wpcf7-list-item-label">Telepon</span></span><span class="wpcf7-list-item last"><input type="checkbox" name="contact-by[]" value="SMS" />&nbsp;<span class="wpcf7-list-item-label">SMS</span></span></span></span></p>

<p><input type="submit" value="Submit" class="wpcf7-form-control wpcf7-submit more blue" /></p>

</div>
<div class="clear"> </div><div class="wpcf7-response-output wpcf7-display-none"></div></form></div>

	<ul class="controls page_margin_top"><li><a href="#gallery-details-close">Kembali ke halaman sebelumnya</a></li></ul></div></div></div></li>
{% else %}
	<li id="gallery-details-2" class=""><div class="columns no_width"><div class="column_left"><div class="details_box">
		
<br /><p>Kepada Yth <strong>{{ name }}</strong>, Form Informasi Anda sudah diterima.</p>
<p>Terima kasih telah mengirimkan informasi ini. Staff kami akan mengontak Anda dengan segera. Apabila ada yang ingin ditanyakan lebih lanjut silahkan hubungi {{ phoneFullTag }} atau HP {{ mobileCall }}.</p>
<br />
<p>Terima kasih</p>
<br />
<p>Salam,<br />
StemCord</p>

	<ul class="controls page_margin_top"><li><a href="#gallery-details-close">Kembali ke halaman sebelumnya</a></li></ul></div></div></div></li>
{% endif %}	
</ul>

<div class="gallery-hide">

<p>Kami ingin membantu Anda lebih lanjut tentang penyimpanan darah tali pusat, sel punca dan kondisi medis yang dapat mempengaruhi proses penyimpanan darah tali pusat. Di sini, kami telah menyediakan daftar pertanyaan yang umum ditanyakan oleh pasien  kepada <a href="{{ url('tentang-kami/pendiri') }}">Direktur Medis</a> kami di waktu yang lalu. Jika Anda memiliki pertanyaan, jangan ragu untuk mengisi <a href="#gallery-details-1">formulir</a> ini dan kami akan menjawab kepada Anda segera</p>

<p>Untuk pertanyaan umum, silakan tinggalkan pesan Anda <a href="{{ url('untuk-klien/buat-enquiry') }}" title="Buat permohonan">di sini</a> atau hubungi hotline layanan pelanggan kami di {{ phoneFullTag }}.</p>

<h3 class="box_header">Tanya &#038; Jawab bersama dr. Teo</h3>
<br />
<span class="darkblue heavy">T: Kebanyakan orang cenderung mengkaitkan Leukemia dengan kanker darah. Apakah ada jenis lain dari kanker darah agar orang menyadari bahwa ada berbagai macam kanker darah?</span>

<p>J: Tidak salah mengkaitkan kanker darah dengan Leukemia. Bagi kami hematolog, ada <strong>Limfoma</strong>, <strong>Myeloma</strong> dan <strong>Leukemia</strong>. Ketiga jenis tersebut adalah yang paling umum dari kanker darah.</p>

<p>Pertama, kanker ini berasal dari jaringan darah atau sel-sel yang ditemukan dalam darah. Tubuh Kita memiliki berbagai jenis sel darah: sel darah putih(lekosit); sel darah merah (eritrosit), plasma dan keping darah (trombosit). Kanker sel darah putih dikenal sebagai <strong>Leukemia</strong>. Hal ini terjadi ketika ada peningkatan abnormal sel-sel darah putih dalam tubuh . Kanker sel plasma dikenal sebagai <strong>Myeloma</strong>. <strong>Limfoma</strong> mengacu pada kanker sel limfatik dari sistem kekebalan tubuh di mana sel-sel limfoid muncul sebagai tumor padat. Bilamana Anda memiliki  trombosit tinggi dalam darah Anda, ini bukan merupakan kanker meskipun terjadi masalah di sumsum tulang. Namun, dalam beberapa kasus 5- 10 %  sel-sel ini dapat berkembang menjadi Leukemia pada beberapa tahun kemudian.</p>

<span class="darkblue heavy">T: Apakah saya masih bisa menyimpan darah tali pusat bayi saya jika istri saya atau saya memiliki Thalassemia minor/mayor?</span>

<p>J: Memiliki Thalassemia minor atau sifat Thalassemia biasanya merupakan kelainan darah ringan. Harapan hidup Anda normal dan Anda tidak rentan terhadap penyakit lebih dari orang lain. Namun, Anda harus memberitahukan dokter kandungan Anda selama periode antenatal awal sehingga tes skrining dapat dilakukan.</p>

<p>Selama bayi tidak beresiko menjadi Thalassemia Major, darah tali pusat dapat dikumpulkan dan disimpan, terutama untuk penggunaan bagi dirinya sendiri (autologus). Bilamana bayi lahir dengan Thalassemia Mayor, darah tali pusat akan cacat dan karenanya, tidak berguna untuk dilakukan penyimpanan.</p>

<span class="darkblue heavy">T: Saya diberitahu bahwa saya tidak bisa menyimpan darah tali pusat bayi saya jika saya pembawa Hepatitis. Apakah ini benar?</span>

<p>J: Sebaliknya, pembawa Hepatitis B (terutama ibu) tetap dapat menyimpan darah tali pusat anak mereka, hanya untuk penggunaan autologus tanpa masalah besar. Bayi Anda biasanya akan divaksinasi saat lahir dan mendapat kekebalan terhadap virus yang sama. Oleh karena itu, bahkan dalam kasus terburuk di mana darah tali pusat terkontaminasi dengan virus, dengan imunisasi  anak akan terlindung. Selain itu, saat ini ada banyak obat efektif yang dapat membasmi virus bahkan jika seseorang menjadi terinfeksi. Meskipun belum ada vaksin yang tersedia dan belum ada pengobatan  efektif yang dapat membasmi  virus Hepatitis C saat ini, Namun, menyimpan darah tali pusat masih layak.</p>

<p>Namun, darah tali pusat akan diperiksa lebih ketat jika ingin digunakan. Pro dan kontra dari penggunaan darah tali pusat harus dipertimbangkan lebih hati-hati dan penggunaan darah tali pusat hanya semata-mata bagi dirinya sendiri (autologus).</p>

<span class="darkblue heavy">T: Saya 8 bulan hamil dan sedang mempertimbangkan menyimpan darah tali pusat anak saya. Apakah masih mungkin untuk menggunakan darah tali pusat anak saya untuk terapi regeneratif?</span>

<p>J: Fakta yang sudah diketahui secara luas saat ini adalah bahwa sel punca, bisa  berasal dari darah tali pusat, sumsum tulang, darah perifer atau jaringan adiposa, semuanya telah berhasil digunakan untuk mengobati penyakit baik melalui Transplantasi Sel Punca (SCT) maupun Terapi Regeneratif. Hal ini dimungkinkan karena beberapa penyakit tidak disebabkan oleh kelainan genetik.</p>

<p>Misalnya, cerebral palsy yang disebabkan oleh hipoksia (kekurangan oksigen ke otak) dapat diobati dengan Terapi Regeneratif menggunakan sel punca darah tali pusat. Untuk kanker lainnya seperti tumor Wilm, kanker yang tidak berasal dari sumsum tulang atau darah tali pusat. Menggunakan darah tali pusat milik sendiri, benar-benar dapat meningkatkan peluang penyembuhan karena mereka belum terkena kemoterapi dan karenanya kualitasnya akan lebih baik.</p>

<p>Pada Leukemia, kesempatan terbaik untuk penyembuhan adalah dengan menggunakan sel punca dari saudara sepenuhnya cocok (allogenik related) atau donor yang tidak berhubungan (allogenik). Jika tidak ada donor tersebut tersedia, menggunakan sel  darah tali pusat anak Anda adalah pilihan yang wajar. Data dari International Bone Marrow Transplant Registry menunjukkan bahwa SCT autologus bisa dipakai sebagai pengobatan. Namun, pada kondisi tertentu seperti haemogloblinopati (anemia sel sabit besar atau misalnya thalassemia), cacat yang melekat pada sel-sel sumsum tulang. Donor akan dibutuhkan untuk menyediakan sel induk tanpa cacat utama untuk SCT.</p>

<p>Sementara ini ada beberapa kebenaran bahwa kehadiran gen abnormal mencegah penggunaan sel punca dalam beberapa penyakit, meskipun ada banyak jenis penyakit di mana penggunaan tidak dipengaruhi oleh kekhawatiran ini sama sekali.</p>

</div>																
{% endblock %}